### ISSUE TITLE
Problemas no ambiente de Homologação

### ISSUE THREAD

**Issue by arkye** [unidoscontraacorrupcao/ej-server#10]
# Conhecidas

- [ ] Rota api.dev.besouro.ejplatform.org apresenta tela default do Ingress

# Resolvidas

- [x] Apenas a rota dev.besouro.ejplatform.org pode ser acessada para utilizar o app
- [x] Perfil não possui linkage com User, tornando impossível a atualização de perfil

**Comment by ricardopoppi** [comment]
Fechando essa issue pois infra será migrada para pencil
