### ISSUE TITLE
Conceber a versão desktop dos cards de candidates

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#100]
Hoje a versão desktop do besouro mantem a largura do conteúdo no centro. No caso da visualização de candidates poderiamos aproveitar melhor esse espaço. Como os candidates devem ser exibidos de 3 em 3 será que a gente não consegue exibir a trinca de cards um do lado do outro?

Peço à @luizapeixe conceber.

**Comment by luizapeixe** [comment]
ok! Como nosso board do invision foi setado para exibir sempre em mobile, subi essa proposta no drive do besouro pra gente poder visualizar melhor e ir validando os layouts. Segue link da primeira proposta da página de lista dos candidates versão Desktop:

https://drive.google.com/file/d/13W3CgacDu-nywqOvIVJvBDNes_pHWKdH/view?usp=sharing

Obs.: aqui fica estranho se deixarmos só 3 cards aparecendo então deixei 4, tudo bem?

**Comment by ricardopoppi** [comment]
acho que ficou massa. pro desktop também é importante aquela solução que estamos bolando para não aprisionar o usuário em interações que ele não quer fazer (a discussão do carregar mais...)

**Comment by luizapeixe** [comment]
também fiquei com essa dúvida. No desktop devemos mostrar quantos cards antes do link "carregar mais candidatos"?

**Comment by ricardopoppi** [comment]
Definimos que tanto no mobile quanto no desktop vamos mostrar 10 por vez. 

(i) No feed TODOS, o carregamento dos novos 10 é automatico após o usuário ter selecionado, pressionado ou fechado (via botão fechar) todos os 10.
(ii) No feed SELECIONADOS e FAVORITOS, é necessário conceber um "carregar mais" no final

**Comment by luizapeixe** [comment]
(i): ok! acham necessário deixarmos 10 cards tb no layout no invision?
(ii): ok, feito e atualizado no invision
(iii): certo! vou trabalhar nessas soluções hoje

**Comment by luizapeixe** [comment]
(i) ok! atualizei a aba TODOS aqui: https://invis.io/SPN6XE5NFGC

também adicionei a situação "não respondeu" como opção possível no último card dessa página

**Comment by ricardopoppi** [comment]
Legal Luiza! Acho que o não respondeu não existirá (confirma @parrahenri?).
Isso porque quem não respondeu aparecerá como NÃO --

Ricardo Poppi
Whatsapp/Telegram: +55 61 9 9531 9531
Skype: rpoppi77
www.instituto.cidadedemocratica.org.br <http://www.cidadedemocratica.org.br>

**Comment by parrahenri** [comment]
Na verdade, quem ainda não se cadastrou e cuja info a TI não tiver ainda poderia aparecer como SEM RESPOSTA mesmo!

No workshop eles pediram isso!

**Comment by ricardopoppi** [comment]
Ok. É uma questão do dado que virá nesse campo na planilha e da regra final de cores que vai exigir uma issue específica. Como a tela está pronta, fechando essa aqui.
