### ISSUE TITLE
Sistematizar jornada de notificações da funcionalidade candidates

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#101]
Aqui precisamos sistematizar a jornada:

1) Usuário selecionou candidate (issue #103)

(i) splash pro usuario
ver: 
![captura de tela 2018-08-03 as 11 18 03](https://user-images.githubusercontent.com/4418975/43647771-04fa1ad8-970f-11e8-9a93-54b372a47044.png)

(ii) notificação para o usuário, dentro da aba de notificações, gera uma notificação do tipo APROVADOS, que é um texto curto
ver: 
![captura de tela 2018-08-03 as 11 19 22](https://user-images.githubusercontent.com/4418975/43647811-1e41e804-970f-11e8-8379-196997d15d40.png)

(ii) candidato recebe um email (texto em formulação)

2) Usuário pressionou candidate (issue #103)

(i) splash (wireframe em formulação)

(ii) notificação de candidate pressionado (texto em formulação)

(iii) candidato recebe um email (texto em formulação)

3) Candidato foi pra SIM em uma das 2 opções (democracia e novas medidas) (issue #115)

(i) usuários que pressionaram esse candidato recebem notificação avisando com link pra interna
(ii) esse candidato volta a ficar visível no feed, resetando, ou seja, saindo da condisção de pressionado, voltando a aparecer para os usuários que pressionaram ele

4) Usuário favoritou candidate (issue #114)

(i) splash (em formulação)
(ii) notificação de candidate favoritado (em formulação)
(iii) candidato recebe email (em formulação)

**Comment by parrahenri** [comment]
Submeti uma ao cliente e estou esperando validação
[planilha de dados para besouro.xlsx](https://github.com/unidoscontraacorrupcao/ej-server/files/2257628/planilha.de.dados.para.besouro.xlsx)

**Comment by parrahenri** [comment]
@ricardopoppi esses são?

1. clicar em apoiar
2. clicar nas redes sociais do candidato
3. clicar nos conteúdos detalhados
4. clicar em share
5. clicar em DESfavoritar

**Comment by ricardopoppi** [comment]
@parrahenri lembrete pra criar os conteúdos das msgs

**Comment by parrahenri** [comment]
1. selecionar
splash
CANDIDATA SELECIONADA COM SUCESSO 
Agradecemos sua participação! Continue selecionando candidatos que te interessem e não deixe de conferir sua caixa de notificações para acompanhar novidades sobre suas seleções

notificação
FULANA DE TAL: Obrigado por me selecionar aqui no app! Para conhecer mais sobre minhas propostas e história, acesse meu site: http://www.sitedacandidata.com.br

email (vai para a candidata)

Boas notícias! Você acaba de ser selecionada por um usuário no aplicativo da campanha Unidos Contra a Corrupção, o que significa que essa pessoa se interessou pelo seu perfil e pelos seus compromissos e agora vai poder ver mais detalhes e informações sobre você.

Atenciosamente.
Unidos Contra a Corrupção



2. pressionar
splash
CANDIDATA PRESSIONADA COM SUCESSO 
Agradecemos sua participação! Continue pressionando candidatos que não se comprometeram ainda e não deixe de conferir sua caixa de notificações para acompanhar novidades sobre essa pressão

notificação
Você pressionou FULANO DE TAL porque ele ainda não se comprometeu com os compromissos da Unidos Contra a Corrupção. 

*CASO HAJA MUDANÇA DE POSIÇÃO 
notificação 2
FULANO DE TAL: Acabei de me comprometer com o NOME DO ITEM. Gostaria de me reavaliar como candidato?

email (vai para a candidata)
Um usuário acaba de solicitar que você se comprometa com os compromissos da campanha Unidos Contra a Corrupção. Essa pessoa conheceu seu perfil e gostaria de pedir que registre seu compromisso.

Quando registrar o compromisso, todos os usuários que tiveram solicitado que você o fizessem receberão avisos diretamente, podendo avaliar positivamente seu perfil! Não perca tempo e registre seu compromisso agora mesmo:

[ link para site da campanha onde candidatos podem se cadastrar ]


3. favoritar
splash
CANDIDATA FAVORITADA COM SUCESSO 
Agradecemos sua participação! Continue selecionando candidatos que te interessem e não deixe de conferir sua caixa de notificações para acompanhar novidades sobre suas seleções

notificação
FULANA DE TAL: Obrigado por me favoritar aqui no app! Minhas redes sociais estão no app para acompanhar meu dia a dia e ficarmos em contato! 

email (vai para a candidata)

Excelente notícia! Depois de te selecionar e conhecer mais sobre seu perfil no aplicativo da campanha Unidos Contra a Corrupção, um usuário acaba de favoritar você. Significa que ela gostou muito de seu perfil e pensa em votar em você no dia da eleição.

Agora, seu perfil será mais fácil de ser visto por essa pessoa, que poderá usar o app no dia das eleições, como um santinho.

Atenciosamente.
Unidos Contra a Corrupção

**Comment by parrahenri** [comment]
fazendo! notificação dos favoritos não tá prevista na tela das notificações ainda @luizapeixe? acho que deixamos passar e lá só tem o "aprovados" e "reprovados", que na vdd são o SELECIONADOS e o PRESSIONADOS (nova nomenclatura que validamos)

**Comment by parrahenri** [comment]
Estao aqui: https://docs.google.com/document/d/1yzomTxjpDE-8xiVLqpyOvAP7jKQKc4m5MTBrIAhCxPQ/edit

**Comment by parrahenri** [comment]
@ricardopoppi nicole viu e fez 1 comentário que já gerou as mudanças necessárias. link tá com versão validada, por tanto!

**Comment by luizapeixe** [comment]
@parrahenri não considerei uma categoria "favoritos" na tela de notificações propositadamente por 2 motivos: 1. todos os FAVORITOS foram antes SELECIONADOS, então a categoria selecionado já abrigaria os favoritos e 2. falta de espaço. Faz sentido pra vocês mantermos assim ou acham que realmente precisamos de uma categoria a mais nas notificações?

**Comment by parrahenri** [comment]
Entendi!
Então nesse caso não teremos notificação! Que acha, Poppi?

**Comment by ricardopoppi** [comment]
Tb acho uma boa não ter. Assim a gente concentra os pushes nas interações
mais relevantes pro objeto do app: SELECIONAR e PRESSIONAR --

Ricardo Poppi
Whatsapp/Telegram: +55 61 9 9531 9531
Skype: rpoppi77
www.instituto.cidadedemocratica.org.br <http://www.cidadedemocratica.org.br>

**Comment by ricardopoppi** [comment]
@parrahenri reformulando aqui: acho legal ter, mas dentro da mesma categoria de selecionados, como sugeriu a @luizapeixe pra não carregar demais as categorias das notificações

**Comment by ricardopoppi** [comment]
pessoal, como já está tudo formulado e já passei pras issues de desenvolvimento, vou fechar essa aqui
