### ISSUE TITLE
Implementar o app candidates no besouro com o feed de TODOS

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#103]
### Feed TODOS

- [x] Feed TODOS (home) com todos os cards, [WIREFRAME](https://projects.invisionapp.com/d/main#/console/14558908/311026533/preview)
- cards serão exibidos de 10 em 10, escolhidos aleatoriamente dentro dos candidatos com match na mesma UF do usuário (para os deslogados a exibição é aleatória considerando a base completa) ou conforme o filtro setado
- em cada card, conforme wireframe, o usuário poderá:
(i) cards de candidatos com tudo SIM: SELECIONAR ou FECHAR
(ii) cards de candidatos com algum NÃO ou SEM RESPOSTA: SELECIONAR, PRESSIONAR ou FECHAR
- Em suma:
  - para candidatos com "SIM - SIM - SIM" só aparece o botão "selecionar" ou "fechar"
  - para candidatos com algum "NÃO" ou "SEM RESPOSTA" aparece o botão "selecionar", o botão "pressionar" e o "fechar"
- a regra de carregamento dos cards é: 
(i) aleatório dentro da UF do usuário, 
(ii) 10 em 10, 
(iii) só carrega os próximos 10 qdo o usuário tiver interagido com todos os 10 primeiros
(iv) não precisa persistir entre seções. Se o usuário fechar o app, voltar ou deslogar, o próximo login carrega novos 10, independente do que ele fez na seção anterior.
(v) o filtro persiste em novas cargas dentro da mesma seção
(vi) não precisa persistir entre seções também, nova seção, filtro zerado

#### **Conteúdo do texto introdutório do feed:**
TEXTO ABERTURA
Olá! Selecione candidatos que te interessarem e pressione quem ainda não tiver se comprometido com as Novas Medidas e o Pacto pela Democracia! Você também pode favoritar e divulgar bons candidatos! :)

Ah! Veja atentamente quem tem Ficha Limpa e que não tem! 

##### (i) toast pro usuario. 
**Conteúdo:** 
CANDIDATA SELECIONADA COM SUCESSO
Agradecemos sua participação! Continue selecionando candidatos que te interessem e não deixe de conferir sua caixa de notificações para acompanhar as novidades 

##### (ii) notificação para o usuário, dentro da aba de notificações, gera uma notificação do tipo APROVADOS, que é um texto curto. Clique na notificação leva para o site do candidato
**Conteúdo:**
Você selecionou a candidata \<NOME DA CANDIDATA\>. Para conhecer mais sobre as suas propostas e sua história, acesse: http://www.sitedacandidata.com.br

IMAGEM EXEMPLO
![captura de tela 2018-08-06 as 14 26 17](https://user-images.githubusercontent.com/6249788/43731435-e33939ce-9984-11e8-8e80-21408a2b6b77.png)

##### (iii) candidato recebe um email
**Conteúdo:**
Assunto: Você foi selecionado por uma pessoa da campanha Unidos Contra a Corrupção
Boas notícias! Você acaba de ser selecionada por um usuário no aplicativo da campanha Unidos Contra a Corrupção, o que significa que essa pessoa se interessou pelo seu perfil e pelos seus compromissos e agora vai poder ver mais detalhes e informações sobre você.

Atenciosamente.
Unidos Contra a Corrupção

##### (i) toast pro usuário
**Conteúdo:**
CANDIDATA PRESSIONADA COM SUCESSO 
Agradecemos sua participação! Continue pressionando candidatos que não se comprometeram ainda e não deixe de conferir as novidades na sua caixa de notificações 

##### (ii) notificação de candidate pressionado (texto em formulação)
**Conteúdo:**
Você pressionou \<NOME DO CANDIDATO\> porque ele ainda não se comprometeu com os compromissos da Unidos Contra a Corrupção.

IMAGEM EXEMPLO:
![captura de tela 2018-08-06 as 14 26 33](https://user-images.githubusercontent.com/6249788/43731445-e9afc570-9984-11e8-8688-375d42c75b57.png)

##### (iii) candidato recebe um email (texto em formulação)
**Conteúdo:**
Assunto: Você recebeu um pedido de uma pessoa da campanha Unidos Contra a Corrupção
Um usuário acaba de solicitar que você se comprometa com os compromissos da campanha Unidos Contra a Corrupção. Essa pessoa conheceu seu perfil e gostaria de pedir que registre seu compromisso.

Quando registrar o compromisso, todos os usuários que fizeram essa solicitação receberão avisos diretamente, podendo avaliar positivamente seu perfil! Não perca tempo e registre seu compromisso agora mesmo:

[http://www.unidoscontraacorrupcao.org.br/#candidatos]

Atenciosamente.
Unidos Contra a Corrupção

**Comment by parrahenri** [comment]
Botão APOIAR: vai levar para um site externo (que será url dos sites de crowdfunding dos candidatos)
