### ISSUE TITLE
Atualizar os wireframes com o detalhamento das regras de negócio

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#111]
@luizapeixe a partir da nossa discussão no invision, peço atualizar os wireframes com as novas regras (cc @parrahenri ):

- [x] Os cards de candidatos devem ter uma opção de FECHAR que seja visível. Talvez manter a coerência com o (X) fechar dos modais atuais do app. Acredito que esse botão só faça sentido na aba TODOS e eventualmente na aba SELECIONADOS (ver item abaixo), já que na coleção de favoritos o usuário tem como remover desfavoritando
- [x] Conceber uma forma do usuário "remover seleção" do candidato. Atualmente se ele selecionou uma vez, é pra sempre. Será que poderemos usar o mesmo fechar (X) pra isso também?
- [x] Nos feed de TODOS não há botão de carregar mais, porém nos feeds de SELECIONADOS e FAVORITOS é importante uma solução de ver mais ou carregar mais (a cada 10 também) pois por questão de segurança da infra não poderemos exibir sempre todos de uma vez  (que podem ser muitos, principalmente no feed selecionados), ainda que o usuário tenha a opção de carregar mais até aparecerem todos os que ele selecionou
- [x] Vamos precisar de uma tela interna de candidate, no estilo que temos nas missões, exibindo as mesmas informações (considerar a versão mais detalhada) e possibilidades de interação presentes nos cards. A regra é a mesma dos cards em relação a quando aparecem as opções de selecionar, pressionar ou favoritar.
- [x] "Conceber uma forma do usuário "remover seleção" do candidato. Atualmente se ele selecionou uma vez, é pra sempre"
- [ ] Conceber uma maneira fácil de RESETAR o filtro, quando o usuário selecionou parâmetros e ocultou. Da maneira atual, a condição de filtrado pode ficar invisível para o usuário, que pode esquecer que fez seleções específicas de visualização
- [x] Conceber os splashs para todas as interações com os cards:
(i) SELECIONAR
(ii) PRESSIONAR
(iii) FAVORITAR
(iv) DESFAVORITAR
- [x] Atualizar o painel de configuração das notificações com os novos nomes SELECIONAR e PRESSIONAR, além de criar o tipo FAVORITO
- [x] Produzir um exemplo de inbox com esses três tipos de notificações (conteúdos na #101 )

**Comment by parrahenri** [comment]
@luizapeixe que acha de um X na aba SELECIONADOS quando o user quiser remover?

@ricardopoppi notou isso:
"Conceber uma forma do usuário "remover seleção" do candidato. Atualmente se ele selecionou uma vez, é pra sempre"

**Comment by parrahenri** [comment]
atualizei na descrição tb

**Comment by luizapeixe** [comment]
Tenho uma sugestão pra essa questão dos botões "fechar card" e "remover seleção",  que é basicamente usar o espaço do recurso "compartilhar" presente apenas na aba FAVORITOS, vejam:

card na aba FAVORITOS:
![captura de tela 2018-08-06 as 13 01 06](https://user-images.githubusercontent.com/6249788/43727600-d4eaee14-9978-11e8-815c-8ca839394ba8.png)

card na SELECIONADOS:
![captura de tela 2018-08-06 as 13 03 28](https://user-images.githubusercontent.com/6249788/43727738-2d5b6790-9979-11e8-9493-e10de8b0b3cc.png)

card na TODOS:
![captura de tela 2018-08-06 as 13 05 10](https://user-images.githubusercontent.com/6249788/43727804-60bce4ec-9979-11e8-9559-523e0a6736a7.png)

que tal?

**Comment by ricardopoppi** [comment]
Achei bom! --

Ricardo Poppi
Whatsapp/Telegram: +55 61 9 9531 9531
Skype: rpoppi77
www.instituto.cidadedemocratica.org.br <http://www.cidadedemocratica.org.br>

**Comment by luizapeixe** [comment]
sobre Conceber os splashs (serão toasts, né? gosto mais dos toasts nesse caso pq deixar a experiência mais ágil de dinâmica que os splashs) para todas as interações com os cards:

(i) SELECIONAR
![captura de tela 2018-08-06 as 14 26 17](https://user-images.githubusercontent.com/6249788/43731435-e33939ce-9984-11e8-8e80-21408a2b6b77.png)

(ii) PRESSIONAR
![captura de tela 2018-08-06 as 14 26 33](https://user-images.githubusercontent.com/6249788/43731445-e9afc570-9984-11e8-8688-375d42c75b57.png)

(iii) FAVORITAR
![captura de tela 2018-08-06 as 14 26 53](https://user-images.githubusercontent.com/6249788/43731463-f9f14486-9984-11e8-91eb-b93ba3e0e31a.png)


(iv) DESFAVORITAR / remover seleção
![captura de tela 2018-08-06 as 14 27 26](https://user-images.githubusercontent.com/6249788/43731478-0606b5b2-9985-11e8-9b55-26d7f26c2173.png)

**Comment by parrahenri** [comment]
gostei!

**Comment by parrahenri** [comment]
sim! toasts! :)
Ficaram ótimos!

**Comment by luizapeixe** [comment]
desenhei a página interna dos candidatos seguindo um mix de Página interna da missão com Cards de candidatos. Algo importante de ressaltar é que os botões de interação 1. Selecionar; 2. Pressionar; 3. Favoritar; 4. Doar; 5. Remover seleção e 6. Desfavoritar é que num primeiro momento apenas os 1 e 2 aparecem de fato. Os botões 3 e 4 só ficam habilitados se o user já tiver selecionado o candidato, assim como os botões 5 e 6 também são condicionados pela ação dos botões 1 e 3. Além disso, o botão doar só aparece para os candidatos que forem selecionados e VERDES. Enfim, temos uma série de condicionais para a exibição e tentando contemplar todas as situações, fiz os seguintes 4 layouts:

a. candidato não-selecionado: https://invis.io/G5NDI95XYNP
b. candidato selecionado verde: https://invis.io/N2NDIA7SQXF
c. candidato selecionado não-verde: https://invis.io/YANDIF0ZDW5
d. candidato selecionado, não-favoritado não-verde: https://invis.io/MFNDIAQ6G5T

**Comment by ricardopoppi** [comment]
@luizapeixe @parrahenri sobre as internas, comentei direto no invision, principalmente sobre o entendimento de colocar todas as interações nas internas. o correto é que as internas tenham as mesmas regras de interação dos cards, a depender do momento:
FEED TODOS: selecionar e/ou pressionar (a depender da cor)
FEED SELECIONADOS: apoiar e/ou favoritar (a depender da cor)
FEED FAVORITOS: compartilhar, desfavoritar e/ou apoiar (a depender da cor)

**Comment by ricardopoppi** [comment]
@luizapeixe sobre a sua proposta do 
(i) remover seleção/fechar nos cards (https://github.com/unidoscontraacorrupcao/ej-server/issues/111#issuecomment-410761012) pode atualizar as telas do invision com essa opção?

Os toasts eu vou usar direto das imagens do comentário mesmo.

**Comment by luizapeixe** [comment]
Ok! Corrigi as internas em cima dos comentários no invision e também já estão atualizadas as telas de listas de cards
todos: https://invis.io/SPN6XE5NFGC
selecionados: https://invis.io/PTN7U215BQW
favoritados: https://invis.io/ZUN7U15JD4C

**Comment by ricardopoppi** [comment]
@luizapeixe sensacional, mto bom mesmo! Pelas minhas contas aqui, ficou faltando só o ítem do filtro, dessa mega issue :-P

Sobre isso quero complementar e pedir que pense com carinho. Ele não vai ser implementado ainda essa semana, então ganhamos um tempo pra essa reflexão. O dilema atual é o seguinte: a mesmo tempo que temos um game que incentiva os usuários a consumir cards de 10 em 10 como num deck de cartas, temos também o filtro que é voltado para um outro tipo de usuário. O que acabamos fazendo foi misturar as duas lógicas. Isso será necessário manter. A minha provocação: além de bolar uma solução visível para quando o filtro está ativo/inativo, será que não poderíamos pensar ele um pouco mais escondido de modo a não interferir na experiencia de uso dos 90% que não usarão?

**Comment by parrahenri** [comment]
Achei massa tb!
E acho boa a sugestão do Poppi! Assim que tiver desenhado algo me avisa que eu apresento ao cliente pra ver se aprovam (pq eles curtem o filtro).

abs!

**Comment by luizapeixe** [comment]
e se a gente deixasse a aba de filtro tb sticky na rolagem, com um ícone de "lixo" ao lado da seta de dropdown, tipo assim:

![captura de tela 2018-08-10 as 13 22 02](https://user-images.githubusercontent.com/6249788/43969438-856fd8b0-9ca0-11e8-93d1-346748975128.png)

Daí quando o user clica na seta, o dropdown desce normal

![captura de tela 2018-08-10 as 13 22 14](https://user-images.githubusercontent.com/6249788/43969492-ab819d36-9ca0-11e8-8d8e-847ed144c177.png)

porém se o user der scroll pra baixo, a aba de filtro sobe e se oculta automaticamente.

O que vocês acham?

**Comment by parrahenri** [comment]
não curti muito o ícone de lixo

sobre a solução: parece boa

**Comment by ricardopoppi** [comment]
Uma referencia, é como o app do mercado livre usa:

![photo_2018-08-12_19-50-17](https://user-images.githubusercontent.com/1162183/44007296-284977c0-9e69-11e8-9cc7-c7447b09f29e.jpg)

**Comment by luizapeixe** [comment]
Que tal assim pessoal:

![captura de tela 2018-08-13 as 18 40 42](https://user-images.githubusercontent.com/6249788/44060221-55ef3842-9f2a-11e8-9d44-e824953e3e17.png)

O ícone de lixo agora é mais um "reciclagem" e os filtros selecionados ficam exibidos acima da busca, sendo facilmente deletáveis (um exemplo de aplicação dessa solução pros filtros: https://cenazero.com.br/busca/equipamentos/tripe/sao-paulo/sao-paulo )

**Comment by ricardopoppi** [comment]
@luizapeixe achei a ideia massa. Num primeiro momento, achei que iria gerar confusão. Mas usando o exemplo que vc passou (cenazero), pareceu funcionar bem. A única ressalve é que temo um problema para implementar: como misturamos filtros estáticos com filtro de nome, não poderemos ativar automaticamente os filtros, exigindo que o usuário sempre clique no botão filtrar.

Opções que vejo pra vc avaliar:
1) tirar as etiquetas azuis e os filtros sempre se refletirem pelo que está descrito nos próprios forms/imputs. Nesse caso o botão reciclar (resetar) retorna os imputs pros valores default
2) os filtros estáticos ficarem mais acima e apenas o nome ficar ao lado do botão filtrar, que só valeria pra ele já que os outros ativam automaticamente

Como o overhead de desenvolvimento da opção (2) é mto grande pro tempo que temos, eu ficaria com a (1) pra essa versão.

**Comment by luizapeixe** [comment]
ok! adotando a opção 1 a gente retoma a solução que já tinha sido pensando pra aba de filtros mesmo, só adicionamos o recurso de "reciclar"

telas atualizadas:
-> aba TODOS / fechada: https://invis.io/SPN6XE5NFGC
-> aba SELECIONADOS/ aberta: https://invis.io/PTN7U215BQW

**Comment by ricardopoppi** [comment]
Blz, issue #122 atualizada, fechando essa
