### ISSUE TITLE
Implementar a aba de SANTINHOS

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#112]
### Funcionamento da aba SANTINHOS e ajustes de implementação

- [x] Destaque maior para o Filtro (@luizapeixe concebeu um destaque azul nos wireframes)

- [x] O clique no nome do candidato e na foto leva para a interna do candidato, em qualquer aba, tanto para logado quanto deslogado

- [x] O nome da aba favoritar vira SANTINHO

- [x] "ADICIONAR EM SANTINHOS" passa a ser a única interação possível na aba de todos, além do acesso à interna do candidato qdo clicar no nome e foto (item 2)

- [x] "ADICIONAR EM SANTINHOS" também será a única interação possível na aba de SELECIONADOS (com isso será necessário ocultar também o botão APOIAR)

- [x] A aba SANTINHOS ganha botão no menu e na navbar

- [x] Os pressionados pelo usuário passam a aparecer na aba TODOS

- [x] Titulos no header referenciarem a aba onde o usuário se encontra: "TODOS OS CANDIDATOS", "SELECIONADOS" e "SANTINHO" (conforme wireframes)

- [x] Substituir o botão fechar pelo novo botão "esconder" (conforme wireframes)

- [x] No menu hamburguer trocar "Voltar às Novas Medidas" por "Site da campanha" (confore wireframes)

- [x] Incluir uma mensagem no final da rolagem dos cards, quando acabam os cards: "Não há mais candidatos"

### Sobre o comportamento do compartilhamento:

(i) Compartilhar será mantido na aba TODOS, SELECIONADOS e SANTINHOS, para todas as cores
(ii) O "ADICIONAR EM SANTINHOS" estará disponível também para os vermelhos
(iii) Vai haver conteúdos diferentes no compartilhamento dependendo da cor quando feito na aba SANTINHOS e em qualquer outra aba (prever isso)

- [x] Textos que serão enviados no quote do compartilhamento para essa fase (@parrahenri precisamos formular e validar esses):

(i) card vermelho em qualquer aba
\<nome-do-candidato\> não atestou passado limpo ou não se comprometeu. Compartilhe a informação.

(ii) card cinza em qualquer aba
Quem luta contra a corrupção e defende a democracia exige compromisso. \<nome-do-candidato\> não respondeu tudo o que pede a campanha. Compartilhe a informação.

(iii) card verde em qualquer aba
Quem é contra corrupção e defende a democracia merece ser lembrado! \<nome-do-candidato\> tem uma candidatura comprometida. Salve como santinho e/ou compartilhe.

### Ajustes de guerrilha que serão revertidos depois

- [x] Ocultar os botões de missões tanto do menu quanto da navbar

- [x] Ocultar os botões "PRESSIONAR" e "SELECIONAR" nos cards da aba todos

- [x] Não exibir a aba "SELECIONADOS" quando o usuário tiver número de selecionados = 0 (igual a zero)

- [x] Ocultar o botão "APOIAR" que aparece nos cards na aba SELECIONADOS

### WIREFRAMES

aba TODOS: https://invis.io/AZO5FHSX7SD *
aba SELECIONADOS: https://invis.io/ZSO5FIB4NJE
aba SANTINHO: https://invis.io/N9O5FIHSMG7
menu hamburguer: https://invis.io/Z3O5FRTF2KS
*reparem q o fundo do botão "fechar" foi alterado de rosa pra cinza (#B7B8B7). A intensão é deixar esse botão mais discreto e chamar mais atenção para as outras interações com o card

icones no drive
Salvar como santinho: https://drive.google.com/file/d/1qKJVV1J1r9_0s_fqGl_H9-5Q19SIW0Iv/view?usp=sharing
Desfazer santinho: https://drive.google.com/file/d/1f365Uu2sX63qJZHleb1fl7HSWDWrpdyW/view?usp=sharing

### Jornada de toasts e notificações internas do app (@parrahenri precisamos validar esse texto o quanto antes)

- [x] Conteúdos dos toasts e notificação interna do app

#### (i) Toast para o usuário
**Conteúdo:**
CANDIDATO/A ADICIONADO A SANTINHOS 
Continue adicionando candidatos/as para o dia da eleição e acesse sua aba SANTINHO

#### (ii) notificação de candidate adicionado a santinhos
**Conteúdo:**
Você adicionou o candidato/a <nome-do-candidato> à sua lista de SANTINHOS! Para saber mais informações sobre ele/a acesse sua página! (mensagem link para a interna da candidata)

===IGNORAR DAQUI PRA BAIXO - CONTEUDO ANTIGO DA ISSUE DESATUALIZADO===
===IGNORAR DAQUI PRA BAIXO - CONTEUDO ANTIGO DA ISSUE DESATUALIZADO===
===IGNORAR DAQUI PRA BAIXO - CONTEUDO ANTIGO DA ISSUE DESATUALIZADO===
===IGNORAR DAQUI PRA BAIXO - CONTEUDO ANTIGO DA ISSUE DESATUALIZADO===
===IGNORAR DAQUI PRA BAIXO - CONTEUDO ANTIGO DA ISSUE DESATUALIZADO===
===IGNORAR DAQUI PRA BAIXO - CONTEUDO ANTIGO DA ISSUE DESATUALIZADO===

- [x] Aba favoritos com apenas os candidates favoritados, [WIREFRAME](https://projects.invisionapp.com/d/main#/console/14558908/311277094/preview)
Regra de carga:
- são exibidos todos os candidates favoritados pelos usuário, mesmo card com os detalhes utilizado na aba de SELECIONADOS
- número da urna nos cards da aba de FAVORITOS é exibido com uma cor diferente (destaque)
- aleatorio
- 10 em 10, com o botão mais ao final carregando mais 10 e aumentando o tamanho do feed
- em cada card, conforme wireframe, o usuário poderá:
(i) para candidates "SIM - SIM - SIM" o usuário pode "DESFAVORITAR" ou "APOIAR"
(ii) para candidates com algum "NÃO" ou "PARCIAL", o usuário só pode "DESFAVORITAR"
(iii) cada card tem a opção de compartilhar com um texto padrão apontando pro link da interno daquele candidato

Conteúdo do texto padrão do botão favoritar:
"Conheci os compromissos desse candidato e agora é um dos meus favoritos! Clique e conheça seu perfil também! \<link da interna do candidato\>"

- [x] Incluir o botão FAVORITAR nos cards da aba SELECIONADOS, conforme a regra:
(i) cards de candidates com tudo SIM: FAVORITAR ou APOIAR (favoritar leva pra aba de favoritos e apoiar para o site de crowdfunding do candidato)
(ii) cards de candidates com algum "NÃO" ou "PARCIAL": FAVORITAR

- [x] Desenvolver a JORNADA qdo o usuário favorita um candidate

#### (i) toast para o usuário
**Conteúdo:**
CANDIDATA FAVORITADA COM SUCESSO 
Agradecemos sua participação! Continue favoritando candidatos que te interessem e não deixe de conferir sua caixa de notificações para acompanhar as novidades

#### (ii) notificação de candidate favoritado
**Conteúdo:**
Você favoritou a candidata FULANA DE TAL! As redes sociais dela estão aqui no app para você acompanhar seu dia a dia e entrar em contato! 
(mensagem linka para a interna da candidata)

IMAGEM EXEMPLO:
![captura de tela 2018-08-06 as 14 26 53](https://user-images.githubusercontent.com/6249788/43731463-f9f14486-9984-11e8-91eb-b93ba3e0e31a.png)

![captura de tela 2018-08-06 as 14 27 26](https://user-images.githubusercontent.com/6249788/43731478-0606b5b2-9985-11e8-9b55-26d7f26c2173.png)

#### (iii) candidato recebe email
**Conteúdo:**

Excelente notícia! Depois de te selecionar e conhecer mais sobre seu perfil no aplicativo da campanha Unidos Contra a Corrupção, um usuário acaba de favoritar você. Significa que ela gostou muito de seu perfil e pensa em votar em você no dia da eleição.

Agora, seu perfil será mais fácil de ser visto por essa pessoa, que poderá usar o app no dia das eleições, como um santinho.

Atenciosamente.
Unidos Contra a Corrupção

**Comment by danielhmarinho** [comment]
@ricardopoppi esse item iii vai embora né?

**Comment by ricardopoppi** [comment]
Sim, na nova lógica dos e-mails incluiremos como indicador no digest.

Lembra que tudo de favoritos por enquanto é branch pra não afetar o prod que vai entrar hj

**Comment by danielhmarinho** [comment]
@ricardopoppi nao vai afetar a prod de hoje. A jornada precisa ser validada em dev e o psuh precisamos resolver antes de finalizar o push da jornada, A parte de candidatos esta com o david entao eu precisava começar a adiantar alguma coisa pra nao ficar parado =/

**Comment by ricardopoppi** [comment]
Tá certíssimo! Quanto antes tivermos isso pronto melhor, aí podemos usar o tempo pros ajustes.

**Comment by danielhmarinho** [comment]
@ricardopoppi uma dúvida, no wireframe os candidatos favoritados continuam sendo mostrados na aba de selecionados mas com o botão desfavoritar. Não fica um pouco redundante? Ou é esse comportamento mesmo?

**Comment by ricardopoppi** [comment]
@luizapeixe @parrahenri é isso mesmo? a principio me parece ok a redundancia já que favoritos é pra usar no dia da eleição, mas vale confirmar isso.

**Comment by danielhmarinho** [comment]
@ricardopoppi outro ponto é a necessidade da aleatoriedade do retorno. Precisa disso mesmo? Acho que serão poucos candidatos e as pessoas já favoritaram então a ordem ser aleatória acho meio desnecessário e só onera o backend.

**Comment by ricardopoppi** [comment]
@danielhmarinho concordo, favoritos não precisa ser aleatório não

**Comment by luizapeixe** [comment]
isso mesmo galera! a ideia inicial é manter realmente todos na aba de TODOS, inclusive os selecionados

**Comment by danielhmarinho** [comment]
@luizapeixe perai entao. Devemos manter os selecionados na aba de todos e os favoritos na aba de selecionados? E quanto ao de selecionados então esta confirmado que devemos deixar apenas alterando o botão?

**Comment by ricardopoppi** [comment]
@danielhmarinho acho que a @luizapeixe trocou os nomes. o que ela quiz dizer que os favoritados permanecem na aba de selecionados e são apenas replicados na aba favoritos. O card e interna passa então a exibir o botão "desfavoritar".

**Comment by ricardopoppi** [comment]
Por questões de simplificação de arquitetura, definimos que os feeds vão funcionar assim: se selecionou fica unicamente no selecionados. se favoritou, fica unicamente na aba de favoritos.

@luizapeixe pode ajudar nos ajustes dos conteúdos dos toasts que aparecem no corpo da issue? Os textos precisam ser menores e talvez fazer menção à aba de favoritos, como vc destacou na nossa conversa no telegram

**Comment by danielhmarinho** [comment]
@ricardopoppi @luizapeixe acho que faltou alteração em dois textos. Quando for desfavoritado e quando for deselecionado

**Comment by ricardopoppi** [comment]
@danielhmarinho segue textos (cc @luizapeixe):

"deselecionado(a) com sucesso
Para encontrar \<Candidate_name + partido\> novamente vá a aba de TODOS"

"desfavoritado(a) com sucesso
Para encontrar  \<Candidate_name + partido\> novamente vá à aba de SELECIONADOS"

**Comment by luizapeixe** [comment]
Sobre dar mais destaque pro filtro, sugeri já tem um tempo que a gente altere a cor da barra do filtro justamente pensando em dar mais destaque

filtro fechado:
![captura de tela 2018-09-19 as 17 51 21](https://user-images.githubusercontent.com/6249788/45780772-ace7e500-bc34-11e8-910d-9d9c85c0bd8c.png)

filtro aberto:
![captura de tela 2018-09-19 as 17 51 28](https://user-images.githubusercontent.com/6249788/45780775-af4a3f00-bc34-11e8-9568-bede078612ae.png)

**Comment by parrahenri** [comment]
@luizapeixe e @ricardopoppi:

Parra, vamos lá.
 
O que decidimos é o seguinte.
 
Vamos mesmo com: “salvar como santinho”.
 
No caso do símbolo, discutimos que a estrela é um símbolo bastante difundido de favorito, isto é, de algo que você guarda para conferir depois.
 
Além disso, a palavra “estrela” é simples e fácil para a gente usar na própria comunicação (missões, posts, emails, etc).
 
A gente pode fazer um post dizendo “Você sabia que poderia salvar seu candidato como um santinho digital apenas apertando na estrela?”
 
Portanto, essa parte está decidida. Blz?
 
Abs, Bene.

**Comment by parrahenri** [comment]
De acordo sobre a sugestão pro filtro! Tem como aumentar ele? E em compensação, diminuimos o texto de abertura? @ricardopoppi @luizapeixe

**Comment by luizapeixe** [comment]
> De acordo sobre a sugestão pro filtro! Tem como aumentar ele? E em compensação, diminuimos o texto de abertura? @ricardopoppi @luizapeixe

aumentar a altura da barra azul? Receio q aumentando barra podemos atrapalhar a visualização dos cards no mobile. Sugiro q a gente faça um teste com ele assim azulão pra ver se só com a alteração de cor já conseguimos o destaque que estamos buscando. Tendo a crer q o azul já resolverá essa questão :)

**Comment by parrahenri** [comment]
Conteúdos validados pelo cliente
https://docs.google.com/document/d/1RFcjDSEI0jBInPnKKcYI7_GEAcBfxvTL76K1veN4dPY/edit

**Comment by parrahenri** [comment]
@ricardopoppi essa entra?

QUANDO clica em "favoritar"
Conteúdo do texto padrão do botão favoritar:
"Conheci os compromissos desse candidato e agora está no meu SANTINHO! Clique e conheça seu perfil também! <link da interna do candidato>"

**Comment by parrahenri** [comment]
E essa?

(iii) candidato recebe email
Conteúdo:

Excelente notícia! Depois de te selecionar e conhecer mais sobre seu perfil no aplicativo da campanha Unidos Contra a Corrupção, um usuário acaba de favoritar você. Significa que ela gostou muito de seu perfil e pensa em votar em você no dia da eleição.

Agora, seu perfil será mais fácil de ser visto por essa pessoa, que poderá usar o app no dia das eleições, como um santinho.

Atenciosamente.
Unidos Contra a Corrupção

**Comment by ricardopoppi** [comment]
@parrahenri sobre o primeiro comentario onde isso apareceria?

sobre o segundo, não poderemos enviar esses emails, pelo bloqueio de spam

**Comment by parrahenri** [comment]
o 1o. deve ser o toast antigo que caducou então. Sobre o 2o. ok!

**Comment by ricardopoppi** [comment]
@parrahenri então blz. realmente os toasts e notificações internas ficaram com esse conteúdo aqui: 

(i) Toast para o usuário
Conteúdo:
CANDIDATO/A ADICIONADO A SANTINHOS
Continue adicionando candidatos/as para o dia da eleição e acesse sua aba SANTINHO

(ii) notificação de candidate adicionado a santinhos
Conteúdo:
Você adicionou o candidato/a à sua lista de SANTINHOS! Para saber mais informações sobre ele/a acesse sua página! (mensagem link para a interna da candidata)
