### ISSUE TITLE
Implementar a interna dos candidates

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#113]
Algo importante de ressaltar é que as internas mantem a mesma regra de interação atualmente implementada nos cards (ignorar o favoritar por enquanto): 

os botões de interação 1. Selecionar; 2. Pressionar; 3. Favoritar; 4. Doar; 5. Remover seleção e 6. Desfavoritar é que num primeiro momento apenas os 1 e 2* aparecem de fato (*botão 2 não aparece para candidatos VERDES e VERMELHOS). Os botões 3 e 4 só ficam habilitados se o user já tiver selecionado o candidato, assim como os botões 5 e 6 também são condicionados pela ação dos botões 1 e 3. Além disso, o botão doar só aparece para os candidatos que forem selecionados e VERDES. Enfim, temos uma série de condicionais para a exibição e tentando contemplar todas as situações, fiz os seguintes 5 layouts:

a. candidato não-selecionado verde: https://invis.io/G5NDI95XYNP
b. candidato não-selecionado não-verde: https://invis.io/MQNDJR275ED
c. candidato selecionado verde: https://invis.io/N2NDIA7SQXF
d. candidato selecionado não-verde: https://invis.io/YANDIF0ZDW5
e. candidato selecionado, favoritado não-verde: https://invis.io/MFNDIAQ6G5T

Essa issue então compreende:

- [ ] Desenvolvimento visual das internas (front)

- [ ] Ativação do botão "compartilhar" nos cards e nas internas, compartilhando a URL da interna com os seguintes metadados (texto):

CARD OU INTERNA VERMELHO (@parrahenri há um problema com esse texto. A nossa regra de cards vermelhos vale para qualquer NÃO. Mesmo que a tendencia é que os vermelhos sejam os fichas sujas, pode acontecer uma excessão. Então esse texto tem que ser mais genérico ou incluir a possibilidade do candidato só ser contra as novas medidas ou pacto. Como faz?)
Título: Quem não tem passado limpo não pode nos representar.
Subtítulo: \<nome-do-candidato\> não atestou passado limpo. Vamos divulgar e pedir sua desistência.

CARD OU INTERNA CINZA
Título: Quem luta contra corrupção e defende a democracia não desiste nunca.
Subtexto: \<nome-do-candidato\> não respondeu tudo o que pede a campanha. Vamos ajudá-la/o a se lembrar.

CARD OU INTERNA VERDE
Título: Quem é contra corrupção e defende a democracia merece nosso apoio!
Subtexto: Essa é uma candidatura comprometida. Saiba mais sobre ela aqui.

- [ ] Ativação da ação de compartilhar (mesmo componente) no botão de pressão (mantendo intactas a jornada e regras atualmente desenvolvidas)
COMO PRESSÃO É APENAS PARA CARDS CINZAS, SERÁ UM TIPO DE TEXTO SÓ:
Título: Ajude a luta contra corrupção e a defesa da democracia.
Subtexto: \<nome-do-candidato\> ainda não respondeu tudo o que pede a campanha. Cobre agora.

Imagem padrão para o meta: https://drive.google.com/file/d/1TMhrPxXqJV9owM3nYDZm0EZ36YVTRKVp/view?usp=sharing

Os textos foram formulados considerando formato face (imagem abaixo), 40 caracteres de um TITULO e 40 caracteres de um SUBTITULO

![captura de tela 2018-08-29 as 18 53 39](https://user-images.githubusercontent.com/6249788/44817786-e0e36380-abbc-11e8-8649-916bf89acb91.png)

**Comment by ricardopoppi** [comment]
@luizapeixe pra implementação da interna precisamos conceber:
(i) repercussão da ação dos botões de interação na interna dos candidatos. Será o mesmo toast que aparece quando o usuario interage com o card?
(ii) o botão compartilhar aparece na interna agora em todas as situações, peço autalizar todos os wires com o botão de compartilhar

@parrahenri precisamos conceber os textos default dos compartilhamentos das internas, nas seguintes condições:
(i) candidato com NÃO em novas medidas: "O candidato \<nome-do-candidato\> @do-candidato ainda não se comprometeu com as novas medidas, pressione ele etc etc
(ii) candidato com SIM em novas medidas: "O candidato \<nome-do-candidato\> @do-candidato se comprometeu com as novas medidas! Selecione ele e saiba mais sobre seu perfil etc etc
(iii) candidato com NÃO em passado limpo: o que acontece? exibe botão de compartilhar? se exibir, seria um texto tipo "O candidato x não tem passado limpo, corra dele! etc etc"?

@davidCarlos precisamos pesuquisar sobre o compo

**Comment by parrahenri** [comment]
@ricardopoppi agora que entendi a funcionalidade. automaticamente vai gerar textos diferentes dependendo da situação de cada candidato é isso?

**Comment by parrahenri** [comment]
Atualizamos pra esseS:

(i) sim passado limpo, algum não em demo ou em medidas: pressão pública mandando o cara se comprometer com demo ou medias, tudo no mesmo texto. um texto genérico ex: o fulano não se comprometeu ainda com democracia ou novas medidas. se comprometa! e etc etc (e o botão share faz share negativo)
(ii) sim passado limpo, sim demo, sim medidas: não tem pressão (mas o botão share faz um share positivo)
(iii) não passado limpo (independente das outras variaveis): pressão mandando a galera não votar nele (e o botão share faz ṕressão negativa)

**Comment by parrahenri** [comment]
Msg precisa ser formato face (imagem), 40 caracteres de um TITULO e 40 caracteres de um SUBTITULO

![captura de tela 2018-08-25 as 19 55 06](https://user-images.githubusercontent.com/4418975/44623322-33610f00-a8a1-11e8-8051-5081dda2f01b.png)

já demandei cliente e pedi até amanhã

**Comment by luizapeixe** [comment]
(i) repercussão dos botões: devemos manter as soluções das outras areas, ou seja, no clique o botão "pisca" (assim como na tela de lista de cards) e um toast sobe informando sobre a ação do clique. E os botões que eventualmente derivam da ação do clique poderiam aparecer tipo num fade-in suave (por exemplo, num card verde, clicando em "selecionar" aparecem os botões "favoritar" e "apoiar")

(ii) atualizar telas: Atualizei as internas dos candidates adicionar o recurso de compartilhar em todos (só pra confirmar: os share estarão presentes só nas internas mesmo né? e não nos cards nas páginas de lista, certo?)

**Comment by luizapeixe** [comment]
@ricardopoppi se nas páginas de lista os cards também apresentarem o recurso de compartilhar nas abas Todes e Selecionados, então temos que repensar a posição do botão de share em todos os cards, porque hoje o mesmo espaço está sendo usado de diferentes maneiras nas 3 abas: 1. Todes = fechar / 2. Selecionades = Remover marcação / 3. Favorites = Share

uma solução prática seria manter os recursos de Fechar e Remover marcação onde estão e pensar um novo lugar pro recurso de Share. Sugiro algo assim:

![captura de tela 2018-08-27 as 15 58 52](https://user-images.githubusercontent.com/6249788/44679728-20218100-aa12-11e8-9e5a-4a3e021f3578.png)

**Comment by luizapeixe** [comment]
corrigindo, melhor assim:

![captura de tela 2018-08-27 as 17 44 17](https://user-images.githubusercontent.com/6249788/44685031-dc824380-aa20-11e8-9176-96b1176a9b01.png)

pq o tom azul sobreposto ao filtro vermelho deixa um vibração incômoda no olho

**Comment by parrahenri** [comment]
Gostei mais dessa última

**Comment by ricardopoppi** [comment]
@luizapeixe massa! vamos da ultima então. assim que vc atualizar os wireframes me avisa por aqui? vlw!

**Comment by luizapeixe** [comment]
Ok! alterei e atualizei no invision as telas da fase 3

https://projects.invisionapp.com/d/main#/projects/prototypes/14558908

**Comment by luizapeixe** [comment]
aqui vai o link para a imagem fixa de compartilhamento no facebook: https://drive.google.com/file/d/1TMhrPxXqJV9owM3nYDZm0EZ36YVTRKVp/view?usp=sharing

**Comment by davidCarlos** [comment]
A implementação da interna está em dev. Como juntar o compartilhamento com a interna gerou uma tarefa muito grande, iremos tratar ambas de maneira separada.
