### ISSUE TITLE
Conceber como apresentar alguns opt-ins ao usuário

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#116]
Fomos provocados a inserir, no ambiente do aplicativo, esses dois opt-ins e um disclaimer. @luizapeixe qual seria a melhor maneira de fazer isso? se colocarmos no cadastro, poucos usuários verão e marcarão já que a tendencia é entrarem via login face. (cc @parrahenri )

() Eu aceito receber notícias sobre o combate à corrupção.
() Concordo e aceito os termos de privacidade da campanha: Unidos contra a Corrupção.
Ao se cadastrar, você ajudará a pressionar os candidatos a se comprometer com o maior pacote de combate à corrupção do mundo

**Comment by luizapeixe** [comment]
Chegamos a comentar essas problemática em outro momento... Um solução que foi colocada foi incorporar esses opt-ins no splash de perfil atualizado, apostando que a missão "PERFIL CAMPEÃO" será a primeira missão a ser executada pelos usuários mais ligados no app e que invariavelmente fará ele editar seu próprio perfil. 

Splash aqui: https://invis.io/QNNDJ9PHR3J 

Será que essa solução ainda se sustenta?

**Comment by parrahenri** [comment]
Acho que tá massa assim!

**Comment by ricardopoppi** [comment]
Mesmo a gente não yendo mais a missão perfil campeão, acho que essa opção
se sustenta sim. Creio que é o lugar mais adequado

> --

Ricardo Poppi
Whatsapp/Telegram: +55 61 9 9531 9531
Skype: rpoppi77
www.instituto.cidadedemocratica.org.br <http://www.cidadedemocratica.org.br>

**Comment by ricardopoppi** [comment]
já abri a issue de implementação dele, a #123 - fechando essa aqui
