### ISSUE TITLE
Solicitar geolocalização do usuário no momento do cadastro ou qdo clicar em "candidates"

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#12]
Solicitar essa informação e gravar em campo específico no perfil. @danielhmarinho @davidCarlos podem comentar qual a abordagem utilizada no SOMOS pra gente poder aproveitar no EJ

Regra de negócio sugerida:
(1) Acrescentamos um campo para CEP no profile do usuário (não no cadastro)
(2) Solicitamos as informações GEO no registro. Se o usuário não informar ou der erro, o campo cep fica em branco. Se der certo o campo cep é preenchido e as infos de cidade/estado/país são preenchidas automaticamente tb
(3) Quando o usuário vai editar o perfil e o campo CEP não está preenchido solicitamos geo novamente, valendo a mesma regra do ítem (2) acima
(4) Quando o usúario acessa a home do app na v3 (candidates), verificamos se ele tem geo, senão solicitamos novamente

**Comment by danielhmarinho** [comment]
@ricardopoppi eu não acho que a abordagem do CEP seja a mais correta. A geolocalização retorna pra gente uma cidade e o estado. Se a gente ainda tiver que fazer mais consultas a partir disso pra gerar um cep vai ser muito trabalhoso e nbão acho que traga resultados pra gente na hora da filtragem. No somos a gente recuperava cidade e estado e a função de filtro funcionava numa boa. Minha ideia era recuperar a cidade e estado pela api do google e a partir dai setar isso no profile dele. Se ele quiser atualizar essa informação basta mudar a uf  e cidade la no perfil. Também acredito que a informação mais relevante no momento seja a uf, pq vamos filtrar os candidatos apenas nesse nível, não?

**Comment by danielhmarinho** [comment]
@ricardopoppi Sobre o momento da solicitação acho melhor fazer no momento que a pessoa entra no candidates mesmo, para nao ficar sobreposta a solicitação de notificações por push.

**Comment by ricardopoppi** [comment]
Blz @danielhmarinho de acordo com a abordagem de um eliminar o CEP, realmente o que precisamos é cidade e UF. Na construção da issue achei que o CEP era necessário para isso. Manda bala como vc propôs.

Sobre o momento, creio que é qdo entra no candidates. No caso, qdo colocarmos em prod a funcionalidade de candidates vamos setar a home pra ela aparecer primeiro ao usuário. Mas por definição, deve ser sempre que o usuário acessa o feed TODOS (que no caso vai ser a home) e não tem essa informação setada no perfil ainda. É importante tb exibir uma modal simples de fallback caso a API do Google não retorno ou dê algum outro erro. Os estilos desse modal podem ser os mesmos usados hj na tela de edição de perfil do usuário. Que tal?

**Comment by danielhmarinho** [comment]
@ricardopoppi podemos apresentar sim uma modal caso a localização retornada pelo google de algum problema. Acho que assim alinhamos bem o escopo dessa issue!
