### ISSUE TITLE
Implementar o filtro nos feeds TODOS e SELECIONADES

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#122]
Implementar o filtro

-> aba TODOS / fechada: https://invis.io/SPN6XE5NFGC
-> aba SELECIONADOS/ aberta: https://invis.io/PTN7U215BQW

Regra do campo "visualizando":

0 todos
1 não responderam
2 não se comprometeram
3 se comprometeram

**Comment by danielhmarinho** [comment]
@ricardopoppi esse filtro representa a mesma ideia das cores do cards? Estamos um pouco confusos quanto a implementação do mesmo. Esse não responderam seria que não responderam a nenhuma das perguntas que definem o card?

**Comment by ricardopoppi** [comment]
Sim, é pra filtrar de acordo com as respostas. Vou explicar melhor aqui:

condição: TODOS - REGRA: qq resposta
condição: NÃO RESPONDERAM - REGRA: opção novas medidas = "SEM RESPOSTA"
condição: NÃO SE COMPROMETERAM - REGRA: opção novas medidas = "NÃO"
condição: SE COMPROMETERAM - REGRA: opção novas medidas = "SIM"
