### ISSUE TITLE
Implementar regra de cores nos cards

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#125]
Cards com qq ítem como "SEM RESPOSTA" são exibidos na cor CINZA
Cards com qq ítem como "NÂO" são exibidos na cor VERMELHA
Cards com os 3 itens como "SIM" (tem que ser os 3) são exibidos na cor VERDE

**Comment by luizapeixe** [comment]
prontinho! telas atualizadas com cards sob a nova definição de cores

Lista / aba Todos: https://invis.io/SPN6XE5NFGC
Lista / aba Selecionados: https://invis.io/PTN7U215BQW
Lista / aba Favoritados: https://invis.io/ZUN7U15JD4C
Lista / versão desktop: https://invis.io/G5NGU36KXAB
Interna / pessoa verde não-selecionada: https://invis.io/G5NDI95XYNP
interna / pessoa verde selecionada: https://invis.io/N2NDIA7SQXF
interna / pessoa cinza selecionada e favoritada: https://invis.io/MFNDIAQ6G5T
interna / pessoa cinza selecionada e não-favoritada: https://invis.io/YANDIF0ZDW5
interna / pessoa vermelha não-selecionada: https://invis.io/MQNDJR275ED

**Comment by ricardopoppi** [comment]
@davidCarlos com esse update da @luizapeixe fica tudo pronto pra essa
