### ISSUE TITLE
criar imagem default pra candidatos

### ISSUE THREAD

**Issue by parrahenri** [unidoscontraacorrupcao/ej-server#126]
@luizapeixe TSE vai atualizar lentamente a base de fotos então precisamos criar uma foto default "foto ainda não foi disponibilizada pelo TSE".

Assim, a gente já sobe como default e depois vai substituindo. Abaixo link pra ver as fotos e pegar o padrão (dimensões etc)

---
As fotos, por exemplo, dos 11 candidatos que mandei ontem estão no
Divulgacand de 2010 ou 2014. Exemplo:

http://divulgacandcontas.tse.jus.br/divulga/#/candidato/2014/680/DF/70000001075

http://divulgacandcontas.tse.jus.br/divulga/#/candidato/2010/14417/MA/100000000206

O formato em 2018 é o mesmo. Claro que cada candidato atualiza a foto
de eleição para eleição

**Comment by luizapeixe** [comment]
que tal algo assim:

![captura de tela 2018-08-10 as 13 03 18](https://user-images.githubusercontent.com/6249788/43968531-d03b746a-9c9d-11e8-8105-ce98a772660e.png)

![captura de tela 2018-08-10 as 13 04 21](https://user-images.githubusercontent.com/6249788/43968580-eee37020-9c9d-11e8-83a4-601ad2d557fc.png)

![captura de tela 2018-08-10 as 13 04 48](https://user-images.githubusercontent.com/6249788/43968593-fdc7da22-9c9d-11e8-864e-2bd2b1f5c551.png)

?

**Comment by parrahenri** [comment]
boa!

**Comment by luizapeixe** [comment]
Ok! Acabei de subir as imagens no nosso drive. Se chamam card_avatar-default-(cinza; vermelho e verde)

**Comment by ricardopoppi** [comment]
Maravilha, já registrei elas na issue da importação #99
