### ISSUE TITLE
Feedbacks do cliente dia 10/08

### ISSUE THREAD

**Issue by luizapeixe** [unidoscontraacorrupcao/ej-server#127]
- [x] os quadros de missões ficam encolhidos no meio da tela com um monte de espaço livre dos dois lados // DEMANDA: criar tela desktop de lista de missões

- [x] a imagem do usuário (quando não tem foto) fica uma coisa cinza meio manchada, sem resolução parece // DEMANDA: retirar filtro de noise das imagens todas

- [x] a fonte cinza é ruim de ler (no fundo branco) // DEMANDA: rever/alterar layouts

- [x] esse logo do x com o cinza atrás fica muito ruim (poderia, por exemplo, colocar só o x sobre o fundo branco mesmo) // DEMANDA: alterar imagem do avatar para a versão .pgn com fundo branco (talvez essa sirva -> "https://drive.google.com/file/d/1-9PoFjWU-xHQVvZQf7zc_gZDL2VPbaM3/view?usp=sharing")

**Comment by luizapeixe** [comment]
SOBRE O ITEM 2. a imagem do usuário (quando não tem foto) fica uma coisa cinza meio manchada, sem resolução parece

retirei o noise dos imagens e atualizei os assets no drive. as imagens são as mesmas, porém versionadas

avatar default no menu: https://drive.google.com/file/d/1zEZGCWz3sKOqe0_Yq80rLEJc2JeLvlhv/view?usp=sharing

avatar default no thumb: https://drive.google.com/file/d/15AsJOJB712U-AJU2aFRuMkXpmsuLmJTk/view?usp=sharing

avatar default no perfil: https://drive.google.com/file/d/163GhhPIpUB6SveKtH3mxlkrsk3_T6YYN/view?usp=sharing

**Comment by ricardopoppi** [comment]
Boa @luizapeixe ! Assignando essa issue pro milestone da v4, após a entrega dos candidatos (@parrahenri )

**Comment by luizapeixe** [comment]
SOBRE O ITEM 1. os quadros de missões ficam encolhidos no meio da tela com um monte de espaço livre dos dois lados

Segue abaixo uma proposta de tela para a lista de missões versão desktop:

![desktop lista de missoes](https://user-images.githubusercontent.com/6249788/44051117-5acb65cc-9f0f-11e8-9b67-f9fa3cad5e67.png)

Obs.: também retirei o filtro de noise das capas das missões e versionei no drive, mas não sei se elas se atualizam sozinhas pro site ou se precisamos substituir os assets :/

**Comment by parrahenri** [comment]
Eu curti!

**Comment by luizapeixe** [comment]
SOBRE O ITEM 3: fontes cinzas difíceis de ler

fiquei pensando sobre essa questão... Ela é mais complexa do que pode parecer por 2 motivos principais:

1. o tom de cinza
seria bastante simples apenas escurecer o tom de cinza de todos os textos q o cliente achou problemáticos, entretanto o cinza que estamos usando é o exato tom de cinza da identidade visual aprovada pro Unidos Contra a Corrupção e alterar esse tom seria desunificar a identidade cromática do Unidos e Besouro.

2. hierarquia estratégica dos conteúdos 
todos os textos q estão em cinza têm sempre uma importância secundária no contexto onde estão apresentados, ou seja, estão em cinza justamente pq não querem chamar tanta atenção porém necessitam estar presentes onde estão. 

Outro fator condicionante da relevância dessa demanda é que a saturação e brilho dos monitores/telas costuma variar bastante de usuário para usuário, então a dificuldade encontrada pelo cliente pode não ser problema para outros users. 

Então fica o questionamento: vocês concordam com a necessidade de escurecer todos os textos em cinza ou devemos argumentar com o cliente em favor de manter o cinza como está?

**Comment by parrahenri** [comment]
@luizapeixe sobre item 3: acho seus argumentos bons. então pra esse vamos manter como está.

**Comment by ricardopoppi** [comment]
@luizapeixe ainda que algumas coisas aqui já foram implementadas (img avatar default por exemplo) as outras coisas dessa issue estão no meu radar pra retomar quando terminarmos de entregar tudo do módulo de candidatos. Isso provavelmente vai acontecer na próxima semana. 

Enquanto isso te peço pra registrar numa outra issue específica de diagnóstico, os problemas de "não correspondencia" com os wireframes e eventuais problemas de ux que vc perceber testando diretamente em dev:  https://dev.besouro.ejplatform.org

Um exemplo de uma coisa que percebi hj e já abri issue é a ausencia de margem entre a borda e títulos dos colapsáveis (issue #228). Mas certamente outras existem. Com esse seu trabalho teremos bons elementos para a fase 4, dos ajustes. (cc @parrahenri)

**Comment by ricardopoppi** [comment]
fechando essa pois issues especificas para os pontos 1 e 2 foram abertas. o ponto 3 decidimos não fazer e o ponto 4 já tinha sido feito.
