### ISSUE TITLE
Conceber uma animação para o card quando ele é selecionado ou pressionado

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#129]
Quando o card do candidato é selecionado ou pressionado, mesmo com o toast, pode parecer imperceptível ao usuário.

Importante concebermos uma animação para o caso do "selecionado" e uma diferente para o caso do "pressionado"

**Comment by luizapeixe** [comment]
Uma dúvida: quando o user seleciona um card, esse card continua na lista de TODOS?

No caso do card selecionado NAO ficar na lista de todos, tenho sugestões
- selecionando: botão pisca, como se tivesse sido apertado / daí card desliza para a direita, como se estivesse mudando de aba
- pressionando: botão pisca, como se tivesse sido apertado / daí card desliza pra cima, como se tivesse sendo "enviado" pra algum lugar
- fechando: botão pisca, como se tivesse sido apertado / daí card some num fade-out

**Comment by ricardopoppi** [comment]
Qdo ele é selecionado, ele some tb. Tanto pressionado quanto selecionado somem.

Eu gostei das propostas. O que acha @parrahenri?

**Comment by ricardopoppi** [comment]
Boa! fechando essa, abri a #131  pra implementação
