### ISSUE TITLE
Criar troféus e capas para as 3 novas missões

### ISSUE THREAD

**Issue by luizapeixe** [unidoscontraacorrupcao/ej-server#130]
1. Cadastre um candidato 
(pessoas precisam conseguir contato com candidatos para que eles se cadastrem no site)

2. Grave um Vídeo
(pessoas precisam gravar vídeo falando sobre pq se uniram contra a corrupção e dando um recado sobre o tema)

3. Cole Adesivos
(pessoas precisam imprimir e colar os adesivos da campanha no seu carro, portão da casa etc)

**Comment by luizapeixe** [comment]
Que tal esses troféus?
esquerda à conquistar // direita: conquistados

![captura de tela 2018-08-15 as 15 01 05](https://user-images.githubusercontent.com/6249788/44164340-24f24680-a09c-11e8-862d-50baf97da5c5.png)

**Comment by luizapeixe** [comment]
que tal essas capas?
![captura de tela 2018-08-15 as 17 15 57](https://user-images.githubusercontent.com/6249788/44170828-eade7000-a0ae-11e8-9b9e-efbddf511efd.png)

**Comment by luizapeixe** [comment]
segue outra opção pro Cadastre um candidato:

![captura de tela 2018-08-22 as 10 54 19](https://user-images.githubusercontent.com/6249788/44467636-c4ae5800-a5f9-11e8-8b16-e30c68610667.png)

**Comment by ricardopoppi** [comment]
como as missões já foram criadas, fechando essa. as imagens ficaram massa demais @luizapeixe! <3
