### ISSUE TITLE
Homologar 3.1

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#132]
https://dev.besouro.ejplatform.org/

**Comment by parrahenri** [comment]
Não rolou acesso @ricardopoppi 
![captura de tela 2018-08-16 as 14 40 54](https://user-images.githubusercontent.com/4418975/44224927-69e0b080-a162-11e8-99ed-e6fa128ec894.png)

**Comment by ricardopoppi** [comment]
@parrahenri tudo indica que foi momentaneo. pra homologar legal, crie um novo cadastro

**Comment by ricardopoppi** [comment]
primeira rodada de homologação feita, issues abertas

**Comment by ricardopoppi** [comment]
feito
