### ISSUE TITLE
Ajustar conteúdo e estilo caixa alta do texto das notificações SELECIONADO e PRESSIONADO

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#133]
Como o texto da notificação de seleção e pressão é mais longo, talvez o estilo esteja inadequado (cc @luizapeixe). Ou o texto tenha que ser encurtado (cc @parrahenri)

Vejam print:
![captura de tela de 2018-08-18 13-55-56](https://user-images.githubusercontent.com/1162183/44301538-15b70700-a2ef-11e8-8991-d0c203d556da.png)

**Comment by parrahenri** [comment]
Proposta alternativa para testar @ricardopoppi 

1. Você pressionou NOME para que ele se comprometa contra a corrupção!
2. Você selecionou NOME. Conheça suas ideias em:

**Comment by danielhmarinho** [comment]
@ricardopoppi ja fiz a adequações ao card, no próximo deploy já estará corrigido, mas vou seguir acompanhando caso façam a alteração da estrutura do card

**Comment by luizapeixe** [comment]
nos layouts do invision as notificações já estavam em caixa baixa, só com termos em destaque com caixa alta. Vejam: https://invis.io/YVNM1MXUA8H

**Comment by ricardopoppi** [comment]
Obrigado @luizapeixe! Como os conteúdos mudaram, acho que isso acabou confundindo o fluxo de desenvolvimento.

@danielhmarinho vamos ajustar isso mantendo apenas o nome do candidate em caixa alta:
Você pressionou NOME-DO-CANDIDATE para que ele se comprometa contra a corrupção!
Você selecionou NOME-DO-CANDIDATE. Conheça suas ideias em: \<site-do-candidate\>
