### ISSUE TITLE
Tamanho do card do candidate não permite que o nome e botões apareçam ao mesmo tempo

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#134]
Observe que quando o nome do candidate aparece, os botões estão cortados. Qdo os botões aparecem por inteiro, não se vê mais o nome do candidate. O filtro colapsado acaba atrapalhando essa interação também.

Nome aparecendo e botões cortados:

![captura de tela de 2018-08-18 13-56-13](https://user-images.githubusercontent.com/1162183/44301562-6e869f80-a2ef-11e8-89a0-a66e587a9305.png)

Botões aparecendo e nome escondido:

![captura de tela de 2018-08-18 13-56-18](https://user-images.githubusercontent.com/1162183/44301563-77777100-a2ef-11e8-9c31-90dcd50e2be9.png)

**Comment by parrahenri** [comment]
@luizapeixe e se diminuirmos a imagem/ foto?

**Comment by luizapeixe** [comment]
Acho que isso pode variar de celular pra celular... mas diminuir a altura da foto é uma solução sim! Assim como diminuir o espaço entre os elementos. creio que diminuindo 40 pixel entre o topo card e os botões de selecionar/pressionar/(...) já resolvemos isso. Vejam:

![captura de tela 2018-08-20 as 10 52 09](https://user-images.githubusercontent.com/6249788/44344474-28544c00-a467-11e8-9fc8-01735927c543.png)

Acham q eu já aplico em todos os layouts?

**Comment by ricardopoppi** [comment]
eu gostei. acho que esse respiro de 40px já faz uma boa diferença. vamos encaminhar essa alteração @parrahenri?

**Comment by parrahenri** [comment]
sim!

**Comment by ricardopoppi** [comment]
@luizapeixe pode atualizar os wireframes e qdo fizer, fecha essa issue

**Comment by luizapeixe** [comment]
ok! telas de lista de card atualizadas no [mobile](https://invis.io/SPN6XE5NFGC) e [desktop](https://drive.google.com/file/d/1pJkevlX74zN0dFeNetWmJ9ZikZL_OOaX/view?usp=sharing). 

Ainda sobre otimizar espaço na rolagem, queria sugerir uma adaptação no estilo da aba de filtro de resultados. espero que não seja complexo do ponto de vista técnica :

Esquerda sem click   //   direito no clique
![captura de tela 2018-08-20 as 15 53 36](https://user-images.githubusercontent.com/6249788/44360449-3fa82f00-a491-11e8-9c6b-ccbd3afc1ed4.png)

O que acham?

**Comment by ricardopoppi** [comment]
Gostei @luizapeixe! Vou registrar isso e colocar como aprimoramento do filtro na 3.2. Pode atualizar os wireframes que estou fechando essa issue
