### ISSUE TITLE
Criar título para os 5 campos colapsáveis

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#142]

**Comment by parrahenri** [comment]
@ricardopoppi são 5. Infelizmente pelas características do cliente, quase certeza que haverá mudanças na nomenclatura. Mas validei isso agora:

1. Nome completo
(virá da BD TSE)
2. Ocupação Profissional
(virá da BD TSE)
3. Aderiu totalmente às Novas Medidas?
(texto de máx 500 caracteres que virá do survey)
4. Total de bens e patrimônio
(texto de máx 500 caracteres que virá do reinaldo)
5. Total de processos a que responde
(texto de máx 500 caracteres que virá do reinaldo)

**Comment by parrahenri** [comment]
Editei o texto pq 2 daqueles 3 não serão colapsáveis

**Comment by ricardopoppi** [comment]
@parrahenri se não serão colapsáveis serão o que esses dois? e qual dois?

**Comment by parrahenri** [comment]
Os 2 itens que estavam na descrição:


Já sofri condenação judicial em primeira instância por algum dos atos acima descritos.
--
Também nunca sofri condenação judicial em primeira instância por nenhum dos atos acima descritos

**Comment by parrahenri** [comment]
podemos ignorá-los. São itens de uma coluna da planilha do surveymonkey.

**Comment by ricardopoppi** [comment]
ah maravilha, já considerei a fonte atualizada do seu comment então: https://github.com/unidoscontraacorrupcao/ej-server/issues/142#issuecomment-414397633

**Comment by ricardopoppi** [comment]
vou fechar essa issue, novos itens ou mudanças a gente faz em novas issues
