### ISSUE TITLE
Tornar o feed TODOS (candidates) a página inicial do app

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#143]
Hoje a página inicial é missões. Deve ser alterada pro feed TODOS dos candidatos

**Comment by danielhmarinho** [comment]
@ricardopoppi essa issue vai tomar um tempo um pouco maior do que prevemos. Várias coisas estão atreladas a localização do usuário, candidatos que ele selecionou ou não.

**Comment by ricardopoppi** [comment]
@danielhmarinho ok, podemos esconder o filtro para os deslogados para evitar essa refatoração. e o geo pode ser pedido após o login que tal?

**Comment by danielhmarinho** [comment]
@ricardopoppi a geo só acontece mesmo depois do login, o problema maior era o filtro mesmo. Se podemos esconder simplifica bastante o trabalho

**Comment by ricardopoppi** [comment]
então vamos nessa @danielhmarinho!
