### ISSUE TITLE
Filtro automático geo não repercute no filtro do topo

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#145]
Para replicar:
1) Cadastre um usuário novo
2) Observe que os cards de candidatos estão filtrados pela sua UF
3) Abra o filtro no topo
4) Note que aparece como UF - Todas.

O ideal seria o filtro do topo repercutir essa condição de filtragem por geo. Se o usuário altera essa condição do filtro, não é necessário repercutir nas próximas seções, que podem vir com o filtro automático setado novamente

**Comment by danielhmarinho** [comment]
@ricardopoppi  "não é necessário repercutir nas próximas seções, que podem vir com o filtro automático setado novamente" o que isso quer dizer? Podemos deixar o padrão ser o estado ele se ele tiver e se não tiver vir o todos?
