### ISSUE TITLE
Barra lateral sem rolagem pra baixo

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#15]
A barra lateral, quando aberta, não está rolando para baixo. Observe que o "DIVULGUE" está cortado

![photo_2018-06-28_19-38-00](https://user-images.githubusercontent.com/1162183/42063994-cb15aadc-7b0a-11e8-8967-3b9cd2323cdc.jpg)

**Comment by davidCarlos** [comment]
A implementação da barra lateral foi feita pelo @arkye. Assinando pra ele a issue.
