### ISSUE TITLE
Atualizar o texto de abertura da v3.1

### ISSUE THREAD

**Issue by parrahenri** [unidoscontraacorrupcao/ej-server#154]
Descubra quais candidatas/os atendem a três critérios: 1. Passado Limpo; 2. Compromisso com Democracia; e 3. Adesão às Novas Medidas contra a Corrupção.

- VERDE é SIM nos três critérios
- VERMELHO é NÃO em algum critério.
- CINZA: ainda não respondeu

Você pode selecionar aqueles que te interessarem Também pode pressionar para que candidatas/os se comprometam! Veja mais detalhes em AJUDA, no menu.

**Comment by parrahenri** [comment]
@ricardopoppi veja

**Comment by ricardopoppi** [comment]
Favoritar é update, então por hora vamos tirar do texto

**Comment by parrahenri** [comment]
feito
