### ISSUE TITLE
Conceber uma solução para exibir as fotos nos cards de candidatos

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#157]
As fotos do TSE tem altura maior que largura. Portanto não se encaixam no formato atual das imgs nos cards.

Precisamos bolar uma solução de como "encaixar" as fotos nesse formato, nos cards

**Comment by luizapeixe** [comment]
Essa questão é um tanto delicada de se solucionar sem que haja necessidade de repensar toda a estrutura do card. Pensando em soluções práticas, vejo duas alternativas nessa situação:

1. justificar a imagem dos candidates pela largura do card (que no mobile deve ser justificada fullwide e no desktop deve ter largura de 320px - hoje está com 500px, por isso na implementação o card parece mais achatado que nos layouts do invision) . ex:
![captura de tela 2018-08-24 as 12 57 22](https://user-images.githubusercontent.com/6249788/44594692-5609ff80-a79d-11e8-8738-9e9c11849cd2.png)

2. aplicar a imagem dos candidates centralizada e justificada pela altura da imagem (220px). ex: 
![captura de tela 2018-08-24 as 12 55 30](https://user-images.githubusercontent.com/6249788/44594603-088d9280-a79d-11e8-8d1e-00ad933dddd4.png)

Na solução 1. acabamos por perder qualidade da imagem e o rosto do candidate tende a ficar um tanto estourado no card. Na solução 2. a foto do candidate fica mais amigável entretanto, nas fotos que não têm fundo branco (como no exemplo acima), as arestas ficarão evidenciadas. Muitas das fotos possuem fundo branco porém algumas infelizmente apresentam um fundo por trás a pessoa. No caso das fotos com fundo branco o resultado visual será assim:
![captura de tela 2018-08-24 as 13 10 31](https://user-images.githubusercontent.com/6249788/44595363-1d6b2580-a79f-11e8-9a2b-f6495f80a68d.png)


Eu prefiro a solução 2. Acham que seguimos assim ou é o caso de realmente repensar a estrutura do card em função das fotos dos candidates?

**Comment by ricardopoppi** [comment]
Não podemos repensar a estrutura do card. É entre 1 e 2 mesmo. Eu tb fico com a 2.

O que acham @parrahenri @davidCarlos @danielhmarinho?

**Comment by parrahenri** [comment]
2!

**Comment by davidCarlos** [comment]
2

**Comment by ricardopoppi** [comment]
fechando essa então pois abri uma específica com as instruções (issue #160)
