### ISSUE TITLE
Propor layout desktop com logo do Unidos Contra a Corrupção presente no header

### ISSUE THREAD

**Issue by luizapeixe** [unidoscontraacorrupcao/ej-server#158]

**Comment by luizapeixe** [comment]
opção 1:
![desktop_lista-candidatesv2](https://user-images.githubusercontent.com/6249788/44685706-7bf40600-aa22-11e8-82fe-b25c0e8486f6.png)

opção 2:
![desktop_lista-candidatesv3](https://user-images.githubusercontent.com/6249788/44685739-8e6e3f80-aa22-11e8-8d3f-4a0e980d51fa.png)

**Comment by parrahenri** [comment]
Gostei mais da 2

**Comment by ricardopoppi** [comment]
fechando essa, abri issue #278 para implementação, provisoriamente em backlog futuro
