### ISSUE TITLE
Criar imagem de capa para ilustrar as 5 missões iniciais

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#16]
As atuais imagens de capa foram escolhidas no susto. Como as missões iniciais tem um papel importante no uso do app, seria legal a gente dar um talento na criação delas. Peço à @luizapeixe conceber e ao @parrahenri orientar a criação de imagens de capa para as 5 missões iniciais:

(i) Missão completar o perfil.
(ii) Missão Apoiar Campanha Unidos Contra a Corrupção
(iii) Missão Compartilhar pedido de assinatura no Grupo da Família ou Grupo de amigos
(iv) Missão Compartilhar Pedido de assinatura no Facebook
(v) Troféu atribuído a partir da obtenção de outros troféus anteriores
(vi) Missão Criar grupo de Whatsapp para mobilizar pela campanha

Para refrescar a memoria: detalhes sobre as missões estão nesse comment: https://github.com/unidoscontraacorrupcao/ej-server/issues/6#issue-333447147

**Comment by parrahenri** [comment]
@luizapeixe a primeira tem o apelo de perfil campeão, perfil verificado, sabe? talvez seja o bench pra olharmos perfis verificados de insta, twitter etc.

3 e 4 vale fazer uma referência visual ao Whatsapp e ao Face mesmo, deixando bem evidente. 
 
Ainda não tive ideias pro 2, 5 e 6. Se tiver ideias, posta e ajuda a chegar nas decisões! :)

**Comment by luizapeixe** [comment]
que tal essas propostas? Achei interessante não manter um padrão específico na criação das capas justamente para deixar em aberto o estilo delas a não limitar as possibilidades de criação para a equipe de TI e/ou users num momento futuro

(i) Missão completar o perfil.
![capa_missao1](https://user-images.githubusercontent.com/6249788/42182769-c0f8cc24-7e15-11e8-83c4-166f0f8def01.png)

(ii) Missão Apoiar Campanha Unidos Contra a Corrupção
![capa_missao2](https://user-images.githubusercontent.com/6249788/42182775-c544ee48-7e15-11e8-8dd5-ee58e668c54b.png)

(iii) Missão Compartilhar pedido de assinatura no Grupo da Família ou Grupo de amigos
![capa_missao3](https://user-images.githubusercontent.com/6249788/42182783-ca8995de-7e15-11e8-960f-f091430b7ea4.png)

(iv) Missão Compartilhar Pedido de assinatura no Facebook
![capa_missao4](https://user-images.githubusercontent.com/6249788/42182788-cfdee728-7e15-11e8-8f85-0d9713d1d0bd.png)

(v) Troféu atribuído a partir da obtenção de outros troféus anteriores
![capa_missao5](https://user-images.githubusercontent.com/6249788/42182802-d4666906-7e15-11e8-992e-aac64dccc971.png)

(vi) Missão Criar grupo de Whatsapp para mobilizar pela campanha
![capa_missao6](https://user-images.githubusercontent.com/6249788/42182808-d7e11324-7e15-11e8-857e-48d18b378e75.png)
