### ISSUE TITLE
Propor solução para o "esmagamento" do filtro no mobile

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#161]
Quando o usuário tenta escrever no campo aberto do filtro  no mobile, o teclado e a navbar sobrepoe o filtro quase todo.

No print abaixo é possível ver isso. Em algum celulares nem o campo partido aparece.

Print:
![photo_2018-08-24_20-37-01](https://user-images.githubusercontent.com/1162183/44612275-76f24500-a7dd-11e8-9678-cf1fd0d057d6.jpg)

**Comment by luizapeixe** [comment]
Uuuuhn... Algumas sugestões pra tentar solucionar essa questão:

1. ocultar a navbar qnd subir o teclado
2. diminuir tipografia dos campos -> deixar o "TODAS" do mesmo tamanho de "Tipos de candidatura"
3. diminuir espaço de altura entre os campos do form -> se hoje tem 20px, deixar com 10px

![captura de tela 2018-08-27 as 12 47 29](https://user-images.githubusercontent.com/6249788/44669828-69b0a280-a9f7-11e8-9628-4c115d7bd2ec.png)

**Comment by ricardopoppi** [comment]
@davidCarlos @danielhmarinho o que acham dessa solução?

**Comment by danielhmarinho** [comment]
@ricardopoppi já tinhamos discutido alguma coisa nesse sentido. Acho que já ajuda demais, além de que pensamos em uma maneira de esconder a barra inferior quando o teclado é aberto.

**Comment by ricardopoppi** [comment]
issue #279 aberta para implementação
