### ISSUE TITLE
Filtro deve aparecer para usuários deslogados também

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#163]
Atualmente o filtro aparece apenas para usuários logados

**Comment by danielhmarinho** [comment]
@ricardopoppi aqui entra aquela conversa que tivemos sobre a arquitetura e e o esforço para resolver. A primeira vista não vai ser uma issue simples de ser resolvida. Basicamente vamos ter que construir filtros a parte só para essa funcionalidade

**Comment by ricardopoppi** [comment]
@danielhmarinho porque seria isso? para deslogado não precisaremos pegar tag geo. Só fazer o sort mesmo

**Comment by danielhmarinho** [comment]
@ricardopoppi os endpoints verificam os candidatos que o usuário já selecionou ou excluiu para que não mostremos mais os mesmos. Se não existe usuário no momento da filtragem então toda essa lógica não se aplica. Por esse raciocinio vamos ter que refazer os endpoints excluindo esse comportamento para quem esta deslogado.

**Comment by ricardopoppi** [comment]
@danielhmarinho ah entendi, é aquela questão dos conteúdos específicos que vem de acordo com a interação do usuário, coisa que não se aplicaria pros deslogados. Não acho que essa issue tem o valor necessário considerando ter que refazer os endpoints. Mas ela tem valor pra campanha. Se tivessemos algum workaround pra esse momento, mesmo que não ideal, seria a melhor opção. Acha que tem?

**Comment by ricardopoppi** [comment]
Ha um workaround possível: o filtros ser apenas exposto off-line e o clique no descolapsar disparar o splash de login
