### ISSUE TITLE
UF escolhida antes de resetar o filtro não repercute mais na interface

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#164]
Para replicar:
1) Escolha uma UF qualquer e filtre
2) Aperte no reset do filtro
3) Escolha novamente a mesma UF do ítem 1
4) Note que ela não repercutiu na interface

Se vc escolher uma outra UF e voltar pra anterior ela volta a repercutir na interface

**Comment by danielhmarinho** [comment]
@ricardopoppi  isso é um comportamento do próprio componente do polymer. Resolver isso seria um esforço grande. Devemos analisar se isso é realmente necessário

**Comment by ricardopoppi** [comment]
@danielhmarinho é um bug do componente então? acho que não compensa o valor que essa correção traria. Talvez valha a pena abrir uma issue no repo do componente que tal?

**Comment by danielhmarinho** [comment]
@ricardopoppi não é bem um bug. Até pensei em uma maneira de resolver mas preciso fazer testes. Caso não funcione ai vou recorrer ao repositório. Nesse caso o esforço é grande mas se eu conseguir resolver da maneira que pensei vai ser simples

**Comment by ricardopoppi** [comment]
@danielhmarinho ok, considera apenas a solução simples, senão deixemos pra fase 4, pois as outras issues agregam mais valor pra esse momento
