### ISSUE TITLE
Transformar campo do filtro "partido" em dropdown com os nomes dos partidos

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#165]
Lista para inserir:

MDB
PT
PSDB
PP
PDT
PTB
DEM
PR
PSB
PPS
PSC
PCdoB
PRB
PV
PSD
PRP
PSL
PMN
PHS
SD
PTC
DC
AVANTE
PODE
PSOL
PRTB
PROS
PATRI
PMB
PPL
REDE
NOVO
PSTU
PCB
PCO

**Comment by danielhmarinho** [comment]
@ricardopoppi apenas se atentar que como estamos restringindo o valor tem que estar exatamente igual a planilha. Observando aqui por exemplo PCdoB esta vindo Pc do B
