### ISSUE TITLE
Ativar os tooltips dos três itens de resposta no card de candidates

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#166]
Como é possível ver no wireframe, cada um dos três itens presentes no card (passado limpo, democracia e novas medidas) tem um tooltip "?" que o acompanha.

https://invis.io/SPN6XE5NFGC

Precisamos implementar

Textos:

Passado limpo:
Nosso critério de passado limpo é rígido. A referência são os crimes da Lei da Ficha Limpa, mas para nós eles nunca prescrevem. No caso de quem tentará reeleição, veremos quem responde a processo no STF.

Democracia:
O critério de compromisso com os princípios democráticos baseia-se na adesão ao Pacto pela Democracia – iniciativa da sociedade pela preservação e revigoramento da vida política e democrática do país.

Novas medidas:
No caso do combate à corrupção, a/o candidata/o terá de se comprometer a, se eleita/o, pôr nossas propostas em tramitação e atuar por sua aprovação. Ressalvas terão de ser identificadas e justificadas.

**Comment by parrahenri** [comment]
O critério de passado limpo para a campanha Unidos Contra a Corrupção é rigoroso, exigindo-se além do mínimo legal para todas as candidaturas. A referência são os crimes listados na Lei da Ficha Limpa, mas o limite temporal é descartado (isto é, consideram-se "passado limpo" os/as candidatos/as que nunca tiveram condenação por nenhum daqueles atos). No caso daquelas/es que concorrem à reeleição no Congresso Nacional, as organizações integrantes da coalizão que lidera a campanha1 verificarão ainda os processos a que essas/es parlamentares respondem no Supremo Tribunal Federal (STF).

**Comment by parrahenri** [comment]
O critério de comprometimento com os princípios democráticos é baseado no compromisso das/os candidatas/os com o [Pacto pela Democracia](https://www.pactopelademocracia.org.br/), iniciativa da sociedade civil brasileira voltada a defender a preservação e o revigoramento da vida política e democrática do país.

**Comment by parrahenri** [comment]
No caso das Novas Medidas contra a Corrupção, a/o candidata/o deverá se comprometer a, caso seja eleita/o, trabalhar já no início de seu mandato a colocar as propostas em tramitação e atuar por sua aprovação. Ressalvas às medidas serão aceitas desde que identificadas e devidamente justificadas.

**Comment by parrahenri** [comment]
@ricardopoppi peguei do release que a TI fez (que é documento aprovado e já enviado pra imprensa)

**Comment by ricardopoppi** [comment]
@parrahenri todos estão muito longos pra tooltip e o do passado limpo está escandalosamente longo rsrs. Vamos ter que resumir

**Comment by parrahenri** [comment]
demandei pro cliente resumir com até 200 caracteres e nos enviar até amanhã

**Comment by luizapeixe** [comment]
temos o tooltip desenhado nessa tela, no 4º card: https://invis.io/SPN6XE5NFGC

nesse exemplo, o tooltip apresenta 445 caracteres contando com espaços.

Só fiz uma pequena alteração no layout. Antes o (?) aparecia próxima as respostas SIM / NAO / SEM RESPOSTA e agora estão próximos às perguntas TEM PASSADO LIMPO / COMPROMETEU-SE e talz.

**Comment by parrahenri** [comment]
TEXTOS APROVADOS::

Nosso critério de passado limpo é rígido. A referência são os crimes da Lei da Ficha Limpa, mas para nós eles nunca prescrevem. No caso de quem tentará reeleição, veremos quem responde a processo no STF.

O critério de compromisso com os princípios democráticos baseia-se na adesão ao Pacto pela Democracia – iniciativa da sociedade pela preservação e revigoramento da vida política e democrática do país.


No caso do combate à corrupção, a/o candidata/o terá de se comprometer a, se eleita/o, pôr nossas propostas em tramitação e atuar por sua aprovação. Ressalvas terão de ser identificadas e justificadas.


c/c: @ricardopoppi
