### ISSUE TITLE
Atualizar conteudo do email enviado aos candidatos pressionados com o link correto

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#167]
Atualmente o email do candidato pressionado contem o link para a home da campanha. Como o pedido é pro candidato se posicionar sobre as medidas, é importante que o link seja direto para o formulário onde ele faz isso, pra não ficar tendo que procurar isso na home da campanha.

Link para entrar no conteúdo do email para o candidato pressionado: http://www.unidoscontraacorrupcao.org.br/compromisso

**Comment by parrahenri** [comment]
Olha, tem uma questão aí.

Todos os candidatos terão CARD pq serão colocados a partir dos dados do TSE. (email TSE ou sem email?)
Será email TSE nesse ponto? Ou sem email?
Quando o candidato responde o surveymonkey, passa a ter um novo email (que é o que ele coloca no formulário).
É isso?

Porque quando um cinza é pressionado, vai receber onde? (se não respondeu no monkey?)
E se ele não preencheu ainda, precisa ir pro RD primeiro (e depois pro monkey), mas se ele já respondeu e estiver mudando de opinião, deveria ir direto pro monkey.

@ricardopoppi

**Comment by ricardopoppi** [comment]
Sobre os emails, vai valer sempre o que estiver na planilha. Entendo que a regra de consolidação é usar email do TSE para os que não responderam e email do survey para os que responderam. Confere?

Sobre onde mandar: não acho um problema o cara que já respondeu ir pro rd tb e receber o link pro monkey novamente. Criar duas regras aí vai inserir um ponto de falha perigoso, pq vamos ter que controlar essas duas situações na jornada. No tempo que temos, alta chance de bug.

**Comment by parrahenri** [comment]
Sim, confere pras duas coisas. Sempre RD. E email da planilha (maior parte o email TSE).

O link correto é: http://www.unidoscontraacorrupcao.org.br/compromisso

Que é o RD
