### ISSUE TITLE
Conceber a ux e telas do sistema de notificações

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#17]
As notificações do besouro são fundamentais para informar sobre:
(i) novas missões
(ii) troféus adquiridos
(iii) votação em frases dentro das missões (integração com ej)
(iv) msgs do admin

Diante disso seria legal pensar o painel de notificações (que será desenvolvido na fase 2) de uma forma mais rica que um simples inbox. O céu é o limite nessa proposição. Inspiro @luizapeixe a propor algo, com acompanhamento e subsídios de @parrahenri

**Comment by parrahenri** [comment]
genial! Redes costumam fazer isso criando ícones diferentes entre as notificações né? 

Será um fluxo só ou usuário terá chance de dizer qual permite receber e qual não quer? Ex: quero receber do admin, mas não de novas missões.

(v) mensagens padrão recebidas dos candidatos nos quais eu tiver dado like
(vi) nova adesão de um candidato que não tinha aderido e no qual eu tinha dado unlike

Essas serão notificações tb

**Comment by luizapeixe** [comment]
primeira proposta saindo do forno:

• tela de lista de notificacões - https://invis.io/AMKSPGK26WN#/308496266_Notifica--es
Explicando:
1. a label rosa indica mensagem não-lida/não-clicada e a label cinza indica mensagem lida/clicada 
2. quando o user clica na notificação, vai direto para o destino relacionado à notificação (não tem hyperlink em trechos específicos do texto das notificações)
3. quando o user clica em "desativar notificações" ele deixa de seguir apenas notificações relacionadas àquela missão/trofeu/opinião/candidate ou assunto específico. Daí então a opção de "reativar notificações" aparece em azul. Para desativar o recebimento de toda uma categoria de notificações, precisa editar nas configurações das notificações.
4. o recurso de filtragem de notificações por categoria não possui a opção "ver todas". por default sempre aparecem todas e para filtrar o user deve selecionar a categoria deseja e, para voltar a ver todas, clicar novamente na categoria filtrada. (essa solução soa bem pra vocês?)

• tela de configuração das notificações - https://invis.io/AMKSPGK26WN#/308496265_Notifica--es_-_configura--es

**Comment by ricardopoppi** [comment]
Ficou muito legal @luizapeixe! Entendi que opção lido/não lido se dá pelo rosa. Os textos são sempre em negrito, é isso? 

Gostei da solução de filtros por botões, sem a categoria ver todas. 

Deixo uma provocação: do jeito que estamos pensando, esse stream acaba sendo mais que notificações. Será que não deveríamos ressignificar esse nome e símbolo pra algo mais completo? Timeline? Unidos world com um planeta e a fitinha da campanha aplicada? 

Peço ao @parrahenri comentar e avaliar esses delírios e os ajustes de conteúdo pra apresentação das telas amanhã

**Comment by parrahenri** [comment]
Eu achei animal!

Facebook usa Notificações ou Página Inicial (não acho que cabe, pq a nossa inicial não será ela). Ele usa um ícone de MUNDO/GLOBO. 
Twitter idem (lógica) e usa ícone de um sino que faz barulho. Instagram não dá nome e usa ícone de coração.

Mais pra reflexão. Eu manteria Notificações e agora pensei que temos de prever o ícone “CANDIDATOS” no menu fixo tb não? abs (uma coisa de cada vez rs)

**Comment by luizapeixe** [comment]
Eu fiquei com a nomenclatura ALERTAS na cabeça :P e manteria um ícone com alusão sonora, tipo um sino ou megafone... O que vocês acham?

Sobre o ícone de candidatos, já estou pensando nisso também. É um desafio esse ícone! será que uma urnazinha? Vocês têm sugestões?

**Comment by parrahenri** [comment]
Talvez pegar referências aqui:
https://play.google.com/store/apps/developer?id=Justi%C3%A7a+Eleitoral+Brasileira <https://play.google.com/store/apps/developer?id=Justi%C3%A7a+Eleitoral+Brasileira>
https://play.google.com/store/search?q=candidatos&c=apps <https://play.google.com/store/search?q=candidatos&c=apps>

O que vale evitar:

estereótipo do homem de terno, porque isso ajuda a reforçam uma imagem do que é político e nós queremos uma político menos branca, macha e rica né?

**Comment by luizapeixe** [comment]
exato, @parrahenri. o desafio é justamente desviar desse padrão automático sistêmico da gravata e da virilidade como sinônimo de política hehehe :P

Seguem algumas idéias:

![captura de tela 2018-07-13 as 14 07 42](https://user-images.githubusercontent.com/6249788/42704471-4d0b181e-86a6-11e8-882e-f5300edf94ab.png)

**Comment by parrahenri** [comment]
To entre o 2 e o 5!

**Comment by ricardopoppi** [comment]
fechando essa, implementação do sistema de notificações será feito na issue #63
