### ISSUE TITLE
Carregar a planilha já com os primeiros dados reais

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#176]
Instruções para carga da planilha (faz um double check especialmente aqui @parrahenri?):
Planilha saneada: 
[planilhacompleta_consolidade_28ago_semduplicatas_SANEADA_emailsmockados.xlsx](https://github.com/unidoscontraacorrupcao/ej-server/files/2334277/planilhacompleta_consolidade_28ago_semduplicatas_SANEADA_emailsmockados.xlsx)

1) Quando houver "e_mail_survey" preenchido, dar preferencia a ele na importação. Senão usar o campo "e_mail_tse".

2) Quando houver "ocupacao_survey" preenchido, dar preferencia a ele na importação. Senão usar "ocupacao".

3) O campo "compromisso_democracia" agora é chamado de "pacto"

4) Colapsáveis que entraram nessa planilha:
(i) campo "justificativa_adesao_medidas" é o conteúdo do colapsável "ADERIU TOTALMENTE ÀS NOVAS MEDIDAS?"
(ii) campo "total_bens" é o conteúdo do colapsável "TOTAL DE BENS E PATRIMÔNIO"
(iii) campo "detalhes_processos" é o conteúdo do colapsável "TOTAL DE PROCESSOS A QUE RESPONDE".

5) Na importação dos campos abaixo, só importar o que tem formato claro de URL (regex):
site_candidato	
url_facebook	
url_twitter	
url_instagram	
url_youtube	
financiamento_coletivo

**Comment by parrahenri** [comment]
1. Incluir uma interrogação:
de "ADERIU TOTALMENTE ÀS NOVAS MEDIDAS"
para "ADERIU TOTALMENTE ÀS NOVAS MEDIDAS?"

Sobre o que vc escreveu: verifiquei com Reinaldo e tá tudo certo!

**Comment by ricardopoppi** [comment]
Atualizei no corpo
