### ISSUE TITLE
Conceber repercussão ao usuário quando o candidato não tiver site ou redes sociais cadastradas

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#177]
- [x] @luizapeixe precisamos bolar uma repercussão, pois em alguns casos o usuário vai clicar no link das redes e o candidato não terá elas cadastadas, aí não acontece nada. Pode ajudar a conceber como a gente avisa o usuário nesse caso?

- [x] @parrahenri o texto da notificação de selecionar considera que todos os candidatos vão ter site cadastrado no app. Mas sabemos que isso não é verdade. Precisamos pensar um texto para o caso de candidatos que não tenham site cadastrado. Atualmente o texto da notificação de selecionado é: "VOCÊ SELECIONOU FULANA. CONHEÇA SUAS IDEIAS EM: site-do-candidato"

**Comment by parrahenri** [comment]
1. Quando não tiver site, mas tiver face: poderia puxar link do face?
2. Quando não tiver nda:

"VOCÊ SELECIONOU FULANA. VOCÊ ENCONTRA MAIS DETALHES DELA NA ABA "SELECIONADOS""

**Comment by luizapeixe** [comment]
é possível, do ponto de vista técnico, que não apareça o logo da rede se o candidate não tiver conta nela??

pro textinho, sugeriria algo tipo "VOCÊ SELECIONOU FULANA. SAIBA MAIS SOBRE ELA NA ABA **SELECIONADOS** "

na issue #181 sugerimos um toast que já puxaria o nome do candidate via código. o que acham? é muito complexo?

**Comment by danielhmarinho** [comment]
vou responder os aspectos técnicos aqui pra já adiantar.
- é bem simples a gente esconder a rede social se ela não tiver
- até fica mais simples assim mas o usuário vai continuar caindo no site após apertar na notificação?
- a complexidade não é tão alta, mas devemos avaliar com cuidado se isso é uma solução

**Comment by ricardopoppi** [comment]
respondendo o @danielhmarinho: vou criar duas issues independentes, uma para ocultar o botão das redes qdo não houver link na API e outra pra essa modificação do texto da notificação interna (já que nesse caso não teremos push) para os candidatos selecionados que não tiverem site_candidato na API

**Comment by ricardopoppi** [comment]
fechando essa pq já foi até implementada
