### ISSUE TITLE
Simplificar o texto dos toasts de seleção e pressão

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#181]
@luizapeixe @parrahenri atualmente o toast de seleção e pressão tem muito conteúdo para os poucos segundos que fica disponível. aumentar o tempo de permanencia dele também não é uma opção pois como é uma interação que tende a ser constante, tem alto potencial de irritar o usuário.

minha sugestão é sermos minimalistas nos textos. hj a gente agradece e fala um monte de coisa. sugiro que falemos o essencial da ação, algo assim:

1) Candidato pressionado com sucesso
Ele receberá um email nosso para que mude de opinião!

2) Candidato selecionado com sucesso
Veja mais detalhes sobre ele na aba selecionados

O que acham?

**Comment by parrahenri** [comment]
de acordo!

**Comment by luizapeixe** [comment]
Beleza! Que tal assim?

1.
![captura de tela 2018-08-29 as 10 37 31](https://user-images.githubusercontent.com/6249788/44791278-a3101c00-ab77-11e8-8020-7932c7042cf1.png)

2.
![captura de tela 2018-08-29 as 10 41 49](https://user-images.githubusercontent.com/6249788/44791525-2d588000-ab78-11e8-9658-4e99ddb53568.png)

**Comment by luizapeixe** [comment]
Beleza! Que tal assim?

1. 
![captura de tela 2018-08-29 as 10 48 51](https://user-images.githubusercontent.com/6249788/44791922-2b42f100-ab79-11e8-8fc5-363f00352628.png) *

2. 
![captura de tela 2018-08-29 as 10 47 58](https://user-images.githubusercontent.com/6249788/44791869-08b0d800-ab79-11e8-97d5-6dfec7baa3c0.png)



* sugestão: penso que clicando em _email_ poderia abrir um lightbox com o conteúdo do email que vamos enviar. O que acham?

**Comment by ricardopoppi** [comment]
legal @luizapeixe uma dúvda: acha que funcionaria esse link no toast, considerando a velocidade? além disso, há complexidades em formatar links no toast que não podemos absorver agora. Minha sugestão é fazermos agora sem isso. Vou encaminhar pra implementação, sem esse link do email. Obrigado!

**Comment by ricardopoppi** [comment]
maravilha, combinado!
