### ISSUE TITLE
Simplificar o conteúdo dos toasts de seleção e pressão

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#185]
1. 
![captura de tela 2018-08-29 as 10 48 51](https://user-images.githubusercontent.com/6249788/44791922-2b42f100-ab79-11e8-8fc5-363f00352628.png) 

*ignorar o item email em formato de link

2. 
![captura de tela 2018-08-29 as 10 47 58](https://user-images.githubusercontent.com/6249788/44791869-08b0d800-ab79-11e8-97d5-6dfec7baa3c0.png)

**Comment by danielhmarinho** [comment]
@ricardopoppi como disse no aspecto técnico essa issue não tem complexidade baixa. Devemos priorizar em que momento?

**Comment by danielhmarinho** [comment]
@ricardopoppi tem muita issue aberta e essa vai demorar um tempo. Foi por isso que perguntei kkkk To querendo limpar o caminho pra começar os favoritos e preciso de uma clareada nas prioriades

**Comment by ricardopoppi** [comment]
essas são prioridade. favoritos podemos começar terça que vem, só começa antes se o campo ficar limpo mesmo

**Comment by ricardopoppi** [comment]
se o nome do candidato complicar @danielhmarinho pode substituir por "O candidato receberá.." e "Veja mais detalhes sobre o candidato na aba..."
