### ISSUE TITLE
Atualizar texto de boas vindas com REGRAS DO JOGO

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#189]
Aqui você vê as/os candidatas/os que registraram: 1. Passado Limpo; 2. Compromisso com Democracia; e 3. Adesão às Novas Medidas contra a Corrupção.

SELECIONE para mais detalhes pessoais e eleitorais, bem como bens e processos. Também é possível PRESSIONAR quem não se comprometeu. Além de enviarmos um email, você conseguirá postar nas suas redes sociais.

Os nomes são apresentados aleatoriamente, sem nenhum tipo de viés nem preferência. Para dúvidas, acesse AJUDA.

**Comment by ricardopoppi** [comment]
@parrahenri fiz uns ajustes mínimos no texto

**Comment by parrahenri** [comment]
boa!
