### ISSUE TITLE
Conceber uma proposta para a msg de boas vindas pode ser fechada pelo usuário

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#196]
Concebe uma proposta @luizapeixe? A ideia é que o usuário possa fechar pra liberar mais espaço para os cards

**Comment by luizapeixe** [comment]
Podemos resolver com o botão de "close" no cantinho da mensagem, tipo assim:

![captura de tela 2018-08-31 as 10 26 46](https://user-images.githubusercontent.com/6249788/44915098-7a6b5c00-ad08-11e8-9be7-7c4855c99aff.png)

que tal?

**Comment by luizapeixe** [comment]
alias!! melhor rosa pra combinar a ação de fechar dos demais cards

![captura de tela 2018-08-31 as 12 13 41](https://user-images.githubusercontent.com/6249788/44920861-61b67280-ad17-11e8-9c1f-98aaf592d151.png)

**Comment by ricardopoppi** [comment]
fechando essa, #266 aberta para implementação
