### ISSUE TITLE
ISSUE PRA EXECUTAR EM PROD ANTES DO DEPLOY DA V3 - troca do texto do email de cadastro

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#197]
Elementos pra atualizar no email que o usuário recebe após o cadastro no app:

SENDER: Unidos Contra a Corrupção <campanha@br.transparency.org> 

Subject: Sua participação é decisiva nesta luta 

Conteudo: 

Olá, 

Seu cadastro na plataforma online da campanha Unidos Contra a Corrupção foi efetivado com sucesso. 

Agora, basta acessar https://app.unidoscontraacorrupcao.org.br para filtrar e conhecer as candidaturas que atendem aos três critérios da campanha: 

1. Passado limpo; 
2. Compromisso com a democracia; e 
3. Apoio às Novas Medidas Contra a Corrupção. 

Além de visualizar todas as candidatas e candidatos ao Congresso Nacional nestas eleições, você pode pressionar que ainda não aderiu à campanha e conhecer detalhes importantes sobre as pessoas que querem nos representar pelos próximos quatro anos. 

Se a candidata ou candidato que você pretende votar ainda não se comprometeu com a campanha, este é o momento para mostrar sua voz e cobrar essa participação.  

Vamos eleger parlamentares que se comprometam vão trabalhar, desde o início de seu mandato, para discutir e aprovar as Novas Medidas Contra a Corrupção! 

Unidos Contra a Corrupção.

**Comment by danielhmarinho** [comment]
@ricardopoppi   campanha@br.transparency.org essa parte vai no subject? Não entendi

**Comment by ricardopoppi** [comment]
@danielhmarinho não, esse é o sender, o remetente do email

**Comment by danielhmarinho** [comment]
@ricardopoppi eu nao entendi o ponto entao. o sender não é unidoscontraacorrupção.org?
