### ISSUE TITLE
alterar ícones dos botões PRESSIONAR e SELECIONAR

### ISSUE THREAD

**Issue by luizapeixe** [unidoscontraacorrupcao/ej-server#199]
os ícones de joinha pra cima e pra baixo foram alterados a pedido do cliente. na nova configuração PRESSIONAR é ilustrado por um Megafone e SELECIONAR é ilustrado por um pin.

O link pros novos assets é
- SELECIONAR: https://drive.google.com/file/d/1SY9F5U7NSQckdITczwVAMy3n6vDeYOVu/view?usp=sharing
- REMOVER SELEÇÃO: https://drive.google.com/file/d/1VVTzKT9sJcU6DJPQwLnclmZBiVE-O_ld/view?usp=sharing
- REMOVER SELEÇÃO 2: https://drive.google.com/file/d/15WL9iZmu5Kfv6I5YqGQjsCDyR24BK3Vf/view?usp=sharing
- PRESSIONAR: https://drive.google.com/file/d/1coi9tPfTzgje10NZSyLQlTrKeqivb-ec/view?usp=sharing

já foram alterados e atualizados no invision os layouts das páginas:
1. lista de candidates aba TODES
2. lista de candidates aba SELECIONADES
3. todas as internas das candidates
4. tela desktop de lista de candidates

PORÉM alterando os layouts da página de [NOTIFICAÇÕES](https://invis.io/YVNM1MXUA8H) percebi que o ícone de megafone já está sendo usado, ilustrando as mensagens de ALERTAS. Então isso precisará ser revisado ainda. Sugiro que a gente use um ícone tipo assim: ![captura de tela 2018-08-31 as 12 19 40](https://user-images.githubusercontent.com/6249788/44921659-8e6b8980-ad19-11e8-8666-4904b5102ce8.png) para os ALERTAS a partir de agora. O que acham?

**Comment by ricardopoppi** [comment]
@luizapeixe como esse pedido é antigo, e já estamos consolidando o app com os ícones atuais, vou fechar essa issue por hora. se no futuro precisarmos disso a gente reativa. (cc @parrahenri)
