### ISSUE TITLE
Definir as informações que constarão no profile do usuário, disponíveis para complementação e edição

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#2]
Peço ao @parrahenri e @luizapeixe fazer uma sugestão inicial de que itens são necessários aqui, considerando como base o profile do EJ

**Comment by luizapeixe** [comment]
A página de perfil do user no EJ hj apresenta as seguintes informações:

1. foto do user
2. nome
3. status de participante * (que pode vir a ser um recurso da gameficação)
4. lista de comentários que criou
5. lista de conversas favoritas
6. informações básicas (nome completo; cidade; gênero; cor/raça; movimento ou partido e biografia)
7. quadro de troféus
8. contribuições quantitativas (como número de votos, comentários, compartilhamentos e quests)

No caso da página de perfil do user no Besouro, não temos os itens 4 e 5 da lista acima. Acredito que não precisamos listar as missões no perfil pq elas já se encontram na página de missões, com fácil acesso pelo click na navbar. A não ser que seja uma listagem diferente, talvez mais resumida, apresentando apenas no nome das missões aceitas e o status de Concluída ou A Concluir.

**Comment by parrahenri** [comment]
De acordo, @luizapeixe! Tb acho que não precisa listar missões

**Comment by ricardopoppi** [comment]
legal gente! como essa proposta já está refletida [no wireframe](https://projects.invisionapp.com/d/main#/console/14558908/303032453/preview) ficamos antenados pra que após a validação com o cliente a gente passe pra dev junto com o resto (cc @parrahenri )
