### ISSUE TITLE
Remover duplicados na aba de seleção e criar uma proteção pra não selecionar cada card mais de 1 vez

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#201]
Os afetados pelo bug do mailgun acabaram ficando com cards duplicados (ou triplicados, quadruplicados) no feed de selecionados. Precisamos limpar os duplicados e criar uma proteção pra não acontecer.

UPDATE: Com esse bug, a jornada de seleção ficou instável. Mesmo o mailgun já estando ativo, as animações estão instaveis e o botão "remover seleção" ficou aparentemente sem evento.

Ver print:

![captura de tela de 2018-08-31 23-06-42](https://user-images.githubusercontent.com/1162183/44941521-b12b8b80-ad75-11e8-9fa8-ce72a039733c.png)

**Comment by davidCarlos** [comment]
Validação adicionada.
