### ISSUE TITLE
Traduzir mensagens de erro em inglês

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#202]
- [x] Erro de senha no login (PRINT 1)
- [x] Erro de email já registrado (PRINT 2)

PRINT 1

![whatsapp image 2018-08-31 at 19 43 44](https://user-images.githubusercontent.com/1162183/44951246-a7695d00-ae35-11e8-83bb-43fef8d9bf85.jpeg)

PRINT 2

![whatsapp image 2018-08-31 at 19 58 23](https://user-images.githubusercontent.com/1162183/44951249-b4864c00-ae35-11e8-95e7-fe165efeb8df.jpeg)

**Comment by danielhmarinho** [comment]
@ricardopoppi são somente esses os erros? Poderíamos passar um pente fino só para não ter que voltar aqui?

**Comment by ricardopoppi** [comment]
@danielhmarinho essas foram as que detectamos. Pente fino é legal sim. Tem alguma estrutura de tradução no código? Se tiver eu mesmo posso ajudar. Pela via da UX, foram essas duas que percebemos

**Comment by danielhmarinho** [comment]
@ricardopoppi primeiro eu estou mapeando como o jonathan fazia isso, aparentemente as repostas da api são jogadas nos toats e esses erros abaixo dos inputs são configuraveis pelo html. Vou mapear tudo do registro e do login
