### ISSUE TITLE
Função "esqueci minha senha" muito instável

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#203]
Recebemos relatos. Fui testar e realmente dá erro de formulário inválido com emails que eu tenho cadastrado no ambiente:

Log de erro:
app-shell.js:807 POST https://app.unidoscontraacorrupcao.org.br/rest-auth/password/reset/ 403 (Forbidden)
send @ app-shell.js:807
generateRequest @ app-shell.js:807
request @ app-shell.js:4644
_requestForgotPassword @ app-shell.js:6410
handler @ app-shell.js:1
_onForgotPassword @ app-shell.js:6352
handler @ app-shell.js:1
_fire @ app-shell.js:1
trackForward @ app-shell.js:1
touchend @ app-shell.js:1
_handleNative @ app-shell.js:1
app-shell.js:4644 api-forgot-password {detail: "CSRF Failed: CSRF token missing or incorrect."}

Print:
![captura de tela de 2018-09-01 20-19-50](https://user-images.githubusercontent.com/1162183/44950675-919f6c00-ae24-11e8-9408-d53106fd4e1c.png)

**Comment by ricardopoppi** [comment]
@danielhmarinho talvez isso tenha relação com as instabilidades do mailgun, então creio que ao aprimorar a lógica de envio de emails resolvemos essas instabilidades tb

**Comment by danielhmarinho** [comment]
@ricardopoppi não tem relação poppi. Esse é um problema gerado pelo django nao lidar corretamente com os tokens, motico que a gente precisa daquele endpoint de /reset. Vou arrumar aqui

**Comment by ricardopoppi** [comment]
ok, maravilha
