### ISSUE TITLE
Reestabelecer push sem o bug da lib pro iphone

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#209]
Reestabelecer push no app, com correção da lib que deixava tela branca no iphone

**Comment by davidCarlos** [comment]
Agora estamos servindo duas builds diferentes, uma pro safari e outra para o Chrome. Na build do safari o push está desabilitado, pois o safari não dá suporte pro firebase, que é a api de push notification que estamos utilizando.
