### ISSUE TITLE
Form de registro dando falso positivo de senha curta

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#21]
Senhas longas estão sendo interpretadas como curtas pelo form de registro:

![photo_2018-07-02_18-35-50](https://user-images.githubusercontent.com/1162183/42187521-c29d463e-7e26-11e8-882f-05a2d002a47b.jpg)

**Comment by arkye** [comment]
Não consegui replicar o erro. Tentei com as seguintes senhas:

* ricardo12345678
* abunchofwordsinaverylongphrase
* alannisteralwayspayshisdebtswithdeathandmisery

**Comment by ricardopoppi** [comment]
Também não consegui replicar novamente. Fechando a issue.
