### ISSUE TITLE
Conceber como desfazer a ação de "fechar"

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#210]
Hoje quando um usuário fecha um card ele some de todos os feeds. Não há como desfazer essa ação, se por acaso ela foi feita por engano.

Como resolver isso @luizapeixe @parrahenri?

**Comment by parrahenri** [comment]
Somando isso ao fato de que os PRESSIONADOS somem, talvez pudessemos criar algum lugar onde ficam esses descartados? pensando alto aqui.

**Comment by luizapeixe** [comment]
no caso dos pressionados, eles somem mas voltam caso alguma das agendas mude e o user é notificado da atualização das agendas do candidate pressionado. Porém pros fechados realmente não pensamos numa maneira de acessa-los novamente. 

(1) E SE, os cards fechados fossem ocultados apenas neste acesso à página e caso o user recarregue a página, os cards fechados voltassem a aparecer? CONTRA: pode ser irritante pro user ter que fechar novamente os cards q ele não quer ver // PRÓ: a irritabilidade poderia impulsionar o user à interagir com o cards (pressionando ou selecionando) ou filtros para manejar sua visualização

(2) OU E SE, quando o user fechasse um card, aparecesse um ícone de lixinho ali na barra do filtro (opção A.) ou no header (opção B.) apresentando a lista de cards que foram fechados?

**opção A**
na lista: 
![captura de tela 2018-09-03 as 12 51 52](https://user-images.githubusercontent.com/6249788/44995199-53b35c80-af78-11e8-99aa-f6146e9de611.png)

no lixo: 
![captura de tela 2018-09-03 as 12 52 16](https://user-images.githubusercontent.com/6249788/44995203-59a93d80-af78-11e8-996a-c2e0fea94475.png)

**opção B**
na lista: 
![captura de tela 2018-09-03 as 12 53 39](https://user-images.githubusercontent.com/6249788/44995215-6b8ae080-af78-11e8-9c0b-7edc6973baa0.png)

no lixo: 
![captura de tela 2018-09-03 as 12 58 01](https://user-images.githubusercontent.com/6249788/44995353-08e61480-af79-11e8-8b3a-9fa82d13ac8b.png)

**Comment by ricardopoppi** [comment]
@luizapeixe @parrahenri retomando essa aqui: eu prefiro a solução (1) pois não polui mais o nosso front, é mais simples de desenvolver e ainda, como vc falou Luiza, incentiva o usuário a seguir interagindo. É mais fácil alguém fechar por engano do que pressionar por engano.

O que acham? Posso passar pra implementação?

**Comment by luizapeixe** [comment]
sim! concordo que a solução 1 é mais prática.

**Comment by parrahenri** [comment]
Manda ver!

**Comment by ricardopoppi** [comment]
fechando essa pois abrimos a #264 pra implementação
