### ISSUE TITLE
Usuário recen criado não consegue fazer login quando desloga após registro

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#22]
Para simular:

1) Registrar novo usuário
2) Fazer logout
3) Tentar logar com esse mesmo usuário, usando email e senha no form de login

Trace do erro no inspector:

api.dev.besouro.ejplatform.org/rest-auth/login/:1 POST http://api.dev.besouro.ejplatform.org/rest-auth/login/ 400 (Bad Request)

app-shell.js:4343 api-login {non_field_errors: Array(1)}
_onError @ app-shell.js:4343
handler @ app-shell.js:1
fire @ app-shell.js:1
_handleError @ app-shell.js:731
error (async)
_addEventListenerToNode @ app-shell.js:1
_addMethodEventListenerToNode @ app-shell.js:1
applyEventListener @ app-shell.js:1
_stampTemplate @ app-shell.js:1
_stampTemplate @ app-shell.js:1
ready @ app-shell.js:1
ready @ app-shell.js:4343
_enableProperties @ app-shell.js:1
connectedCallback @ app-shell.js:1
connectedCallback @ app-shell.js:1
_attachDom @ app-shell.js:1
_readyClients @ app-shell.js:1
_flushClients @ app-shell.js:1
_propertiesChanged @ app-shell.js:1
_flushProperties @ app-shell.js:1
_flushProperties @ app-shell.js:1
ready @ app-shell.js:1
ready @ app-shell.js:1
_enableProperties @ app-shell.js:1
connectedCallback @ app-shell.js:1
connectedCallback @ app-shell.js:1
_attachDom @ app-shell.js:1
_readyClients @ app-shell.js:1
_flushClients @ app-shell.js:1
ready @ app-shell.js:1
ready @ app-shell.js:1
_enableProperties @ app-shell.js:1
connectedCallback @ app-shell.js:1
connectedCallback @ app-shell.js:1
_attachDom @ app-shell.js:1
_readyClients @ app-shell.js:1
_flushClients @ app-shell.js:1
_propertiesChanged @ app-shell.js:1
_flushProperties @ app-shell.js:1
_flushProperties @ app-shell.js:1
ready @ app-shell.js:1
ready @ app-shell.js:1
_enableProperties @ app-shell.js:1
connectedCallback @ app-shell.js:1
connectedCallback @ app-shell.js:1
(anonymous) @ app-shell.js:7969
f @ login:1
(anonymous) @ login:1
h @ login:1
e @ login:1
i @ login:1
(anonymous) @ login:1
a @ login:1
c @ login:1
f.onload @ login:1
load (async)
b @ login:1
d @ login:1
c @ login:1
(anonymous) @ login:1
setTimeout (async)
window.define @ login:1
(anonymous) @ login:1

**Comment by arkye** [comment]
Esse erro está associado à confirmação de cadastro. Depois que eu habilitei as configurações de e-mail para recuperação de senha, rest-auth começou a exigir a confirmação de cadastro. Vou desativar por ora a exigência de confirmação por e-mail.

**Comment by ricardopoppi** [comment]
Blz, deixemos desativado sim. Testei novamente e consegui logar normalmente. Sucesso
