### ISSUE TITLE
Ativação do botão compartilhar e ação compartilhar em pressão

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#220]
- [x] Ativação do botão "compartilhar" nos cards e nas internas, compartilhando a URL da interna com os seguintes metadados (texto):

CARD OU INTERNA VERMELHO 
Título: Quem não tem passado limpo não pode nos representar.
Subtítulo: \<nome-do-candidato\> não atestou passado limpo ou não se comprometeu. Vamos divulgar e pedir sua desistência.

CARD OU INTERNA CINZA
Título: Quem luta contra corrupção e defende a democracia não desiste nunca.
Subtexto: \<nome-do-candidato\> não respondeu tudo o que pede a campanha. Vamos ajudá-la/o a se lembrar.

CARD OU INTERNA VERDE
Título: Quem é contra corrupção e defende a democracia merece nosso apoio!
Subtexto: Essa é uma candidatura comprometida. Saiba mais sobre ela aqui.

- [x] Ativação da ação de compartilhar (mesmo componente) no botão de pressão (mantendo intactas a jornada e regras atualmente desenvolvidas)
COMO PRESSÃO É APENAS PARA CARDS CINZAS, SERÁ UM TIPO DE TEXTO SÓ:
Título: Ajude a luta contra corrupção e a defesa da democracia.
Subtexto: \<nome-do-candidato\> ainda não respondeu tudo o que pede a campanha. Cobre agora.

Imagem padrão para o meta: https://drive.google.com/file/d/1TMhrPxXqJV9owM3nYDZm0EZ36YVTRKVp/view?usp=sharing

UPDATE: Contabilizar para cada card/interna quantas vezes o compartilhar foi utilizado, tanto no evento do botão compartilhar quanto no evento do botão pressão

Os textos foram formulados considerando formato face (imagem abaixo), 40 caracteres de um TITULO e 40 caracteres de um SUBTITULO

![captura de tela 2018-08-29 as 18 53 39](https://user-images.githubusercontent.com/6249788/44817786-e0e36380-abbc-11e8-8649-916bf89acb91.png)

**Comment by parrahenri** [comment]
Cara, eu sublinhei essa questão pro cliente quando ele decidiu aquela mudança de regra de negócio. Raciocínio deles foi: todo mundo que se cadastrar vai dizer SIM pras duas coisas, ou deixar sem resposta. Ninguém vai ser doido de se cadastrar e dizer não pra mudar de cinza pra vermelho por iniciativa própria.

Então dá pra mantermos esse texto e monitorarmos. que tal? @ricardopoppi

**Comment by ricardopoppi** [comment]
@parrahenri blz, eu mantive mas fiz um ajuste no subtext: "ou não se comprometeu". Se achar melhor tirar a gente tira. Que tal?

**Comment by parrahenri** [comment]
achei de que ficou bom!

**Comment by ricardopoppi** [comment]
Conteúdos formato quote:

Botão de Compartilhamento:

CARD OU INTERNA VERMELHO
Quem não tem passado limpo não pode nos representar. <nome-do-candidato> não atestou passado limpo ou não se comprometeu. Vamos divulgar e pedir sua desistência.

CARD OU INTERNA CINZA
Quem luta contra corrupção e defende a democracia não desiste nunca. <nome-do-candidato> não respondeu tudo o que pede a campanha. Vamos ajudá-la/o a se lembrar.

CARD OU INTERNA VERDE
Quem é contra corrupção e defende a democracia merece nosso apoio! Essa é uma candidatura comprometida. Saiba mais sobre ela aqui.

No botão de pressão:

COMO PRESSÃO É APENAS PARA CARDS CINZAS, SERÁ UM TIPO DE TEXTO SÓ:
Ajude a luta contra corrupção e a defesa da democracia. <nome-do-candidato> ainda não respondeu tudo o que pede a campanha. Cobre agora.
