### ISSUE TITLE
Titulo da interna de candidatos sem estilos

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#222]
Conforme print:

![captura de tela de 2018-09-04 22-29-06](https://user-images.githubusercontent.com/1162183/45066072-ee07c300-b092-11e8-893e-d493c13402a5.png)

**Comment by davidCarlos** [comment]
Qual estilo esse título deveria ter? Porque esse comportamento de collapse no mobile não foi previsto nos wireframes.

@luizapeixe

**Comment by davidCarlos** [comment]
Pra fechar logo essa issue, eu apenas apliquei a mesma fonte usada na interna. Caso precise de alterações a gente reabre essa issue.

**Comment by luizapeixe** [comment]
aqui podemos manter a mesma tipografia do nome no card, ou seja, Folio Bold Condensed mesmo
