### ISSUE TITLE
Atualizar texto do tooltip/hover/(?) do "passado limpo"

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#223]
Ajuste no texto que fica no tooltip (?) do critério "Tem passado limpo?" nos cards:

O novo texto é: "Nosso critério de passado limpo é rígido. A referência são os crimes da Lei da Ficha Limpa. No caso de candidata/o à reeleição, veremos quem é réu no STF"

**Comment by ricardopoppi** [comment]
@danielhmarinho em dev, ainda consta o texto antigo:

![photo_2018-09-07_15-56-11](https://user-images.githubusercontent.com/1162183/45237976-8f229380-b2b6-11e8-86c8-269eeb444ee1.jpg)

**Comment by danielhmarinho** [comment]
@ricardopoppi acho que nao dei merge da branch com esses fix menores. Vou dar uma olhada
