### ISSUE TITLE
Formular de forma integrada a experiência de usuário de cadastro/login/esqueci-senha

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#229]
Atualmente o app está assim:

1) Se tento LOGAR com um email cadastrado e erro a senha ou tento fazê-lo usando o email do facebook (e tendo feito login por ele), RECEBO MSG PADRÃO: "Verifique se seu e-mail e senha estão corretos"

2) Se tento CADASTRAR com um email cadastrado ou usado no login facebook, RECEBO MSG PADRÃO: "Um usuário já se registrou com esse email"

3) Se tento RECUPERAR SENHA de um email cadastrado, ou um email não cadastrado, RECEBO MSG PADRÃO: "Se existe uma conta com este e-mail, um envio com instruções foi realizado."

3.1) Se o email foi usado pra login social, nunca recebo msg
3.2) Se o email não existe na base, nunca recebo msg.
3.3) Se o email existe na base, recebo msg com link de recuperação de senha (caminho feliz)

Porque estou levantando essa discussão? Porque os usuários esquecem. Esquecem o email que usaram, esquecem que fizeram login via facebook, esquecem qual o email que eles usam no facebook. Esquecem.

Elementos pra gente considerar:

1) Risco de engenharia social. Se a gente expõe que um email está cadastrado na nossa base, abrimos a possibilidade de um ataque validar quais emais nós temos. Hoje o formulário de cadastro faz isso, mas o de esqueci minha senha não. Fico em dúvida se pela natureza do app a gente deveria seguir se preocupando com isso.
2) Informação para o usuário. Hoje esses casos que a gente não manda email no formulario de recuperação de senha (qdo o email não está cadastrado ou quando o login foi feito via facebook) poderiam ser resolvidos com uma msg, por email, explicando. Aí não criaríamos exposição dos usuários mas não deixaríamos eles sem resposta.
3) No caso do usuário tentar se cadastrar com um email usado anteriormente pra fazer login social, acho que também deveríamos avisar. Talvez por email tb, pra não expor essa informação no público. Uma msg do tipo: "Opa percebi que vc tentou logar com o seu email do facebook. Lembre-se que vc está usando login social, então da próxima vez que tentar entrar no app, clique no link da rede social que vc usa" - algo assim
4) Outro ponto: aumentar o tempo de expiração de login próximo do infinito. Aí esses usuários nunca precisariam fazer login novamente

**Comment by parrahenri** [comment]
@ricardopoppi gostei desses dois itens e acho que resolvem muita coisa, especialmente o 4

No caso do usuário tentar se cadastrar com um email usado anteriormente pra fazer login social, acho que também deveríamos avisar. Talvez por email tb, pra não expor essa informação no público. Uma msg do tipo: "Opa percebi que vc tentou logar com o seu email do facebook. Lembre-se que vc está usando login social, então da próxima vez que tentar entrar no app, clique no link da rede social que vc usa" - algo assim
Outro ponto: aumentar o tempo de expiração de login próximo do infinito. Aí esses usuários nunca precisariam fazer login novamente

**Comment by parrahenri** [comment]
Dúvida, temos estatistica de porcentagem de cadastro e da porcentagem de login via face? Isso pode justificar uma mudança na tela, subindo o ícone do face e estimulando que as pessoas lembrem que acessaram assim?

**Comment by parrahenri** [comment]
@luizapeixe aproveitando, será que se a gente excluir a logo da campanha dessa tela de login não ganhamos um espaço bom? pq em alguns aparelhos, o icone do face fica escondido.

**Comment by luizapeixe** [comment]
Seria mesmo interessante ter uma estatística da quantidade de users que estão logando via Facebook, pra entender que prioridade damos pra visualização desse recurso.

Pensando sobre o ponto 1. de exposição dos emails cadastrados, e se a gente mudasse a frase de "Um usuário já se registrou com esse email" para algo menos nítido, como "Este email não pode ser usado, tente outro por favor". No fundo eles dizem a mesma coisa, porém de uma maneira menos exposta. Será que ajuda?

Concordo que o ponto 4, de deixar os users sempre logados, ajudam a minimizar os problemas de login dos usuários esquecidos.

Sobre retirar o logo da tela de login, tendo a preferir que a gente mantenha ele ali porém repensando seu tamanho pra tentar otimizar a visualização de todos os elementos. Ajustei a tela de login tentando otimizar espaços e dar mais destaque pra opção de login via FB, vejam: https://invis.io/6XNZQLCFHJ2

**Comment by ricardopoppi** [comment]
@luizapeixe @parrahenri dos 6.300 usuário cadastrados hj, 2.600 entraram via login social. Outro erro que temos recebido é o pessoal tentando fazer cadastro na tela de login. Parece que afeta usuários mais velhos que não rolam a tela pra ver o botão de cadastro ou não sabem a diferença entre login e cadastro

**Comment by ricardopoppi** [comment]
@luizapeixe será que não vale experimentar uma hipótese de tela de login, sema logo (ou muito diminuida), com o botão de "cadastre-se" na mesma hierarquia do login e mantendo esse botão do facebook reformulado que vc fez na nova proposta? Só pra gente ter duas opções e decidir juntes.

**Comment by luizapeixe** [comment]
Certo! Reformulei a posição dos elementos e agora temos um caminho pro "cadastre-se" bem próximo do login. Eles ainda não tem a mesma hierarquia (login ainda tem mais valor que o cadastre-se) entretanto nessa nova proposta o usuário não precisa rolar o scroll para enxergar o link de se cadastrar. O que acham?

-> https://invis.io/6XNZQLCFHJ2

**Comment by ricardopoppi** [comment]
@luizapeixe mto bom! minha percepção é que isso minimiza algumas das confusões dos usuários que estamos percebendo pelos reports

**Comment by parrahenri** [comment]
Consegue testar como fica em dispositivos com tela pequena pra termos certeza? Essa calibragem acho que será importante!

**Comment by ricardopoppi** [comment]
Além disso @luizapeixe tem uma coisa importante. Talvez o login social tenha que estar mais destacado que o cadastro. Hj temos aproximadamente 1/3 dos usuários que fazem login assim. Talvez com a prevalencia esse numero aumente.

Como referencia, veja o login do medium. Eles foram até mais radicais. Os logins sociais na primeira página e se alguém quiser preencher formulario, vai pra página seguinte. Achei que foi uma boa solução de simplificação. Veja print:

![captura de tela de 2018-09-13 17-49-19](https://user-images.githubusercontent.com/1162183/45523681-f2be2c80-b7a0-11e8-9766-8257c984647d.png)

**Comment by luizapeixe** [comment]
acho que priorizar o login social acima do login via email vai da nossa estratégia comercial / social também, pra além de seguir referencias externas. O ruim de priorizar o login via FB é que o FB é uma empresa concentradora/vendedora de dados e não tão transparente quanto gostaríamos, né? não sei se isso vai contra a filosofia do app de alguma maneira. Entretanto a solução do medium acaba por equalizar os meios de login, distanciando todas as opções de login por 1 click do user. Seguindo essa idéia, desenhei essa nova proposta, vejam: https://invis.io/MYO2A666CJB

**Comment by parrahenri** [comment]
gostei!

**Comment by ricardopoppi** [comment]
ok, issue #265 aberta para implementação
