### ISSUE TITLE
Atualizar proposta de galeria de trofeus com as especificidades da gameficação v1 do EJ

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#23]
Atualmente a proposta de wireframes da galeria de troféus no perfil apenas exibe os troféus. Porém os troféus serão recebidos e desbloqueados de acordo com uma regra especificada na gameficação.

A galeria deverá exibir de alguma maneira os troféus conquistados e os trofeus a conquistar, além daqueles que ainda estão bloqueados. Uma boa referencia pode ser chavear entre cor/preto-e-branco e um símbolo de cadeado naqueles ainda bloqueados.

Além disso a galeria deveria explicar o que o usuário deve fazer para conquistar os troféus. Deveriam eles ser clicáveis?

Essa issue é para atualizar [esse wireframe](https://projects.invisionapp.com/share/DGLGGUJHY67#/screens/303032454_Perfil_2) considerando o seguinte cenário:

(i) Troféus que serão conferidos pelas missões (sempre desbloqueados para qualquer usuário):
Troféu Perfil campeão (completamento do pefil)
Troféu Apoiador (cumprir a missão de apoiar abaixo assinado)
Troféu Ativista de Whatsapp (cumprir a missão de compartilhar a campanha no zap)
Troféu Ativista de Facebook (cumprir a missão de compartilhar a campanha no face)

(ii) Troféu que é soma de outros trofeús (bloqueado enquanto o usuário não ganhar os três troféus requisitos pra esse):
Troféu Super Ativista (soma dos troféus de tipo Apoiador + Ativista de Whatsapp + Ativista de Facebook)

(iii) Troféu conferido pela missão mas que tem pre-requisito de outro troféu (bloqueado enquanto o usuário não ganhar o troféu super ativista):
Troféu Mobilizador (após completar a missão "Criar grupo de Whatsapp para mobilizar pela campanha"). PREREQ: Para o usuário ter acesso a essa missão, requer possuir "Troféu Super Ativista".

**Comment by ricardopoppi** [comment]
cc @parrahenri

**Comment by luizapeixe** [comment]
que tal assim o quadro de troféus: https://invis.io/S8MIODH5GW3#/303032454_Perfil_2 ?

Daí, quando o user clicar em "VER MISSAO" ele é levado pra página da missão específica daquele troféu. E no caso dos troféus bloqueados, clicando no "ENTENDA" poderia abrir um splash tipo assim: https://invis.io/M6MIOHRRDGW#/306925983_Mobile_Portrait_Splash_Trofeu_Bloqueado

**Comment by parrahenri** [comment]
Senti falta de ter o nome da missão e algum outro destaque visual além do cadeado. É importante gerar estímulos que deixem a pessoa afim de desbloquear e fazer essa!

**Comment by luizapeixe** [comment]
@parrahenri tem razão. Incluir o nome da missão deve instigar o user a jogar. Alterei o layout do quadro de troféus considerando essa sugestão. Sobre os apelos visuais, confesso que ainda não tive o tempo de gostaria para me dedicar no estilo visual dos troféus. Não estou priorizando essa demanda no momento para agilizar as issues mais relacionadas com problemas de UX ou outras questões que impactam mais diretamente a implementação

**Comment by parrahenri** [comment]
boa! volta nisso depois!

**Comment by ricardopoppi** [comment]
@luizapeixe mto legal. Fiquei pensando que deveriamos talvez alterar a ordem das infos no perfil, dando mais destaque para os trofeus em vez das infos. Qdo o user vai pro perfil, já cai dentro dos trofeus. Mto radical?

**Comment by luizapeixe** [comment]
@ricardopoppi concordo que priorizar o quadro de trofeus no perfil realmente impulsiona o caráter gameficante do app! Mas acho que não necessariamente precisamos trocar os itens de lugar. E se a gente apenas definisse que sempre q o user entra no perfil dele, a aba selecionadas será a de troféus (centralizada entre as opções PERFIL, TROFEUS e CONTRIBUIÇÕES)? 
Eu gosto da opção INFO na lateral esquerda pq ela fica mais próxima dos metadados de nome e status do user, configurando um conjunto de informações mais pessoais do user. Além do que a aba INFO é bastante importante de ser visitada porque ela também rende um troféu. Acho q desloca-la para a lateral direita (onde hoje fica CONTRIBUIÇÕES) poderia diminuir a hierarquia de importância dela

**Comment by ricardopoppi** [comment]
parece bom!

**Comment by ricardopoppi** [comment]
Gente, to fechando essa issue pois vou abrir específicas de implementação
