### ISSUE TITLE
Aumentar infinitamente o tempo de duração da seção do usuário pra eles não terem que fazer login de novo

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#230]
Isso resolveria 90% dos ruídos que estamos tendo com o app

**Comment by davidCarlos** [comment]
Implementei uma lógica de renovação de token, sempre que o token do usuário expirar. Dessa forma ele não é deslogado e sempre vai ter um token válido para realizar novas requisições. Vale ressaltar que o ideal seria ter um segundo token que seria o token para expirar o token usado nas requisições da api, mas devido ao tempo curto isso não foi implementado.

**Comment by ricardopoppi** [comment]
sensacional, isso atende perfeitamente as necessidades de negócio do momento
