### ISSUE TITLE
Candidatos estão na base mas não estão sendo encontrados pelo filtro de nome

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#234]
Exemplo:

SANDRA GONÇALVES
PROFESSOR CEZAR HILDO
ROMEU GONÇALVES

Para replicar:

1) Procure por "gonçalves" no filtro de nome, com os outros filtros setados para "todos"
2) Note que nenhum dos dois Gonçalves acima, que estão na base, aparecem no resultado
3) Procure por "hildo" no filtro de nome
4) Note que o Professor Cezar Hildo, que está na base, não aparece.

O teste foi feito com usuário recém criado pra evitar o viés do usuário ter "fechado" algum candidato

**Comment by danielhmarinho** [comment]
@ricardopoppi fiz o teste e absolutamente todos esse candidatos apareceram

**Comment by ricardopoppi** [comment]
@danielhmarinho consegui replicar. Só acontece no mobile. Vai em dev, cria um novo cadastro, e pesquisa por "Gonçalves", mantendo todos os outros itens do filtro como "todos". 

Só vão aparecer dois cards.

**Comment by danielhmarinho** [comment]
@ricardopoppi pelo que percebi aqui tem alguma coisa no filtro quebrando em alguns momentos, vou tentar verificar o que pode ser

**Comment by danielhmarinho** [comment]
@ricardopoppi o filtro deslogado ta quebrando uma coisinha e já sei o que é, mas logado eu não consigo reproduzir esse comportamento =/

**Comment by ricardopoppi** [comment]
pois é mas o erro pra mim foi logado. aproveitei pra testar deslogado tb. coloquei gonçalves, tudo setado pra todos (como veio por default) e só apareceram os mesmos dois olha só o print:

![photo_2018-09-07_21-54-23](https://user-images.githubusercontent.com/1162183/45248549-995d8580-b2e8-11e8-8754-7ed7622f8686.jpg)

**Comment by ricardopoppi** [comment]
observe que tem o "carregar mais candidatos". Eu clico e não carrega mais.

**Comment by ricardopoppi** [comment]
@davidCarlos @danielhmarinho parece ser alguma situação específica do meu andoid, já que consegui replicar tanto no chrome mobile quanto no firefox mobile. Estou pedindo pra outras pessoas testarem, se eu tiver mais novidades, reabro aqui com elas
