### ISSUE TITLE
Investigar os gargalos de utilização na visualização de candidatos por usuários deslogados

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#235]
A página inicial do app, tanto mobile quanto desktop foi concebida pra ser acessível a usuários que queiram apenas navegar nos candidatos, filtrar e verificar a cor de cada card. Os botões de interação aparecem mas só fazem sentido para o usuário logado.

Nessa semana, recebemos a seguinte mensagem vinda de uma pessoa muito relevante na campanha: "Pessoal, será muito importante lançar uma versão totalmente simplificada do filtro nas vésperas das eleições. Sem nenhum tipo de login, pressão, missão, ou nada que complique a experiência de quem quer entrar e ver quem é verde, cinza ou vermelho. A única coisa que colocaria a mais seria algo para divulgar "santinhos". Nesta etapa, todas essas ferramentas adicionais de gamificação, pressão, coleta de dados são importantes, mas na reta final temos que fazer com que isso vire uma fonte de consulta super simples e amigável."

Diante disso, creio que será necessário fazer uma validação em campo de como os usuários estão se comportando na home deslogada. Pois ela já é, em tese, isso que está sendo solicitado. Creio que essa validação seria mais rica em algum evento que participassem mais pessoas interessadas na campanha e não apenas com o núcleo duro.

Acham essa ideia boa @parrahenri @luizapeixe? É viável?

**Comment by luizapeixe** [comment]
concordo seria bem bacana a gente abrir mais possibilidades de interação pro user deslogado. De cara, mesmo sem uma dinâmica de teste com usuários, já gostaria de sugerir 2 pontos:
1. permitir que users deslogades possam FECHAR os cards na aba TODOS
2. permitir que users deslogades possam ir pra interna do candidate clicando no nome ou foto do card

o recurso de selecionar é mesmo muito poderoso e útil pros eleitores. seria incrível se o user pudesse selecionar cards e formar uma coleção mesmo estando deslogado. Não sei se isso conversa com nossa estratégia de negócio, mas sou a favor dessa flexibilização de experiência sim! 

Não sei se é possível do ponto de vista técnico permitir que users não logados adicionem cards na aba de selecionados mas, caso sim, algo que pensei é que o user deslogado poderia selecionar cards porém se ele fechar o site sem se logar, poderá perder sua coleção de cards selecionados (tipo salvar cards selecionados via cache, talvez. faz sentido isso?).

Como solução pra lembrar o user de se logar poderíamos talvez exibir um splash (vulgo lightbox vulgo modal) no momento q ele clicar no botão "selecionar" avisando que o login é importante pra uma experiência completa no APP. E pra reforçar ainda mais a importância do login, poderíamos incluir uma faixa fixa no inicio da tela da aba de Selecionados (num estilo parecido com o toast, porém no topo da tela, e fixo) também avisando da importância do login. O que acham?

**Comment by ricardopoppi** [comment]
@luizapeixe reagindo e trazendo mais coisas que o pessoal da campanha nos trouxe (cc @parrahenri):

1) Sobre poder fechar deslogado me parece uma ótima. Abrimos uma issue sobre persistir o "fechar" apenas na sessão do usuário, quando deixariamos de registrar esse ato de ignorar candidatos. Hoje registramos ele pra cada usuário (issue #264)
2) Também me parece uma ótima. Assim os usuários teriam acesso à informações adicionais sem precisar passar pelo rito de login e selecionar
3) Avaliar a ressignificação do favortitar para uma narrativa de "santinho eleitoral" inclusive usando esse nome. Aí esse recurso entraria na ultima semana, no lugar do selecionar e pressionar que seriam ocultados. Importante que a proposta aproveite a mesma dinâmica dos favoritos, que já foi desenvolvida
4) Foco no serviço de informação: (i) filtro ser carregado aberto e/ou outras melhorias pontuais e (ii) ocultar temporariamente os ícones de missões tanto do menu hamburger quanto da navbar, que poderia dar espaço para o ícone dos "santinhos"

Pode avaliar e propor considerando isso? Pra facilitar a assertividade na implementação importante que, além das telas, vc possa detalhar os novos fluxos de ux.

**Comment by ricardopoppi** [comment]
@luizapeixe (cc @parrahenri), trazendo mais elementos pra essa aqui que serão válidos para a ultima semana do app:

1) Possível fechar deslogado e fechar persiste apenas na sessão mesmo para os logados
2) Ocultar os botões de missões tanto do menu quanto da navbar
3) Filtro carrega aberto
4) O clique no nome do candidato e na foto leva para a interna, em qualquer aba
5) A aba favoritar vira SANTINHO
6) ADICIONAR SANTINHO passa a ser a única interação possível na aba de todos (além do acesso à interna)
7) ADICIONAR SANTINHO também será possível na aba selecionados, mantendo as outras interações (como APOIAR)
8) A aba SANTINHO ganha botão no menu e na navbar

**Comment by parrahenri** [comment]
+ conseguir entrar na interna sem necessidade de login

**Comment by parrahenri** [comment]
eventualmente o compartilhar nessa nova versão possa virar botão ao lado do santinho, vale estudar

**Comment by ricardopoppi** [comment]
@parrahenri bem levantado. Hj o compartilhar nos cards vermelhos e cinzas faz pressão (tanto pra desistir quanto pra responder). Precisamos decidir:

1) compartilhar será mantido na aba TODOS e SELECIONADOS? 
2) O ADICIONAR SANTINHO estará disponível para os vermelhos? 
3) O compartilhar na aba de SANTINHOS estará disponível para todas as cores? 
4) Haverá conteúdos diferentes no compartilhamento dependendo da cor quando feito na aba SANTINHOS?

**Comment by parrahenri** [comment]
1. Sim e Sim
2. Sim
3. Sim
4. Sim, mas tem uma questão sensível aqui. Porque pode ser escolhido por uma pessoa que gosta, ainda que seja vermelho.

**Comment by ricardopoppi** [comment]
Sobre o ponto 4: Se mantém o texto atual, o compartilhamento de santinhos vermelhos se mantém como "pressão por desistência" até o final. É por aí?

**Comment by ricardopoppi** [comment]
para registrar, botão fechar deslogado não será possível. motivos:
1) não é comum permitir post para usuários deslogados (falha de segurança)
2) o custo de refatoramento pra isso acontecer é muito superior ao valor para o usuário
3) o filtro é bem completo e atende todas as necessidades do usuário para organização do deck

**Comment by luizapeixe** [comment]
Obrigada pela organização das demandas, pessoal. Sobre a questão da sessão Santinhos, temos alguns pontos a considerar:

1. nomenclatura do botão de ação nos cards (aba selecionados)
por questões de diagramação, é importante que a nomenclatura aqui não seja muito extensa. Estou sugerindo "Tornar Santinho" como ação pro botão. Para reverter essa ação, pensei em "Rasgar Santinho" mas não sei se pode soar meio radical. O que acham?

2. icone figurativo
por se tratar de um ícone que é aplicado bem pequeno no layout (20px no máximo) faz-se necessário utilizar poucos elementos para representa-lo, caso contrário ficará poluído e possivelmente difícil de interpretar. Depois de alguns rascunhos cheguei em 4 primeiras propostas aqui, duas mais genéricas (estrela e coração) e duas mais específicas (panfleto e anjo). 

segue abaixo a primeira leva de propostas para ilustrar os botões tanto de ação quanto da navbar:

![captura de tela 2018-09-18 as 21 33 30](https://user-images.githubusercontent.com/6249788/45724083-dd734480-bb8a-11e8-9467-1dece7433b71.png)
pró: ilustra ao pé da letra a palavra santinho
contra: pode confundir aqueles não familiarizados com o termo "santinho" como panfleto eleitoral

![captura de tela 2018-09-18 as 21 33 39](https://user-images.githubusercontent.com/6249788/45724087-e19f6200-bb8a-11e8-8528-769d9f3c03a3.png)
pró: ilustra literalmente o que é um santinho
contra: ícone composto por mtos elementos, não é clean

![captura de tela 2018-09-18 as 21 33 53](https://user-images.githubusercontent.com/6249788/45724091-e532e900-bb8a-11e8-9639-845416d2f57b.png)
pró: ícone clean, óbvio, representa a ação de favoritar
contra: não ilustra o termo "santinho"

![captura de tela 2018-09-18 as 21 34 00](https://user-images.githubusercontent.com/6249788/45724098-ea903380-bb8a-11e8-910e-5833770445c9.png)
pró: ícone clean, óbvio, representa a ação de favoritar 
contra: não ilustra o termo "santinho"

O que acham? Pitaquem e sugiram a vontade!

**Comment by ricardopoppi** [comment]
a 1 ficou muito boa @luizapeixe! mas pelas mesmas questões que vc apontou eu iria de 3 ou 4. Preferencialmente 3, pq a estrela tb tem aquela conotação de "rate", ou seja, um candidato que vc dá estrelinhas é um que vc dá nota alta e vai votar

**Comment by parrahenri** [comment]
Sobre isso:

1. acho importante mandarmos todas as opções de ícones pra eles escolherem
2. Em vez de “Tornar santinho” sugiro “Salvar no"

**Comment by luizapeixe** [comment]
1. concordo que devemos mostrar pelo menos 4 opções pro cliente poder opinar também. Compartilho com vocês algumas outras soluções que desenhei, caso achem interessante trocar uma solução por outra dentro dessas 4 preferidas que postei ontem. Vejam:

![captura de tela 2018-09-19 as 11 59 59](https://user-images.githubusercontent.com/6249788/45762191-329f6c80-bc04-11e8-8873-7ebe56ad12f8.png)

2. Outras sugestões: "Obter santinho" ou "criar santinho" ou "Adotar santinho"

**Comment by parrahenri** [comment]
@luizapeixe consegue criar com 3 frases diferentes tb? assim eu apresento pra eles:

TORNAR SANTINHO
SALVAR NO SANTINHO
CRIAR SANTINHO

**Comment by luizapeixe** [comment]
claro! só uma ressalva pra sugestão de "salvar no santinho", é que essa quantidade de caracteres já fica muito extensa para aplicar no botão, pois no caso de ser um card verde, deve aparecer também o botão de "apoiar" e isso acabar por limitar pela metade o tamanho do nosso botão de "Santinhar", veja:

![captura de tela 2018-09-19 as 12 57 10](https://user-images.githubusercontent.com/6249788/45765526-9a0cea80-bc0b-11e8-9e39-19282554d3c6.png)
ps.: ignore o ícone do coração

**Comment by parrahenri** [comment]
@luizapeixe devemos tirar o botão de apoiar c/c: @ricardopoppi

**Comment by parrahenri** [comment]
Salvar no santinho
Tirar do santinho

**Comment by luizapeixe** [comment]
> @luizapeixe devemos tirar o botão de apoiar c/c: @ricardopoppi

nesse caso podemos ficar mais tranquilos com relação as nomenclaturas dos botões. 

segue abaixo as propostas atualizadas:

![captura de tela 2018-09-19 as 13 45 08](https://user-images.githubusercontent.com/6249788/45768131-59fd3600-bc12-11e8-9f6f-60ba727eed23.png)

![captura de tela 2018-09-19 as 13 45 17](https://user-images.githubusercontent.com/6249788/45768142-5d90bd00-bc12-11e8-8e60-4dd3bd063533.png)

![captura de tela 2018-09-19 as 13 45 27](https://user-images.githubusercontent.com/6249788/45768146-61244400-bc12-11e8-90f4-e380053ccd77.png)

![captura de tela 2018-09-19 as 13 45 34](https://user-images.githubusercontent.com/6249788/45768152-65506180-bc12-11e8-900b-b15b7c7b1873.png)

**Comment by parrahenri** [comment]
bele! bota santinho sempre no singular, porfa. vai ser o nome da aba.

**Comment by luizapeixe** [comment]
> bele! bota santinho sempre no singular, porfa. vai ser o nome da aba.

as abas hoje são no plural. devemos manter os santinhos diferentes das demais abas mesmo?

**Comment by parrahenri** [comment]
sim, infelizmente vai ter essa diferença! Pq as demais fazem referência aos candidatos e esse “santinho” é aquele papel, espécie de colinha que registra todos os candidatos em que vc vai votar. :/

**Comment by luizapeixe** [comment]
Ok! entendido sobre a questão da aba SANTINHO ser no singular.

algumas dúvidas sobre outras demandas dessa issue:

3- filtro carrega aberto
Isso demanda alguma alteração de design ou é uma orientação mais pra DEV?

7- ADICIONAR SANTINHO também será possível na aba SELECIONADOS, mantendo outras interações (como APOIAR)
Me aprece que o botão de APOIAR não estará mais ativo nessa próxima etapa. confere @parrahenri ?

9- Pressionados pelo usuário passam a aparecer na aba TODOS
vamos mostrar na interface dos cards quando for o caso de candidatos Pressionados?

**Comment by ricardopoppi** [comment]
@luizapeixe respondendo (cc @parrahenri)

3- Atente pra issue #112 te marquei la nessa concepcao
7- Com base na proposta validada, eu orientei o time a manter as interacoes existente, incluindo o APOIAR (@parrahenri isso tem que cair mesmo? senão vou ter que alterar a conversa que fiz ontem no planning e atualizar a issue, preferia não causar esse disturbio, o que acha?)
9- Não mostraremos, os cards pressionados serão identicos aos outros cards, pois já terá encerrado a fase de pressão e não haverá mais botão para fazer isso

**Comment by parrahenri** [comment]
@ricardopoppi sim, tem que cair. Bruno pediu pra tirar tudo.

**Comment by parrahenri** [comment]
Parra, vamos lá.
 
O que decidimos é o seguinte.
 
Vamos mesmo com: “salvar como santinho”.
 
No caso do símbolo, discutimos que a estrela é um símbolo bastante difundido de favorito, isto é, de algo que você guarda para conferir depois.
 
Além disso, a palavra “estrela” é simples e fácil para a gente usar na própria comunicação (missões, posts, emails, etc).
 
A gente pode fazer um post dizendo “Você sabia que poderia salvar seu candidato como um santinho digital apenas apertando na estrela?”
 
Portanto, essa parte está decidida. Blz?
 
Abs, Bene.

**Comment by luizapeixe** [comment]
Beleza! Vamos aos layouts então

aba TODOS: https://invis.io/AZO5FHSX7SD *
aba SELECIONADOS: https://invis.io/ZSO5FIB4NJE
aba SANTINHO: https://invis.io/N9O5FIHSMG7

* reparem q eu alterei o fundo do botão "fechar" de rosa pra cinza (#B7B8B7). A intensão é deixar esse botão mais discreto e chamar mais atenção para as outras interações com o card

**Comment by ricardopoppi** [comment]
blz, sobre o apoiar vou atualizar a issue a avisar o pessoal amanhã. sobre as propostas visuais a partir dessas decisões @luizapeixe pode produzir os wireframes e linkar eles aqui?

**Comment by luizapeixe** [comment]
e menu hamburguer: https://invis.io/Z3O5FRTF2KS

**Comment by ricardopoppi** [comment]
@luizapeixe maravilha! vou atualizar na issue da implementação. Valeu pela super agilidade de sempre!

**Comment by ricardopoppi** [comment]
Fechando essa issue pois a concepção está feita

**Comment by luizapeixe** [comment]
e icones no drive
Salvar como santinho: https://drive.google.com/file/d/1qKJVV1J1r9_0s_fqGl_H9-5Q19SIW0Iv/view?usp=sharing
Desfazer santinho: https://drive.google.com/file/d/1f365Uu2sX63qJZHleb1fl7HSWDWrpdyW/view?usp=sharing

**Comment by ricardopoppi** [comment]
@luizapeixe vamos ter que fazer alguns ajustes pontuais do que veio da aprovação com o pessoal da campanha. Se possível mantenha nos mesmos links pois já transportei eles pra issue de implementação. Se não for possível me avisa que atualizo lá.

São eles:

Aba TODOS
1 - O título da página qdo a aba TODOS tá selecionada poderia ser trocado de "CANDIDATOS" por "TODOS OS CANDIDATOS"
2 - O botão "fechar" poderia ser chamado de "esconder" (no card)

Aba SELECIONADOS
3 - Trocar o título da página, quando a aba está ativa de "CANDIDATOS" para "SELECIONADOS".
 
Aba SANTINHO
4 - Mesma coisa, quando a aba está ativa, trocar o título de "CANDIDATOS" por "SANTINHO".
 
MENU
5 - Trocar "CANDIDATES" por "CANDIDATOS";
6 - e trocar "Voltar às Novas Medidas" por "Site da campanha".
 
Navbar
7 - Trocar "CANDIDATES" por "CANDIDATOS".
 
Extras
8 - Importante vermos uma mensagem no fim da rolagem dos cards, quando acabam os cards: "não há mais candidatos"

**Comment by luizapeixe** [comment]
OK! telas atualizadas

aba TODOS: https://invis.io/AZO5FHSX7SD
aba SELECIONADOS: https://invis.io/ZSO5FIB4NJE
aba SANTINHO: https://invis.io/N9O5FIHSMG7
e menu hamburguer: https://invis.io/Z3O5FRTF2KS
