### ISSUE TITLE
Carregar nova versão da planilha (8-set)

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#236]
Segue planilha já saneada: 
[planilhacompleta_consolidade_8set_colunajustificativalimitada500char.xlsx](https://github.com/unidoscontraacorrupcao/ej-server/files/2371099/planilhacompleta_consolidade_8set_colunajustificativalimitada500char.xlsx)

**Comment by ricardopoppi** [comment]
@davidCarlos sobre importação, achamos um candidato que tá na planilha e não entrou no app:  ANDERSON LUZ DOS SANTOS  BATATA ANDERSON  UF: SC - 00362869901

**Comment by davidCarlos** [comment]
Planilha importada no ambiente dev.

**Comment by ricardopoppi** [comment]
@davidCarlos na importação em prod, é necessário importar as 3 fotos novas que foram coletadas do TSE, que estão aqui: https://drive.google.com/drive/folders/1hsjcp1FA9NMJgxXuh8EkLtG3UNzOKxym

**Comment by luizapeixe** [comment]
ok! foto colorida atualizada porém agora ela tem 20kb enquanto as outras têm 6 e 7 kb. Precisa passar aquele scrpt de linux do @davidCarlos 

-> https://drive.google.com/file/d/1mxwXhsKzXkO-yFNkByWKo9OObGQ540_E/view?usp=sharing

**Comment by ricardopoppi** [comment]
fechando essa pois carga foi feita. para as fotos abrirei nova issue
