### ISSUE TITLE
Instabilidades no login social em iphone/safari

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#237]
Report recebido ontem a tarde/noite, usuário já tinha cadastro via login social, fez várias tentativas durante algumas horas (das 18hs às 21hs aproximadamente).

O email do usuário vou mandar em pvt pra ajudar na verificação de logs. Vamos olhar como oportunidade pra descobrir essa fonte de instabilidade que pode estar vitimando outros usuários de iphone/safari (recebemos alguns relatos indiretos disso).

Sintoma: A aba do facebook é aberta, retorna pro app e fica carregando infinitamente na tela do login. Se o usuário tenta acessar diretamente a home do app "/candidates" segue não logado

Videos:

[videos_bug_loginsocial_îphonesafari.zip](https://github.com/unidoscontraacorrupcao/ej-server/files/2366466/videos_bug_loginsocial_iphonesafari.zip)

Como nunca vamos poder prever todas as fontes de instabilidade, a issue #230 tem ficado cada vez mais relevante. Quanto menos logins os usuários precisarem fazer, menos chance de erro por parte deles, menos chance de instabilidade no oauth.

**Comment by davidCarlos** [comment]
Se o usuário não consegue logar nem a primeira vez a issue #230 não faz sentido pra resolver esse problema. Temos que investigar pq o cadastro não está funcionando bem no iphone/safari.

**Comment by ricardopoppi** [comment]
Esse usuário tinha conseguido logar sim, ele tem conta no app. Foi retorno. A #230 resolveria sim. 99% das reclamaçoes que estou recebendo é retorno.

**Comment by ricardopoppi** [comment]
não conseguimos reproduzir
