### ISSUE TITLE
Erro na aba de seleção: app mudando a candidata selecionada

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#243]
Usuário: liana_morisco@hotmail.com
Candidata selecionada: SP | SENADOR | 457 | MARA CRISTINA GABRILLI | MARA GABRILLI | 24731270855
Candidato que apareceu incorretamente na aba, no lugar dela: SP	SENADOR	131	EDUARDO MATARAZZO SUPLICY	EDUARDO SUPLICY	05909198815

**Comment by davidCarlos** [comment]
não consegui reproduzir, Vamos seguir monitorando e se mais usuários reportarem o mesmo problema damos uma investigada mais a fundo.
