### ISSUE TITLE
Gerar exportação dados Besouro

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#263]
Modelagem final

Planilha de usuários
Nome
Email
Cidade
UF
Genero
Raça
Tel/whatsapp
Idade
Missões aceitas
Missões concluídas
Candidatos Selecionados
Candidatos Favoritados
Candidatos Pressionados
Candidatos Compartilhados

Planilha de candidatos
ID (CPF)
Nome urna
UF
Passado limpo
Pacto/Democracia
Novas medidas
Num vezes Favoritados
Num vezes Selecionados
Num vezes Pressionados
Num vezes Compartilhados
Num vezes Ignorados
Mudou status?

**Comment by ricardopoppi** [comment]
@davidCarlos podemos simplificar, basta um botão onde o usuário recebe o(s) csv(s) default sem ter opção de escolher nada

**Comment by davidCarlos** [comment]
Exportação está pronta. Faltam os dados relacionados aos favoritos, uma vez que esse código ainda não entrou na branch stable. Quando a issue de favoritos estiver pronta, eu adiciono essas informações na exportação.

Para exportar os dados:

```docker exec -it <id do container da api> ./manage.py shell -c "from ej.export_to_csv import export; export()"```

**Comment by ricardopoppi** [comment]
Só pra registrar aqui antes do guia, o script gera dois arquivos:
USERS_CSV_FILE_PATH = /tmp/usuarios_exportados.csv
CANDIDATES_CSV_FILE_PATH = /tmp/candidatos_exportados.csv
