### ISSUE TITLE
Atualizar tela de login/cadastro com mais destaque para login social

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#265]
Nessa nova proposta, o fluxo de interação é:

1) A primeira tela apresenta, em igual hierarquia, as opções de login por email ou facebook. TELA: https://invis.io/ZDO3HN385UJ
2) Se o usuário clicar no login por email, os inputs de email e senha abrem. TELA: https://invis.io/6XNZQLCFHJ2 (Observar que o botão cadastre-se não aparece mais no final mas logo abaixo do botão "ENTRAR"
3) Se o usuário optar por se cadastrar por email, vale a tela atualmente implementada

**Comment by danielhmarinho** [comment]
@ricardopoppi só não entendi pq a primeira tela tem logo do ej kkk devemos apenas substituir pelo besouro, correto?

**Comment by ricardopoppi** [comment]
ahahaha ignora que foi alguma atualização indevida, avisei a @luizapeixe ela vai voltar a tela correta

**Comment by luizapeixe** [comment]
Agora sim, pessoal!

1. A primeira tela apresenta, em igual hierarquia, as opções de login por email ou facebook. TELA: https://invis.io/ZDO3HN385UJ

2. Se o usuário clicar no login por email, os inputs de email e senha abrem. TELA: https://invis.io/6XNZQLCFHJ2 (Observar que o botão cadastre-se não aparece mais no final mas logo abaixo do botão "ENTRAR"

Se o usuário optar por se cadastrar por email, vale a tela atualmente implementada

**Comment by danielhmarinho** [comment]
@ricardopoppi uma ressalva aqui. Se a pessoa optar por cadastrar por email na tela temos que pelo menos alterar o estilo do botão do facebook. Manter aquele botão redondo vai ficar estranho pro usuário.

**Comment by ricardopoppi** [comment]
@danielhmarinho de acordo, o ideal é replicar o novo estilo do botão, conforme a tela de login (https://projects.invisionapp.com/share/6XNZQLCFHJ2#/screens) ou seja, replicar esse mesmo botão na tela de cadastro
