### ISSUE TITLE
Permitir ao usuário fechar a msg de boas vindas

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#266]
O efeito pode persistir somente durante a sessão do usuário.

Proposta:

![captura de tela 2018-08-31 as 12 13 41](https://user-images.githubusercontent.com/6249788/44920861-61b67280-ad17-11e8-9c1f-98aaf592d151.png)

**Comment by danielhmarinho** [comment]
@ricardopoppi os boas vindas de missão e de candidate nao podem fechar juntos, correto? Hoje a gente usa um mesmo componente para ambos apenas mudando o texto, se a lógica for( e deve ser o mais correto mesmo) o usuário podendo fechar cada uma individualmente vai exigir uma certa refatoração.

**Comment by ricardopoppi** [comment]
Por hora fecham juntos aí a gente avalia a prioridade da refatoracao, c ctz não é agora. Que tal?

**Comment by danielhmarinho** [comment]
@ricardopoppi enquanto implemento acho que vai facilitar muito, mas se for simples de separar eu já faço dessa maneira

**Comment by ricardopoppi** [comment]
@danielhmarinho combinado
