### ISSUE TITLE
Avaliação técnica: é possível preservar interação de usuários deslogados usando apenas cookie/sessão?

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#267]
@davidCarlos @danielhmarinho há algo no stack que usamos que permitiria isso?

**Comment by danielhmarinho** [comment]
@ricardopoppi possível é. Manter as coisas na sessão do navegador é relativante simples, meu problema é apenas o tempo que temos e quais são as interações que serão possíveis

**Comment by ricardopoppi** [comment]
ok, avaliação feita, fechando essa
