### ISSUE TITLE
Conceber um campo/opção na tela de edição de informações do perfil onde o usuário doa dados à campanha

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#27]
Hoje a tela de edição de perfil está limitada à edição de campos. Para produzir um efeito pedagógico sobre a importância dos dados pessoais, precisamos criar uma dinamica simples que contribua com essa consciência.

Ex:

Um campo extra ou um splash ao salvar com um conteúdo mais ou menos assim (peço ao @parrahenri revisar):

Obrigado por complementar informações do seu perfil! Há varias maneiras de contribuir com a campanha e uma delas é permitindo que a coalização acesse seus dados e possa falar com você diretamente! Queremos oferecer oportunidades de mobilização personalizadas para você com base no que compartilha conosco. Mas essa é uma opção inteiramente sua e que pode ser revogada a qualquer momento.

- [ ] Aceito compartilhar essas informações com a campanha, para uso exclusivo na campanha

![screencapture-dev-besouro-ejplatform-org-profile-2018-07-06-08_59_42](https://user-images.githubusercontent.com/1162183/42378035-2e6a8840-80fc-11e8-9695-d21b35530a10.png)

**Comment by parrahenri** [comment]
Gostei do texto. Esse "revogar" na prática será como?

**Comment by ricardopoppi** [comment]
A principio, desmarcando/alterando essa mesma opção. Na prática, uma nova exportação indicaria que o usuário fez um opt-out e ele seria excluido dos sistemas externos (RD Station etc)

**Comment by parrahenri** [comment]
Massa! to de acordo com o texto e valeria ter as opções:

1. permito que a campanha me envie notificações aqui no app
2. permito que  que a campanha me envie emails

**Comment by luizapeixe** [comment]
realmente, questões interessantes para se refletir!

Cheguei a desenhar a tela de edição de perfil com as opções de notificações ali entretanto de fato faz mais sentido que essas opções estejam numa área dedicada as configurações das notificações (a ser desenhado na fase 2 com base na #17 ). Então tendo a gostar mais da ideia de apresentar essas opções no splash de confirmação de atualização do perfil:

![captura de tela 2018-07-09 as 13 52 06](https://user-images.githubusercontent.com/6249788/42464411-55aca2b4-837f-11e8-9271-bad8dbdff902.png)

**Comment by ricardopoppi** [comment]
@luizapeixe @parrahenri  agora que temos a tela de notificações e as configurações, podemos pensar qual a melhor estratégia para isso. para fins de otimização de desenvolvimento o ideal seria concentrar tudo na tela de configurações das notificações. Além disso, lendo a política de privacidade da transparencia internacional, a lógica é de opt-out e não opt-in. Acho que devemos deixar isso para as fases/versões futuras do besouro então.
