### ISSUE TITLE
Item "ver regras" da home e do menu lateral não está linkado com o conteúdo estático /rules/

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#28]
Os links não estão ativos

**Comment by ricardopoppi** [comment]
Nesse primeiro momento podemos servir fora da api como estático no app. Peço ao @parrahenri indicar esses conteúdos

**Comment by parrahenri** [comment]
Aqui ainda estou inseguro quais regras são essas. São as regras da gameficação? Como ganhar pontos e tudo isso? pq a rigor, não há regras pq não se trata de um concurso ou coisa do tipo. Não há prêmios mesmo (os troféus e tudo isso é melhor que fiquem auto-explicados na propria área de troféus).

Que acham @luizapeixe e @ricardopoppi? 

Eu tiraria esse link.

**Comment by ricardopoppi** [comment]
Eu não tiraria. Aproveitaria esse link pra resumir as regras das missões e troféus, ainda que elas se repitam na galeria de troféus. Essa redundancia não pesa, eu acho.

**Comment by parrahenri** [comment]
Minha reflexão é de que a campanha já tem muito conteúdo, medidas, já temos página de ajuda, de privacidade. Esse ver regras tá com bastante evidência e faz sentido quando a gameficação for o central da coisa, quando comentários ou autores ganharem algo também e por aí vai. Por isso pensei que tá sobrando.

**Comment by ricardopoppi** [comment]
É de fato tem muito conteúdo de distração mesmo. A vantagem do ver regras é que ele agrada o tipo de usuário "estudioso" ou de mais idade. Digo isso porque é esse link que aparece no rodapé do texto de boas vindas na home. A outra opção é esse link do texto de boas vindas virar o "Ajuda". Mas aí vai ser um texto longo, acho que perde o sentido de um conteúdo com orientação mais rápida, intermediaria entre o paragrafo de boas vindas e os textos longos de Ajuda e Privacidade.

@luizapeixe o que acha?

**Comment by ricardopoppi** [comment]
Fechando essa issue pois a opção ver regras foi eliminada do app. a issue #29 cobre a demanda de conteúdos estáticos
