### ISSUE TITLE
Criar ícone para perfis de "benfeitores"

### ISSUE THREAD

**Issue by parrahenri** [unidoscontraacorrupcao/ej-server#280]
O cliente fez uma campanha de crowdfunding e prometeu que os doadores teriam um avatar diferente lá no app. Então precisamos criar um ícone de "medalha", "troféu" ou algo do tipo que apareça nos perfis que a gente assignar pelo admin, quase como aqueles perfis verificados de mídias sociais.

@luizapeixe formula algo porfa?

**Comment by parrahenri** [comment]
@ricardopoppi criada a de design

**Comment by luizapeixe** [comment]
Ok! Só pra entender melhor onde seria aplicado esse ícone... Seria um elemento aplicado em cima da foto de avatar? ou um troféu mesmo na área de badgets? Caso seja um badget, acho que valeria criar uma missão pra isso, pra manter a coerencia com os demais troféus. Caso seja um elemento sob a foto de avatar, vale bater com o pessoal de DEV a viabilidade disso.

Outra possível solução seria incorporar essa diferenciação ali no "Status do Participante", na página de perfil (logo abaixo do nome do user). Poderia ser algo tipo "Status do participante: Benfeitor(a) + ícone"

@ricardopoppi @danielhmarinho @davidCarlos

**Comment by parrahenri** [comment]
Em cima da foto do avatar (ou embaixo). Enfim, sobre a foto, como uma camada ou ícone igual esses que a gente bota na foto de perfil do face, sabe?

**Comment by luizapeixe** [comment]
Ok! Que tal essas opções:

![captura de tela 2018-09-19 as 16 05 42](https://user-images.githubusercontent.com/6249788/45775370-f4b34000-bc25-11e8-9c9b-2285935c21d4.png)

**Comment by luizapeixe** [comment]
Seguem mais opções seguindo a referencia de "medalha" sugerida pelo cliente

![captura de tela 2018-09-24 as 18 51 03](https://user-images.githubusercontent.com/6249788/45981358-1861f600-c02b-11e8-8276-9d852bc9d282.png)

reparem q em algumas opções estou sugerindo não só o ícone na foto mas também uma imagem discreta aplicada no fundo azul. Vale bater com a equipe de front se isso é possível

**Comment by ricardopoppi** [comment]
@parrahenri coloca no radar essa aprovação ao longo da semana para que ela seja uma issue de implementação da próxima semana

**Comment by parrahenri** [comment]
Eles querem a opção F!
_



+ 55 11 996 040 934
@parrahenri
Jundiaí – SP | Brasil
www.cidadedemocratica.org.br <http://www.cidadedemocratica.org.br/>

**Comment by luizapeixe** [comment]
ok! já adicionei os elementos no drive

badget: https://drive.google.com/open?id=1GDXsyGX1nstP3YA3-jgHF7MCuMJmph7H
madalha no fundo do backgroud: https://drive.google.com/open?id=1_zrQ3mGFNXJLB7y8-SMHLtRIErgtmL_4

**Comment by parrahenri** [comment]
@ricardopoppi já tem issue pra implementar esse "avatar"?

**Comment by ricardopoppi** [comment]
issue #302 aberta para implementação
