### ISSUE TITLE
Ajustar mensagem quote do compartilhamento dos cards vermelhos

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#281]
Issue emergencial, pois a campanha recebeu indicação de que a msg atual está contra a lei eleitoral. A nova msg quote do compartilharmento dos cards/interna vermelhos deve ser:

"\<nome-do-candidato\> não atestou passado limpo ou não se comprometeu. Vamos divulgar?"

**Comment by parrahenri** [comment]
+ Ajustar dos VERDES

Quem é contra corrupção e defende a democracia merece ser lembrado! <nome-do-candidato> tem uma candidatura comprometida. Saiba mais sobre ela aqui.
