### ISSUE TITLE
Opções do filtro visualizando aparecem pela metade em mobile

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#282]
Só aparecem as primeiras. Para replicar, abra as opções do filtro visualizando, quando em mobile

Print:

![photo_2018-09-21_15-25-07](https://user-images.githubusercontent.com/1162183/45899195-8d76c680-bdb2-11e8-9101-c254f7129870.jpg)

**Comment by danielhmarinho** [comment]
@ricardopoppi a ideia aqui é esconder a barra inferior quando filtro for aberto. Vou aplicar esse comportamento
