### ISSUE TITLE
Implementar nova ux do filtro com base nos critérios das cores

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#283]
Implementar a nova UX do filtro, conforme discussão abaixo. @luizapeixe pode subir as telas/assets? Não deixe de observar o meu ultimo comment: "Lembrando que o "não se comprometeu" tb é vermelho"

=========================================================
Esse ítem do filtro (visualizando) é onde está o core da campanha. É onde se filtra pelos critérios que determinam as cores dos cards. De certa forma, esse filtro não apresenta especificamente uma regra de cor, mas atualmente 4 criterios:
se comprometeu
não se comprometeu
não tem passado limpo
não respondeu

O não respondeu acabou ficando desnecessário. E o não se comprometeu e não tem passado limpo, são os vermelhos.

Será que a gente poderia simplificar esse filtro filtrando apenas em VERDES e VERMELHOS? Há uma perda aí que nem todo mundo está habituado a regra de cor. Mas se além de simplificar esse filtro, a gente pudesse apresentar ele de outra forma (sem ser dropdown, outra solução), será que a gente não resolve essa demanda de priorizar verdes e vermelhos apenas com essa simplificação e melhoria de UX desse filtro específico?

O que acham @luizapeixe @parrahenri?

**Comment by parrahenri** [comment]
mas tem "não se comprometeu" cinza tb, não?

**Comment by parrahenri** [comment]
Pergunto isso (comentário anterior) porque o compromisso se refere às novas medidas, mas não ao pacto da democracia. Então acaba tendo CINZA no "se comprometeu". Sendo assim, acho que o ideal é manter as 4 opções.

Mas tanto aí, quanto no filtro por partido tem problema de UX relatado. a caixa de opções fica difícil de manusear e, em alguns dispositivos, não dá pra ver todas as opções.

**Comment by davidCarlos** [comment]
Eu acho que funciona bem, e a complexidade de implementar é baixa. Posso iniciar essa tarefa amanhã.

**Comment by parrahenri** [comment]
Eu gostei!
