### ISSUE TITLE
Imagem do candidato não aparece nem em twitter nem e whatsapp (facebook e telegram está ok)

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#284]
Print twitter:

![captura de tela de 2018-09-22 14-26-42](https://user-images.githubusercontent.com/1162183/45920080-be6bff80-be75-11e8-83d2-ee366693bcbd.png)

Print whatsapp (mesmo esperando um tempo pra carregar a foto):

![captura de tela de 2018-09-22 14-34-38](https://user-images.githubusercontent.com/1162183/45920082-c88dfe00-be75-11e8-9dce-ff6cd6e627b1.png)

**Comment by ricardopoppi** [comment]
Prints dos que funcionaram:

FACEBOOK:

![captura de tela de 2018-09-22 14-27-00](https://user-images.githubusercontent.com/1162183/45920087-d80d4700-be75-11e8-9745-fa1e0cd6acbc.png)


TELEGRAM:

![photo_2018-09-22_14-44-16](https://user-images.githubusercontent.com/1162183/45920090-0723b880-be76-11e8-986d-9b186464cb9d.jpg)

**Comment by davidCarlos** [comment]
@ricardopoppi eu tinha te avisado que no whatsapp tem que esperar o whatsapp carregar a imagem antes de mandar a mensagem. Se enviar a mensagem antes do whatsapp puxar a meta tag da imagem, ela não vai aparecer na mensagem (Inclusive o compartilhamento que fiz com você no whatsapp tem a foto do candidato). Em relação ao whatsapp não tem muito o que fazer, o usuário tem que esperar a foto carregar, no twitter realmente não está funcionando. Vou atualizar o título da issue.
