### ISSUE TITLE
novo texto abertura

### ISSUE THREAD

**Issue by parrahenri** [unidoscontraacorrupcao/ej-server#285]
BOAS VINDAS!
Aqui você vê todas as candidatas e candidatos à Câmara dos Deputados e ao Senado e se eles têm:
1. PASSADO LIMPO;
2. Compromisso com DEMOCRACIA; e
3. Adesão às NOVAS MEDIDAS contra a Corrupção.
PESQUISE sobre os candidatos e use o botão ESTRELA para salvar suas preferências no SANTINHO digital.
Para dúvidas, acesse FAQ.

**Comment by parrahenri** [comment]
@ricardopoppi

**Comment by ricardopoppi** [comment]
fechando essa pois a #295 agrega as mudanças de conteúdo para quanto santinhos entrar em prod
