### ISSUE TITLE
atualizar texto FAQ

### ISSUE THREAD

**Issue by parrahenri** [unidoscontraacorrupcao/ej-server#286]
Atualizar com esses textos

COMO FUNCIONA A CAMPANHA?
NA PRIMEIRA FASE DA CAMPANHA, DIVULGAMOS AS NOVAS MEDIDAS CONTRA A CORRUPÇÃO E COMEÇAMOS A COLETAR ASSINATURAS DOS BRASILEIROS QUE APOIAM ESSA AGENDA.
NA SEGUNDA FASE, BUSCAMOS O COMPROMETIMENTO DE TODOS OS CANDIDATOS AO CONGRESSO NACIONAL PARA QUE TRABALHEM, CASO ELEITOS, DESDE O INÍCIO DO MANDATO PARA DISCUSSÃO E APROVAÇÃO DO PACOTE DE MEDIDAS.
NA TERCEIRA FASE, LANÇAMOS A PLATAFORMA ONLINE PARA QUE A SOCIEDADE POSSA CONHECER OS CANDIDATOS QUE SE COMPROMETERAM COM A CAMPANHA, PRESSIONAR AQUELES QUE AINDA NÃO TIVEREM ADERIDO E AJUDAR A ELEGER UM CONGRESSO QUE IMPLEMENTE E AVANCE COM AS PROPOSTAS DAS NOVAS MEDIDAS.
AGORA, TODAS AS PESSOAS QUE USAREM A PLATAFORMA PODERÃO PESQUISAR, FILTRAR E SELECIONAR OS NOMES DE SUA PREFERÊNCIA E GERAR SANTINHOS DIGITAIS (CARTÕES VIRTUAIS) COM AS INFORMAÇÕES IMPORTANTES PARA O DIA DA VOTAÇÃO.
 
COMO AS PESSOAS PODERÃO INTERAGIR? O PAPEL DA SOCIEDADE SE ENCERRA COM AS ELEIÇÕES?
EM SETEMBRO DE 2019, ERA PERMITIDO A ELEITORAS/ES CONSULTAR CANDIDATAS/OS NA PLATAFORMA ONLINE, VERIFICAR SEUS COMPROMISSOS ASSUMIDOS (OU NÃO), PESQUISAR E FILTRAR OS NOMES CONFORME OS CRITÉRIOS DA CAMPANHA, COMPARTILHAR AS INFORMAÇÕES COM AMIGOS E FAMILIARES E AINDA EXERCER PRESSÃO SOBRE AS/OS PRÓPRIAS/OS CANDIDATAS/OS PARA QUE SE COMPROMETESSEM.
NA SEMANA QUE ANTECEDE ÀS ELEIÇÕES, EM OUTUBRO, TODOS OS QUE NAVEGAM NA PLATAFORMA PODERÃO SELECIONAR E SALVAR SEUS NOMES FAVORITOS E AINDA GERAR SANTINHOS DIGITAIS (CARTÕES VIRTUAIS) COM TODAS AS INFORMAÇÕES IMPORTANTES PARA O DIA DA VOTAÇÃO. NESTA FASE, AS FUNÇÕES DE COMPARTILHAMENTO E PRESSÃO FICARÃO DESABILITADAS. 
DEPOIS DAS ELEIÇÕES, TODOS OS QUE SE CADASTRARAM NA PLATAFORMA ONLINE SERÃO INFORMADOS POR E-MAIL, REDES SOCIAIS E SITE DA CAMPANHA SOBRE O PASSO-A-PASSO DO ACOMPANHAMENTO E COBRANÇA DOS CANDIDATOS ELEITOS E O ENCAMINHAMENTO DAS NOVAS MEDIDAS CONTRA A CORRUPÇÃO NO CONGRESSO NACIONAL.

**Comment by parrahenri** [comment]
@ricardopoppi

**Comment by parrahenri** [comment]
1. Coloca como 2o. item, depois de "O que é a campanha"
2.  Sim, substitui totalmente

**Comment by ricardopoppi** [comment]
Fechando essa pois a issue #295 já agregou essa mudança tb
