### ISSUE TITLE
Colapsável cortando o texto na interna do candidato (motorola g5)

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#288]
Eu não consegui replicar. Porém recebemos esse relato (print). Será que é possivel agir preventivamente de forma que esse colapsavel se expanda qdo o texto não couber?

![whatsapp image 2018-09-23 at 18 43 55](https://user-images.githubusercontent.com/1162183/45933389-08321400-bf62-11e8-92e9-31499045949b.jpeg)

**Comment by danielhmarinho** [comment]
@ricardopoppi não tem como a gente prever o tamanho do conteúdo e ele expandir de acordo com conteúdo(Na verdade até podemos mas é um trabalho grande pra essa reta final). Podemos aumentar preventivamente o tamanho. O estranho é que é um tamanho fixo, não deveria quebrar em apenas um aparelho e em outros não

**Comment by danielhmarinho** [comment]
@ricardopoppi to achando que a quantidade de caracteres que ta vindo na planilha ta superior ao planejado

**Comment by ricardopoppi** [comment]
@danielhmarinho a quantidade de char está abaixo dos 500, eu verifiquei isso. O que parece é que alguns aparelhos aumentam a fonte por algum motivo, gerando esse corte

**Comment by danielhmarinho** [comment]
@ricardopoppi se o aparelho muda o tamanho da fonte isso é opção do navegador da pessoa, não temos muito como controlar isso. O padrão é 16 pixels de base, se o celular aumenta isso não temos muito como controlar. Uma medida preventiva é mudar a unidade em que a font é calculada. Pode funcionar

**Comment by ricardopoppi** [comment]
Se for simples, podemos ir por esse caminho sim, pode decidir vc. Lembrando que essa issue não merece mais que 30 minutos, já que recebemos apenas 1 report.

**Comment by ricardopoppi** [comment]
Ainda segue ocultando parte do texto em algumas larguras

**Comment by ricardopoppi** [comment]
@danielhmarinho @davidcarlos o caminho de resolução dessa issue passa a ser usarmos título e texto nas internas em vez de colapsaveis.

Aí já viria tudo aberto pro usuário rolar.

**Comment by danielhmarinho** [comment]
@ricardopoppi devemos esperar alguma tela da @luizapeixe ?

**Comment by ricardopoppi** [comment]
Não, pode implementar aproveitando os estilos do colapsável pro título e pro corpo do texto
