### ISSUE TITLE
Incluir dois ítens estáticos no menu lateral: "Ajuda" e "Privacidade"

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#29]
esse conteúdo deve ler da página estática /help/ e /privacy/ do backend django

**Comment by ricardopoppi** [comment]
Nesse primeiro momento podemos servir fora da api como estático no app. Peço ao @parrahenri indicar esses conteúdos

**Comment by parrahenri** [comment]
Sobre PRIVACIDADe a capanha já tem esse:

POLÍTICA DE PRIVACIDADE E TERMOS DE USO TRANSPARÊNCIA INTERNACIONAL BRASIL
A ASSOCIAÇÃO TRANSPARÊNCIA E INTEGRIDADE, conhecida como “Transparência Internacional Brasil”, é uma associação brasileira, sem fins lucrativos e de caráter filantrópico, inscrita sob CNPJ no 26.219.946/0001-37 e regulamentada de acordo com o Código Civil Brasileiro (artigos 44 a 69).

A Transparência Internacional Brasil se compromete com sua privacidade e seu conforto na internet. As informações nessa página tratam [1] dos dados que coletamos em suas visitas a este e os demais sites que gerenciamos; [2] dados pessoais informados por você à Transparência Internacional Brasil; [3] informações coletadas junto a empresas de enriquecimento e locação de dados; [4] e, principalmente, sobre nosso compromisso com sua privacidade e o sigilo dos seus dados.

Podemos atualizar estes termos sempre que for necessário, considerando, mas não se limitando, a contratação de novos serviços, evolução das tecnologias já utilizadas, mudanças em nossa Política de Doação e a legislação em vigor.

Ao utilizar esse e os demais sites gerenciados pela Transparência Internacional Brasil, realizar doações financeiras para a Transparência Internacional Brasil, participar de nossas ações de voluntariado ou consumir outros conteúdos gerados pela Transparência Internacional Brasil, você declara estar de acordo com nossos termos de uso e esta política de privacidade.

COLETA DE DADOS
Coletamos dados de acesso e utilização de nossos sites apenas para fins estatísticos. O uso de cookies e pixels de acompanhamento se destinam exclusivamente ao aperfeiçoamento de nossas ações de marketing e captação de recursos. Durante sua visita, não coletamos informações pessoais e dados particulares. Essas informações só são registradas em nossos bancos de dados quando você preenche um formulário e, espontaneamente, as fornece para a Transparência Internacional Brasil.

Podemos utilizar os serviços de enriquecimento e limpeza de banco de dados de empresas homologadas e com permissão legal para prestar este tipo de serviço. A captura de novas informações se destina exclusivamente à melhora no processo de comunicação entre a Transparência Internacional Brasil e você.

Da mesma forma, podemos alugar novas listas de fornecedores com autorização para utilizar seus dados – principalmente, mas não apenas, para envio de mala direta e e-mail marketing. Esses dados só ficarão armazenados nos bancos de dados da Transparência Internacional Brasil para que não sejam enviadas comunicações abusivas caso você não responda à primeira mensagem. A responsabilidade pela captura inicial de seus dados é da empresa fornecedora da lista e você poderá solicitar mais informações à Transparência Internacional Brasil a qualquer momento.

UTILIZAÇÃO DAS INFORMAÇÕES
Ao se cadastrar em uma lista da Transparência Internacional Brasil, podemos enviar e-mails, cartas e mensagens de texto (SMS) para fins de mobilização, divulgação e captação de recursos da própria Transparência Internacional Brasil ou de projetos que apoiamos.

Não enviaremos comunicações que não sejam relacionadas à Transparência Internacional Brasil, ações de combate à corrupção ou mensagens abusivas.

Todas as informações captadas durante seu acesso aos sites gerenciados pela Transparência Internacional Brasil, em ações de marketing e captação de recursos e eventos serão utilizadas apenas pela Transparência Internacional Brasil. Esses dados não serão, em hipótese alguma, vendidos, alugados ou cedidos a terceiros.

ENVIO DE MENSAGENS DE TEXTO (SMS)
A Transparência Internacional Brasil utiliza os serviços de envio de SMS marketing de empresas especializadas e que respeitam a legislação em vigor. Podemos entrar em contato por telefone ou por mensagem de texto de segunda a sexta-feira, das 09h às 20h e aos sábados, das 10h às 16h, exceto em feriados nacionais.

Ao se cadastrar em uma ficha de filiação da Transparência Internacional Brasil (https://doe.transparenciainternacional.org.br), você poderá receber uma mensagem de texto de confirmação em seu celular em até 30 minutos, mesmo fora do horário acima estipulado.

ACESSO AOS SEUS DADOS
Você pode solicitar uma cópia dos seus dados a qualquer momento, através do e-mail relacionamento@transparenciainternacional.org.br. No entanto, esses dados precisam ser solicitados por você e não serão entregues a parentes ou assessores/secretários.

SEGURANÇA DA INFORMAÇÃO
Todos os dados em poder da Transparência Internacional Brasil são armazenados em servidores seguros e criptografados, cujo acesso só é permitido a funcionários da Transparência Internacional Brasil capacitados a gerenciá-los com segurança ou fornecedores com contratos de confidencialidade.

Em todas as páginas em que informações financeiras possam ser transmitidas, um certificado de criptografia de alto nível estará instalado e homologado por uma empresa reconhecida para este fim (Thawte EV SSL CA- G3).

EXCLUSÃO DE DADOS
Você pode solicitar a exclusão do envio de mensagens a qualquer momento, clicando no link “descadastrar endereço” no rodapé de nossos e-mails, respondendo um SMS com a palavra “SAIR” ou entrando em contato com nosso Canal de Relacionamento com Doadores, através do e-mail relacionamento@transparenciainternacional.org.br.

REDES SOCIAIS
A Transparência Internacional Brasil está presente na seguinte rede social:

Facebook (https://www.facebook.com/
transparenciainternacional)

Acreditamos a liberdade de expressão que faz parte do processo para construirmos uma sociedade cada vez mais aberta e igual para todos. Por isso, não excluiremos comentários postados em redes sociais sobre os posicionamentos e ações da Transparência Internacional Brasil.

Apenas mensagens abusivas, de cunho comercial, com conteúdo impróprio, palavras de baixo calão, com ataques pessoais ou a grupos específicos serão excluídas e o usuário poderá ser banido de nossas páginas.

SITES GERENCIADOS PELA TRANSPARÊNCIA INTERNACIONAL BRASIL
Abaixo, a lista de sites gerenciados pela Transparência Internacional Brasil e representados por esta Política de Privacidade:

transparenciainternacional.org.br;
doe.transparenciainternacional.org.br;
novasmedidas.transparenciainternacional.org.br;
transparenciainternacional.com.br;
transparenciacorporativa.org.br;
trac.transparenciainternacional.org.br;
cmal.transparenciainternacional.org.br;
quemmoraaolado.org.br;
unidoscontraacorrupcao.org.br
GERAL
Política de Privacidade atualizada em 25/05/2018.

www.transparenciainternacional.org.br/politica-de-privacidade

**Comment by parrahenri** [comment]
O AJUDA pode servir pra uma espécie de FAQ e de infos sobre a campanha (e tiramos o Ver Regras)

Vou elaborar algo

**Comment by danielhmarinho** [comment]
Os dois itens foram adicionas a barra lateral e uma página para a política de privacidade foi criada no app. No aguardo do conteúdo da ajuda para fechara issue.

**Comment by ricardopoppi** [comment]
@danielhmarinho para PRIVACIDADE, o conteúdo é esse: https://github.com/unidoscontraacorrupcao/ej-server/issues/29#issuecomment-403849348

Para AJUDA, peço ao @parrahenri postar aqui o conteúdo validado pela Transparência Internacional

**Comment by danielhmarinho** [comment]
@ricardopoppi o conteúdo da parte de privacidade já está la. Assim que o ajuda for decidido subo a página estática e fecho a issue

**Comment by parrahenri** [comment]
@ricardopoppi 

Ajuda

O que é a campanha Unidos Contra a Corrupção?
A Campanha Unidos contra a Corrupção é uma ação para promover as Novas Medidas contra a Corrupção e para que eleitores e candidatos trabalhem juntos por um novo Congresso Nacional de 2019 comprometido com esta luta.  

Quem está responsável pela campanha?
O responsável pela campanha é uma coalizão de organizações sociais apartidárias e com longa trajetória de combate à corrupção no país, a saber, Contas Abertas, Instituto Cidade Democrática, Instituto Ethos, Movimento de Combate à Corrupção Eleitoral-MCCE, Observatório Social do Brasil e Transparência Internacional - Brasil. 

Quais as fases da campanha?
A campanha tem 3 fases. A primeira tem como objetivo divulgar as Novas Medidas e coletar assinaturas dos brasileiros e brasileiras que apoiam essa agenda! Depois, a segunda fase busca comprometer candidatos e candidatas, pedindo que se cadastrem na campanha e declarem seu compromisso contra a corrupção, sua defesa da democracia e seu passado limpo.

A terceira fase será o momento em que a sociedade poderá conhecer os candidatos e candidatas que se comprometeram com a campanha, pressionar aqueles que ainda não tiverem aderido e ajudar a eleger um Congresso que implemente e avance com essa agenda.

O que são as Novas Medidas?
Trata-se do maior pacote de medidas anticorrupção já produzido no mundo. Ele agrega 70 projetos de lei, propostas de emenda constitucional e resoluções administrativas para promover melhorias na capacidade de o Brasil enfrentar de maneira sistêmica o problema da corrupção. Esta resposta se reflete nas diferentes abordagens que compõem o pacote: prevenção, controle e participação social, educação, investidura de agentes públicos, transparência e acesso à informação, desburocratização, responsabilidade e democracia partidária, desenvolvimento institucional, integridade empresarial, detecção, investigação, sanção, articulação interinstitucional, cooperação internacional e recuperação de ativos. 

Por que este pacote foi desenvolvido?
Nenhum país no mundo conseguiu reduzir significativamente os índices de corrupção sem atuar de maneira sistêmica sobre o problema. O debate sobre a corrupção no Brasil vem sofrendo com a polarização política exacerbada e o foco limitado às operações de investigação e processos judiciais de grandes nomes nacionais. Logo, a atenção sobre as causas e soluções estruturais têm ficado à margem. Com esta iniciativa, desejamos trazer novamente o debate para respostas que possam contribuir para uma mudança de patamar significativa e duradoura no controle da corrupção no Brasil. 

Como se deu a construção coletiva das Novas Medidas?
No processo inicial de construção do pacote de medidas foram 373 instituições brasileiras. Este conjunto inédito de medidas foi levado à análise e adaptações das equipes da TI e da FGV Direito Rio e Direito SP, e contou com contribuições de 192 especialistas, redatores e revisores brasileiros(as), entre gestores(as) públicos(as) dos mais variados órgãos, sociedade civil, academia, integrantes do Judiciário e do Ministério Público, além de advogados(as). Em fevereiro deste ano, as 84 propostas finais foram colocadas em consulta pública através da plataforma colaborativa online Wikilegis, através da qual qualquer pessoa pode conhecer em detalhe cada uma das propostas, apoiar, comentar, criticar e sugerir alterações. Ao final da consulta, em abril, 379 sugestões de emenda de 912 cidadãos cadastrados na plataforma foram acolhidas e avaliadas pela TI e pela FGV Direito Rio e Direito SP. Deste modo, o grupo chegou à formatação final de 70 propostas e que pode ser encontrada em www.unidoscontraacorrupcao.org.br. 

Por que o pacote é chamado de "Novas Medidas"? Existe alguma relação com as "10 Medidas Contra a Corrupção"?
O pacote das “10 Medidas” foi uma importante iniciativa que almejou dar uma resposta sistêmica ao problema da corrupção. Ele teve o mérito de compilar e propor importantes reformas anticorrupção para o país, e coletou mais de dois milhões de assinaturas em seu apoio. Com isso, a campanha das “10 Medidas” chamou a atenção de parcela considerável da população para a necessidade de o país começar a construir respostas sistêmicas à corrupção. No entanto, o pacote também teve problemas e limitações. Algumas propostas foram consideradas por importantes segmentos da sociedade brasileira como excessivas e problemáticas. Houve desacordo e insatisfação com medidas que poderiam ter seu uso perigosamente deturpado (por exemplo, o teste de integridade de funcionários públicos) e outras que limitavam recursos da defesa de réus – atingindo não apenas aqueles de colarinho branco (historicamente impunes), mas também réus de crimes comuns que estão nas parcelas mais vulneráveis da população e cujas garantias básicas são sistematicamente ignoradas. Este foi um dos motivadores para que a TI liderasse este amplo projeto de construção coletiva de propostas, garantindo a participação da sociedade desde sua elaboração, que não somente buscasse atacar as causas estruturais da corrupção e promovesse a integridade no Brasil, mas também que o fizesse da forma mais representativa possível da multiplicidade de visões e interesses da sociedade brasileira.

**Comment by ricardopoppi** [comment]
@danielhmarinho qdo vc pegar essa issue, a entrada desse texto AJUDA sobrepõe o atual REGRAS que vai sair do app:

Vc pode:

- [ ] Retirar o "Ver regras" no final do cabeçalho de boas vindas na home do app (aquele texto rosa)
- [ ] Na  barra lateral (menu hamburger) substituir o atual "REGRAS" pelo "AJUDA" mantendo o mesmo estilo
- [ ] Ainda na barra lateral (menu hamburguer), incluir o "PRIVACIDADE" logo abaixo do "AJUDA", usando o mesmo estilo dele
