### ISSUE TITLE
Processar com filtro PB as novas fotos de candidatos

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#293]
@luizapeixe, há novas fotos na pasta para passar no filtro pb: https://drive.google.com/drive/folders/1hsjcp1FA9NMJgxXuh8EkLtG3UNzOKxym

**Comment by luizapeixe** [comment]
done!
arquivo zipado com nova leva PB aqui: https://drive.google.com/file/d/1QJbiOQxFZZGrwB2ueNemcN3VPfsL0M_j/view?usp=sharing

**Comment by ricardopoppi** [comment]
fotos importadas
