### ISSUE TITLE
[SANTINHOS] Quando o usuário sai da interna o filtro reseta sozinho

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#296]
Para replicar (em dev):

1) Configure o filtro pra uma UF específica (diferente da sua) e uma condição (não tem passado limpo, por ex)
2) Clique no nome ou foto de um card qq para entrar na interna
3) Clique no botão voltar
4) Observe que o filtro voltou pro default, causando uma quebra de UX

**Comment by danielhmarinho** [comment]
@ricardopoppi o problema aqui é apenas o estado que volta a ser configurado para a uf do usuário, vou pensar em alguma coisa que não de muito trabalho pra resolver. E isso não é um bug so de santinhos mas vou subir tudo no mesmo pacote

**Comment by ricardopoppi** [comment]
ok, combinado
