### ISSUE TITLE
Adiantando reflexão sobre o app estar com 3 abas nas fase SANTINHOS

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#298]
@luizapeixe @parrahenri abrindo essa reflexão aqui: a funcionalidade de santinhos vem responder uma angustia da campanha de focar a interação nessa ultima semana. por isso nessa versão o usuário não terá acesso a missões e a apenas uma interação nos cards: santinho

como o jogo já estava em curso, tivemos dificuldade sobre o que fazer com a coluna selecionados. todo mundo que tivesse card lá, deixaria de ter acesso se simplesmente removêssemos essa coluna. a solução implementada foi: se o usuário tem cards lá, a coluna segue aparecendo, se não tem a coluna some (já que não haveria mais a possibilidade de selecionar ngn).

já que nessa versão, o detalhamento dos cards (os famosos colapsáveis) serão acessíveis nas internas via um clique (na aba todos e santinhos) e também no botão "ver detalhes" na aba santinhos, ter cards na coluna selecionados não servirá mais pra nada. Então minha pergunta pra vocês é: 

NÃO SERIA MELHOR RESETARMOS TODOS OS SELECIONADOS QUANDO ESSA VERSÃO ENTRAR?

**Comment by parrahenri** [comment]
perguntas:

se a gente zerar pressionados e selecionados perderemos esses metadados? Tem como reverter isso depois? Ou seja, recompor BD com esses dados depois das eleições e retornar os selecionados e pressionados aos seus usuários?

**Comment by ricardopoppi** [comment]
pressionados a gente não precisa zerar, pois eles aparecerão na aba todos. seria só os selecionados mesmo

recompor BD até dá, mas é trabalhoso e arriscado. se a gente tomar essa decisão, estaríamos matando a interação selecionados para a próxima fase

**Comment by parrahenri** [comment]
nesse sentido acho melhor não zerarmos, por motivos que nem previmos ainda. (eventuais usos futuros). à exemplo do pressionados, não podemos devolver os selecionados pra TODOS e ocultar o SELECIONADOS?

**Comment by luizapeixe** [comment]
também tendo a votar em NÃO resetar. Isso pq, pensando pela experiência do usuário, parece frustrante que ele tenha investido tempo criando sua seleção de candidatos e de repente esse recurso sume sem aviso prévio. Acho que se for necessário tirar a aba SELECIONADOS, poderíamos pensar em deixar o acesso pra essa sessão em outro lugar, no menu-hamburguer por exemplo

**Comment by ricardopoppi** [comment]
@danielhmarinho @davidCarlos uma consulta sobre isso: podemos provisoriamente não filtrar os selecionados na aba TODOS e simplesmente ocultar a aba selecionados em qq condição? (hj ela é oculta apenas para os que tem selecionados = 0)

**Comment by ricardopoppi** [comment]
@davidCarlos @danielhmarinho @parrahenri @luizapeixe 

Mapeei as seguintes possibilidades:
(1) Remover os selecionados. Nesse caso, pela implementação da funcionalidade santinhos de não exibir a aba selecionados quando o número de selecionados é igual a 0, resolveria a questão. Ponto negativo: pessoas que engajaram no jogo e fizeram sua curadoria terão todo seu trabalho perdido;
(2) Passar a exibir os SELECIONADOS na aba todos e simplesmente forçar o ocultamento da aba. Já vamos fazer isso com os pressionados (como parte da issue santinhos) então faríamos o mesmo, "devolvendo a aba para os usuários após as eleições. Ponto negativo: complexidade técnica de ter que mexer na  API e estranhamento daqueles que já são usuários do app, para os quais a aba simplesmente sumiria sem avisar
(3) Deixar como está e confiar que a não existencia da aba para os novos usuários já é suficiente para fins de simplificação e que as 3 abas não é uma poluição tão grande para os usuários que já se cadastraram e selecionaram candidatos.

**Comment by ricardopoppi** [comment]
fechando essa pois optamos pela opção 2 já transformada em issue #301
