### ISSUE TITLE
[SANTINHOS] Quando usuario clica na aba TODOS botão santinho da navbar e hamburguer para de funcionar

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#299]
Para replicar:

1) Faça login
2) Clique no botão santinho da navbar ou hamburguer
3) Clique no título da aba "TODOS"
4) Tente clicar novamente no botão santinho da navbar ou hamburguer

**Comment by danielhmarinho** [comment]
@ricardopoppi a navbar nessa caso de desktop mas p bug é reproduzido no celular? (ela sumir ja vai ser corrigido em desktop_

**Comment by danielhmarinho** [comment]
@ricardopoppi consegui reproduzir aqui
