### ISSUE TITLE
[SANTINHOS] Interna dos candidatos não reflete a condição SANTINHO

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#300]
Ao acessar a interna de um candidato, tanto na aba TODOS quanto SANTINHO, ela não exibe o botão "salvar como santinho" ou "desfazer santinho"

**Comment by ricardopoppi** [comment]
@danielhmarinho não entendi a complexidade. Atualmente a interna não exibe nenhum botão, ela só teria que exibir um único botão com apenas dois estados: "Salvar como Santinho" ou "Desfazer Santinho". É isso?

**Comment by danielhmarinho** [comment]
@ricardopoppi não é nem complexo, apenas é uma issue um pouco grande , mas como as outras são pequenas acho que da pra encaixar sem problemas

**Comment by ricardopoppi** [comment]
isso, o coerente é o botão aparecer para os deslogados tb
