### ISSUE TITLE
Pesquisar se é possível aplicar atributos de cores nas fotos lidas nas metatags pelo facebook, whatsapp etc

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#307]
Hoje a foto é compartilhada PB. Seria um grande valor para o negócio se ela pudesse ser compartilhada com a cor do filtro atribuído pela campanha.

**Comment by davidCarlos** [comment]
Pela minha pesquisa não é possível aplicar css em meta tags.
