### ISSUE TITLE
Melhorar a indicação do "editar perfil" na aba de infos do perfil de usuário

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#31]
acho que acho vale repetir a apresentação do recursos de edição com um link “editar perfil” na própria aba de INFOS. Solução que usamos também no EJ genérico. peço a @luizapeixe fazer uma proposta disso no wireframe dessa tela

**Comment by luizapeixe** [comment]
aí vai a aba INFOS do Perfil com botão de edit tb no fim da página: https://invis.io/T6MSGEIK34F#/303032453_Perfil_1

**Comment by ricardopoppi** [comment]
Ok, issue #38 aberta pra implementação
