### ISSUE TITLE
Investigar dois casos de usuários que reclamaram de ter seus nomes de usuário trocados

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#310]
Tivemos dois relatos:

1) Email: cassiocarlos@hotmail.com
Nome real do usuário: Cassio Cechinel
Nome que apareceu trocado na plataforma: "Guilherme Rodrigues"

Print
![whatsapp image 2018-10-02 at 16 10 23](https://user-images.githubusercontent.com/1162183/46409171-ec113e00-c6ea-11e8-994c-6be3186df439.jpeg)

2) Email: nanainterativa@hotmail.com
Nome real do usuário: (não sabemos)
Nome que apareceu trocado na plataforma: "bar Cauã da Rocha"

Print
![whatsapp image 2018-10-03 at 08 43 00](https://user-images.githubusercontent.com/1162183/46409180-f3d0e280-c6ea-11e8-8e3c-42ffbddebeb8.jpeg)

**Comment by davidCarlos** [comment]
Removi todos os display_name que começavam com 'bar' para não haver estranhamento por parte do usuário. Isso se deu provavelmente devido a mudanças no ej, que no começo do projeto gerava nomes randômicos para os usuários cadastrados.
