### ISSUE TITLE
[GUERRILHA] Ajustes de regra do verde e exibição dos critérios pra reta final

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#311]
- [x] 1) criterio de verdes passa a considerar apenas passado limpo = SIM e novas medidas = SIM

- [x] 2) qdo democracia = "SEM RESPOSTA" e os outros dois itens forem = SIM, exibe nessa cor da foto acima (rosa/vermelho). Quando tudo for SIM, exibe todos os SIM em verde. Nos cards cinzas, onde tudo é SEM RESPOSTA, exibe tudo branco

- [x] 3) filtro default passa a ser verde, junto com UF

**Comment by ricardopoppi** [comment]
@luizapeixe qual o hexa da cor rosa e da verde do texto?

**Comment by luizapeixe** [comment]
> @luizapeixe qual o hexa da cor rosa e da verde do texto?

rosa: #E6007E nosso rosa institucional da identidade
verde: #32CEA6 o mesmo verde usado no filtro sob a foto dos candidates verdes
