### ISSUE TITLE
Como prevenir que o drop de UF não apareça comprimido?

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#312]
Recebemos dois reports desse tipo de comportamento do drop de UF, de dois lugares diferentes. Pelo que pude observar não tem a ver com o comprimento da tela.

Há algo a ser feito pra prevenir isso? @luizapeixe @davidcarlos

![whatsapp image 2018-10-03 at 18 20 21 1](https://user-images.githubusercontent.com/1162183/46444588-0bd74f00-c749-11e8-863d-ee1066f1f426.jpeg)

![whatsapp image 2018-10-03 at 20 15 00](https://user-images.githubusercontent.com/1162183/46444663-5a84e900-c749-11e8-83e9-cd06ca472b13.jpeg)

**Comment by luizapeixe** [comment]
pra mim apareceu encolhido logo que entrei no app e já fui direto clicar no drop de UF. Segundos depois fiz de novo e apareceu normal. Será q não pode ter sido o caso da pessoa ter clicado antes de ter terminado de carregar a página completamente? (pergunta de gente meio leiga :P )

**Comment by davidCarlos** [comment]
Provavelmente foi um problema de conexão, em que o componente não terminou de carregar e o usuário tentou realizar uma ação. Não temos muito o que fazer.
