### ISSUE TITLE
Cadastro por email quebrado em prod

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#313]
Qq email no cadastro em prod dá erro de formulario e msg como se email não tivesse cadastrado

![captura de tela de 2018-10-03 21-14-56](https://user-images.githubusercontent.com/1162183/46446245-9cb22880-c751-11e8-840e-ece94be22150.png)

**Comment by davidCarlos** [comment]
Problemas de restrição no mailgun. Email de cadastro desabilitado em prod.
