### ISSUE TITLE
Caixas de seleção no perfil se sobrepondo

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#32]
As caixas de seleção no perfil se sobrepõem quando abertas e não rolam todas as opções disponíveis. Veja imagem:

![captura de tela de 2018-07-08 14-03-51](https://user-images.githubusercontent.com/1162183/42422182-0c36b948-82b8-11e8-9835-b8f22ea0ef65.png)

**Comment by danielhmarinho** [comment]
Resolvido o problema com web-animations e o comportamento agora esta correto. Sem esta correção a edição do perfil ficaria comprometida, já que a seleção da opção e o fechamento do dropdown dependem do animations.
