### ISSUE TITLE
Fazer ajustes nos campos do perfil do usuário

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#33]
- [x] Opções default de "identidade de genero" e "Cor / raça" devem ser "Não informado". Hoje consta como "Não definido" e isso pode ter outra interpretação
- [x] Retirar as opções "movimento ou partido" e "mini bio"
- [x] Incluir opção de "Telefone/Whatsapp"
- [x] Incluir opção de "Idade"

**Comment by parrahenri** [comment]
Incluir IDADE @davidCarlos

**Comment by danielhmarinho** [comment]
@ricardopoppi na hora da recuperação do perfil já mudamos para não informado, mas na caixa de seleção na edição de perfil a opção se mantém "não definido" ou mudamos também para "não informado" ?
![selecao_015](https://user-images.githubusercontent.com/3606884/42526354-f1c66cbc-844b-11e8-8c55-025d946a5c41.png)

**Comment by ricardopoppi** [comment]
@danielhmarinho pode padronizar tudo como "Não informado", tanto na recuperação, quanto na edição
