### ISSUE TITLE
Criar as regras de negócio da exportação dos dados do besouro para uso em plataformas externas

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#35]
Para uso em RD Station etc

**Comment by parrahenri** [comment]
já pensou algo sobre isso?

**Comment by ricardopoppi** [comment]
Iniciei uma modelagem pros dados de missões, aqui: 
https://docs.google.com/spreadsheets/d/14mmr9jdwuQOSc1_Z4rusU9QO55lnvvlR5SAEaLXEcjA/edit#gid=0

Para os dados de conversa, temos o modelo do report do EJ: https://drive.google.com/file/d/1Wjqa0lwdsNK4zGMrOCcIJmhBavfczYDy/view?usp=sharing

**Comment by ricardopoppi** [comment]
Modelagem final

Planilha de usuários
Nome
Email
Cidade
UF
Genero
Raça
Tel/whatsapp
Idade
Missões aceitas
Missões concluídas 
Candidatos Selecionados
Candidatos Favoritados 
Candidatos Pressionados 
Candidatos Compartilhados 


Planilha de candidatos
ID (CPF)
Nome urna
UF
Passado limpo
Pacto/Democracia
Novas medidas
Num vezes Favoritados
Num vezes Selecionados 
Num vezes Pressionados
Num vezes Compartilhados
Num vezes Ignorados
Mudou status?
