### ISSUE TITLE
Botão "DIVULGUE" do menu lateral não está compartilhando a url da campanha

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#36]
Comportamento esperado era abrir o modal de compartilhamento, usando a url da campanha: 

"Conheça as Novas Medidas Contra a Corrupção e faça parte da maior união anticorrupção que o país já viu #UnidosContraaCorrupção" http://unidoscontraacorrupcao.org.br/

**Comment by danielhmarinho** [comment]
@ricardopoppi existe mais alguma coisa a ser compartilhada além do link? Algum titulo ou descrição?

**Comment by ricardopoppi** [comment]
@danielhmarinho sim! Puxa, falha minha, esse conteúdo já existe esqueci de colocar ele aqui. 

Vai esse texto junto: "Conheça as Novas Medidas Contra a Corrupção e faça parte da maior união anticorrupção que o país já viu #UnidosContraaCorrupção"  http://unidoscontraacorrupcao.org.br/
