### ISSUE TITLE
Formular regra de negócio para o módulo de gerenciamento de candidatos (fase 3)

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#39]
Versão desktop mostrar o máximo de candidatos por vez
Inspiração: site 342

----
Informações do CARD RESUMIDO: 
- Número de Urna,
- Nome, 
- Partido, 
- UF, 
- Cargo que disputa, 
- Tem passado limpo? S/N; 
- Comprometeu-se com Democracia? S/N; 
- Aderiu às Novas Medidas? Parcialmente/Totalmente/N

----
Cor default: preto e branco/ cinza
Se aderiu às novas medidas (adesão aceita a partir de formulário e análise das justificativas): card fica amarelo
Se não aderir, ainda que tenha SIM para os outros campos continua preto e branco
Se além disso tem SIM para os outros dois campos, fica verde.
Para ter verde precisa dos 3 campos aceitos
-----

**Problema a ser solucionado nas duas versões (mobile e desk): teremos milhares de candidatos (cards)**

Precisaremos de barra de busca por nome, filho UF e filtro Partido para facilitar aos eleitores.

No entanto, temos de solucionar esse problema pensando na primeira visualização (sem filtros marcados), por exemplo. No máximo dá pra deixar o filtro UF desde o início, a partir do cadastro da pessoa/ geo de seu cel. Os outros são feitos por opção do participante.

- temos de mostrar todos de maneira aleatória
- temos de mostrar tanto os em verde/ amarelo quanto os em pb (para desgastá-los e estimular que tentem mudar sua cor)

O número elevado faz com que cada vez mais a gente pense que o ideal é receber infos dos participantes (UF, partidos que tem interesse, cidade em que mora etc) para tentar reduzir a quantidade de infos e evitar que o sistema apresente candidatos com os quais ele não quer interagir.

**Comment by parrahenri** [comment]
@ricardopoppi feito

**Comment by ricardopoppi** [comment]
colando o comentário da @luizapeixe da issue de notificações pra cá, onde essa discussão deve ser desenvolvida (cc @parrahenri )

----------
exato, @parrahenri. o desafio é justamente desviar desse padrão automático sistêmico da gravata e da virilidade como sinônimo de política hehehe :P

Seguem algumas idéias:

![captura de tela 2018-07-13 as 14 07 42](https://user-images.githubusercontent.com/6249788/42704471-4d0b181e-86a6-11e8-882e-f5300edf94ab.png)

**Comment by luizapeixe** [comment]
Ata do papo 16/07 - 8h30:

-> objetivo das telas: 
pressionar candidates e engajar eleitores (debutados federais e senadores)

-> cronograma: 
entrega da fase 2: dia 25
implementação da fase 2 começa dia 26
deadline ideal pra entrega das telas da fase 3: dia 25

-> itens do card na lista default:
	•	Número de Urna,
	•	Nome,
	•	Partido,
	•	UF,
	•	Cargo que disputa,
	•	Tem passado limpo? S/N;
	•	Comprometeu-se com Democracia? S/N;
	•	Aderiu às Novas Medidas? Parcialmente/Totalmente/N


### - pagina inicial com card resumido (estimulo de velocidade)
	- se comprometeu: verde
	- se comprometeu parcialmente: amarelo
	- não se comprometei: PB
	- filtros que facilitem que users cheguem nos conteúdos q eles querem chegar ( !!! )
		- deputado ou senador?
		- campo de busca (por nome)
		- quero ver quem NÃO se comprometeu (filtro por cores)
		- partido
		- cidade (por default já entra filtrado na cidade da pessoa)

### - página de coleção de curtidos de candidates curtidos ( - velocidade e + aprofundamento)
	- na coleção o user pode favoritar candidates
	- card apresenta mais infos + botão de “ver mais”

### - galeria de favoritados
	- card ultra enxuto
	- botão de ver detalhes
	- botão desfavoritar
	- maior destaque pro número de urna

**Comment by parrahenri** [comment]
Dados possíveis pro card completo! c/c: @luizapeixe 

Dados de redes sociais:
Perfis no Twitter, Facebook, Instagram e Youtube

Dados do TSE:
Nome completo, nome de urna, CPF, grau de instrução, ocupação, lista de bens, certidões (certidão negativas, de que não há condenações criminais), votações em eleições anteriores (quando houver) e distribuição dos votos por município em eleições anteriores

Dados da Receita Federal
Empresas que fizeram doações ao candidato em eleições anteriores  (TSE) e quadro societário deles
Quadro societário das empresas constantes em sua lista de bens (lista autodeclarada pelo candidato ao TSE e disponibilizada por esse Tribunal)
Dados do STF
Inquéritos e ações penais em andamento (caso tenha prerrogativa de foro)

Dados da Câmara dos Deputados e do Senado Federal
Atividade parlamentar: projetos de lei apresentados, projetos de lei aprovados, frequência em sessões plenárias, frequencia em comissões, uso de verbas de gabinete

Dados dos Tribunais de Contas (da União -- TCU -- e dos Estados -- TCEs)
Contas rejeitadas por irregularidades durante o exercício na administração pública (por lei, os Tribunais de Contas devem enviar à Justiça Eleitoral, em ano de eleições, uma relação de gestores públicos, ocupantes de cargos ou funções com contas rejeitadas - esses dados ajudam a Justiça Eleitoral a analisar se defere a candidatura ou não)

**Comment by luizapeixe** [comment]
Subi agora no invision uma primeira proposta pra esses layouts!

• Lista geral: 
https://invis.io/AMKSPGK26WN#/309939624_Mobile_Portrait_Candidates_Todes

• Lista de aprovados: 
https://invis.io/AMKSPGK26WN#/309939623_Mobile_Portrait_Candidates_Aprovades

• Lista de favoritos: 
https://invis.io/AMKSPGK26WN#/309939622_Mobile_Portrait_Candidates_Favorites

No card, aproveitei o máximo do que já foi desenvolvido para o card das missões e estabeleci uma ordem nas infos exibidas para que os diferentes tipos de card mantenham unidade entre si e também otimizar o processo da implementação. A ordem de prioridade foi:

1. nome
2. : 2a. candidatura; 2b. urna; 2c. partido
3. foto
4. botões de ação do card
5. : 5a. ficha limpa; 5b. comprometimento; 5c. adesão às medidas
6. redes sociais
7. dados todos

Essa ordem soa ok pra vocês?

Na área dos 7. Dados todos (ver [aba Aprovados](https://invis.io/AMKSPGK26WN#/309939623_Mobile_Portrait_Candidates_Aprovades)), desenhei apenas a opção "Dados do TSE" mas as outras opções devem seguir a mesma estrutura. A gente aprovando esse estilo, eu diagramo as outras opções também.

Sobre a aplicação das cores, estou atribuindo elas em 3 momentos: na área 5. respondendo as perguntas (sim-verde, não-cinza, parcialmente-amarelo); na área 4. com aprovar (verde) e reprovar (amarelo) os candidatos e na área 3. como um filtro colorido com 50% de opacidade para informar que o candidate foi aprovado ou reprovado, combinando com o botões (estamos usamos a mesma solução - filtro 50% opacidade - nos cards das missões aceitas, bloqueadas e expiradas). Essa lógica de aplicação das cores faz sentido pra vocês?

Sobre o filtro de busca com diferentes campos, vejam na [aba APROVADES](https://invis.io/AMKSPGK26WN#/309939623_Mobile_Portrait_Candidates_Aprovades). 

Sobre nomenclaturas, é interessante que a gente pense em nomenclaturas inclusivas. No momento estou usando TODES, APROVADES e FAVORITES nas abas, mas essa solução soa estranho para algumas pessoas... O que vocês acham? Estou aberta a sugestões! Talvez GERAL, APROVAÇÕES e SELEÇÃO... algo assim, não sei. 

Sobre a Navbar, já apliquei alguns estudos alí pra gente já ir visualizando como reestruturar a Navbar considerando as novas funcionalidades, vejam:

![captura de tela 2018-07-20 as 11 32 49](https://user-images.githubusercontent.com/6249788/43008176-afa10d5c-8c10-11e8-9712-65d933b4d2e6.png)

**Comment by parrahenri** [comment]
Luiza, podemos testar invertendo os dados do candidato (cargo, partido etc) pelos 3 compromissos? Só pra termos duas opções na hora de apresentar.

Sobre a aplicação das cores:

1) O primeiro card tem SIM, NAO e PARCIAL. Deveria ser todo amarelo não?
2) O segundo card tem SIM, NAO e NAO. Deveria ser todo cinza, certo?

Por ajustar isso para levarmos na quarta?

Já temos as telas que aparecem quando eu APROVO/ REPROVO?

Uma observação: tanto esses dois botões, quanto os 3 marcadores de compromisso estão com moldura retangulares/ quadradas. Não dá pra testar algo que diferencia os dois? Talvez só os ícones de polegar já sejam o bastante?

ABA APROVADES

Pq o filtro só aparece aqui? Deveria já aparecer na home.

O que eu não comentei é porque curti! :))

**Comment by parrahenri** [comment]
Sobre navbar, prefiro a 2

**Comment by luizapeixe** [comment]
respondendo ao @parrahenri :

Luiza, podemos testar invertendo os dados do candidato (cargo, partido etc) pelos 3 compromissos? Só pra termos duas opções na hora de apresentar.
- Sim! Porém vale lembrar que se a gente descer as infos de Candidatura, Urna e Partido, elas não aparecerão na aba de FAVORITES, já que o card é mais curto e mostra apenas até a foto da pessoa. Nesse caso deveríamos considerar alongar um pouco mais o card nessa aba pra incluir essas infos também.

Sobre a aplicação das cores:
1) O primeiro card tem SIM, NAO e PARCIAL. Deveria ser todo amarelo não?
2) O segundo card tem SIM, NAO e NAO. Deveria ser todo cinza, certo?
- no caso, a ideia do filtro amarelo ou verde em cima da foto é pra indicar quando o USUÁRIO aprova ou reprova o candidato, ou seja, o filtro não é atribuído automaticamente a partir das respostas das três perguntas ali. Minha ideia é que, por default, todos os cards aparecem coloridos (sem filtro nenhum) e só ganham o filtro qnd o user clica para aprovar ou reprovar. Faz sentido pra vcs assim?

Por ajustar isso para levarmos na quarta?
- sim! que horas será na quarta? lá no mesmo coworking, né?

Já temos as telas que aparecem quando eu APROVO/ REPROVO?
- ainda não. vou criar. Será um splash? ou um toast? Acho que se o objetivo da Aba Todes é agilidade, podemos resolver com um Toast, né?

Uma observação: tanto esses dois botões, quanto os 3 marcadores de compromisso estão com moldura retangulares/ quadradas. Não dá pra testar algo que diferencia os dois? Talvez só os ícones de polegar já sejam o bastante?
- ok! vou pensar numa solução pra diferenciar eles

ABA APROVADES
Pq o filtro só aparece aqui? Deveria já aparecer na home.
- o filtro na verdade é retrátil, ele é exibido e ocultado pela seta " \/ " no canto direito da aba de filtro. É que só na tela da aba Aprovades q eu exemplifiquei ele aberto, mas na real ele estará presente nas três telas

Estou produzindo aqui e aviso aqui quando subir novidades no invision.

**Comment by parrahenri** [comment]
@luizapeixe sobre o primeiro ponto: manda ver! acho que vale testarmos dos dois jeitos.

Sobre esse: no caso, a ideia do filtro amarelo ou verde em cima da foto é pra indicar quando o USUÁRIO aprova ou reprova o candidato, ou seja, o filtro não é atribuído automaticamente a partir das respostas das três perguntas ali. Minha ideia é que, por default, todos os cards aparecem coloridos (sem filtro nenhum) e só ganham o filtro qnd o user clica para aprovar ou reprovar. Faz sentido pra vcs assim?

-> TI pediu especificamente que o card apareça todo em cinza, todo em amarelo ou todo em verde. Nesse caso teremos de ficar na especificação do cliente msm se não pode gerar ruído pelo menos nessa primeira apresentação.

Sobre quarta: sim, no mesmo. 13hs ou 13h30! A confirmar!

Qual a diferença entre splash e toast?

**Comment by luizapeixe** [comment]
Sobre a questão dos filtros amarelo / verde / PB, fiquei com uma dúvida... então a ideia é que o filtro sob a foto seja mesmo via algoritmo, determinando uma média entre as respostas para Ficha Limpa, Comprometimento e Adesão? Ou o user poderá votar em três opções tipo Aprovado, Reprovado e Parcial?

Sobre splash VS toast, [splash](https://invis.io/AMKSPGK26WN#/305653432_Mobile_Portrait_Splash_Missa-o_Aceita) é aquela tela que abre tipo light box e [toast](https://github.com/unidoscontraacorrupcao/ej-server/issues/72) é tipo um aviso que sobe na parte inferior do layout

Acabei de subir as OP2s

todes - https://invis.io/AMKSPGK26WN#/310329942_Candidates_Todes_Op2
aprovades - https://invis.io/AMKSPGK26WN#/310329941_Candidates_Aprovades_Op2
favorites - https://invis.io/AMKSPGK26WN#/310329940_Candidates_Favorites_Op2

**Comment by parrahenri** [comment]
@luizapeixe a cor será lida do BD. Ou seja, teremos um banco de dados com cada candidato e as três colunas dizendo sim/não. E aquela regra de negócio que expliquei automatiza a cor que reflete no card todo.

O user não vota nisso, nem nas 3 opções. (temos sim que prever uma tela especial pro candidato se cadastrar e se comprometer, mas é outra tela).

O user vota se ele "gostei e quero conhecer mais" ou "não gostei porque ainda não se comprometeu"

**Comment by parrahenri** [comment]
Já temos as telas que aparecem quando eu APROVO/ REPROVO?
ainda não. vou criar. Será um splash? ou um toast? Acho que se o objetivo da Aba Todes é agilidade, podemos resolver com um Toast, né?


Lembra que chegamos a falar que talvez fosse até um item pra ficar no Navbar? Porque cada um que eu digo sim me envia automaticamente uma MSG. E todo mundo que eu digo não recebe uma MSG minha e se muda de posição e se compromete, eu recebo uma MSG. Então se isso fica dentro da página de notificações, talvez se perca.

Temos de avaliar:

- se vale ser dentro das notificações
- se merece uma página específica

**Comment by parrahenri** [comment]
Por fim, sobre OP2s: Achei que a primeira versão ficou melhor. E vc?

**Comment by luizapeixe** [comment]
Sobre os filtros coloridos: Ok! Entendi. Repensei aqui e, considerando também os audios que trocamos no telegram, atualize as telas da OP1 e da OP2.

Sobre cores nos botões de APROVAR e REPROVAR, acho importante os botões terem uma cor de background até para dar mais leitura aos botões. Na OP1 estou exemplificando usando as cores roxo e azul (como você já viu) e na OP2 estou usando apenas branco e roxo, economizando uma cor e usando dos contrastes para diferenciar um botão do outro.

Sobre o toast de comprovação de votação, que tal algo assim:
![captura de tela 2018-07-23 as 19 36 12](https://user-images.githubusercontent.com/6249788/43106608-bcf2e312-8eaf-11e8-8625-7568fd68bbaa.png)
Repare que eu adicionei números nas abas APROVADES e FAVORITES, na OP1 eles estão em rosa e na OP2 estão em azul, para gente ver as opções e selecionar a mais interessante.

Outras diferenças sutis entre a OP1 e a OP2 são:
- que na OP1 o nome dos candidatos aparece alinhado à esquerda e na OP2 estão centralizados
- na aba APROVADES, o botão de "conheça mais" é bem destacado na OP1 e mais discreto na OP2

**Comment by parrahenri** [comment]
Boa! Da minha parte acho que tá tudo considerado né? Poppi tem sugestões?
Luiza, importante você:

- preparar uma apresentação dessas telas pro dia, explicando a criação

**Comment by luizapeixe** [comment]
ok! atualizei em cima dos seus comentários, @parrahenri :)

**Comment by ricardopoppi** [comment]
Gente, comentando aqui pra vcs terem esse contexto amanhã. Não tenho expectativa de atualizações sobre isso antes da oficina ok?

@luizapeixe @henrique meus comentários gerais sobre complexidade:
1) O mecanismo de exibição (front) me parece que não requer grandes complexidades, mesmo na ficha completa da aba de "aprovades" já que os estilos são padronizados e os dados virão organizados em planilhas;
2) Creio que essa solução também tem a vantagem de ser adaptável para desktop pois vai bastar fazer uma organização dos cards aproveitando a largura da tela, sem grandes reformulações visuais extras;
3) Creio que será importante a criação de um tour para o aprovar/reprovar, principalmente em função do que significa esse ato. Estou aprovando/reprovando com base em que? O que acontece com o candidato qdo eu aprovo ou reprovo? O tour resolveria coisas assim, acredito;
4) As opções de filtros creio que são viáveis, podemos até avaliar o uso de auto-complete no nome e cidade/estado;
5) Me preocupa um pouco o que virá nos links "conheça mais" ou "ver detalhes" pois acho que foge um pouco do escopo do app ficar apresentando telas detalhadas tanto pelo esforço de concepção do dataviz quanto pela implementação no front mobile;
6) Como nem todos os usuários cadastrados terão preenchido suas informações geo, é fundamental prever um splash/toast/whatever que peça isso ao usuário no primeiro acesso da área de candidatos. Sem essa informação a interação com os candidatos trará praticamente valor zero ao usuário;
7) Um desafio de back é qual o critério/algoritmo que utilizaremos para priorizar a carga dos cards. É fundamental concebermos isso. Ex:
(i) De cara aparecem só os candidatos do Estado (ainda é muita gente, então seriam exibidos de forma aleatória? / ou priorizariamos pela cidade, pra fazer um recorte mais específico? / e quando não houver candidatos da cidade, volta pra estado?)
(ii) Quando o usuário aprova algum candidato, usaremos algum metadado dele nessa priorização de exibição? ex: partido? 
(iii) Pela natureza do escopo do app (comprometimento da classe política em prol das novas medidas), talvez seja interessante priorizar candidatos que não se comprometeram, numa tentativa de induzir os usuários a pressionar para que o façam, reprovando-os
(iv) Esse ítem 7 requer um debate só pra ele. Apenas adiantei algumas possibilidades, nem todas serão viáveis de desenvolver no prazo da v3, por isso teremos que ser bem eficientes nessa defnição

**Comment by luizapeixe** [comment]
Na reunião de apresentação das telas dos candidatos (V3) de ontem, anotei os seguintes feedbacks:

Comentei algumas com "_-> (...)_"

- as agendas ficam no ligar dos botões de interação e vice versa
- repensar título dos botões “aprovar” e “reprovar” _-> curtir e pressionar ?_
- nos cards da aba APROVADES deixar mais evidente que as redes dos candidates não são share
- conteúdo dos toggles da aba APROVADES será todo repensado
- aba FAVORITES nao tem aba de filtro!
- metadado URNA tá parecendo UMA ( ! ) _-> aumentei o entre espaços entre letras pra melhorar a leitura_
- opção de compartilhar fica apenas na aba FAVORITES _-> essa info se mantém?_
- destaque pro número de urna é importante! talvez valha mais destaque ainda
- foi sugerido que ao invés do candidate receber email a email de aprovações/reprovações, que seja enviado um resumo diário ou semanal, para evitar spam feelings - tipo extrato (micael)
- sobre “dados TSE”: motrar historio de partidos / patrimônio / (...) (micael)
- não há consenso sobre a aplicação das cores: Estão dúvida se usam 2, 3 ou 4 cores.
- IDEIA NOVA: pra quem cumpre os 3 critérios, será habilitado um botão de “apoiar campanha” $
- no desktop: deixa a aba de filtros sempre aberta
- na aba GERAL serão exibidos só de 3 em 3 cards
- sentem necessidade de um botão que exiba apenas os candidatos verdes, mesmo sem estar logado _-> isso é possível usando a aba de filtros_
- os candidatos verdes não podem ser REPROVADOS (aka PRESSIONADOS)
- “tem passado limpo?” vira “atestou passado limpo?”?? (benedito) _-> isso se mantém?_
- agendas voltam a ter cores (incluindo vermelho - para passado sujo) _-> ainda sem consenso geral_
- sugerem mais um elemento sob a foto para o caso de candidatos a reeleição sendo processados / identificar se candidatos são de reeleição ou não?? um gadget? no campo de filtro? _-> isso se mantém?_
- nas abas APROVADES e FAVOTIRES botão PRESSIONAR não existe mais nos cards verdes. ele pode virar o de DOAR 
- DESFAVORITAR não faz sentido com coração de do jeito q tá _-> talvez um coração partido_

Em cima disso, bolei uma nova versão da aba GERAL pra gente analisar soluções pras alterações nos cards: https://invis.io/QCN6WQJ2JS8
nessa proposta, minha sugestão é mantermos as cores amarela, verde e cinza nas fotos e, nas agendas, deixarmos todas brancas e só no caso de candidato ficha suja, deixar o NAO em vermelho. Mais cores que isso receio que deixe o layout muito poluído e esquisofrênico

ainda fala bolar:
- novo icone pro botão PRESSIONAR
- botão DOAR
- desenhar abas Curtidas e Favoritadas
- na página de Alertas, trocar nomenclaturas e icones de Curtidas e Pressionadas

**Comment by parrahenri** [comment]
@luizapeixe :
repensar título dos botões “aprovar” e “reprovar” -> curtir e pressionar ?

CONHECER e PRESSIONAR

**Comment by parrahenri** [comment]
Sobre as Seções:

TODOS
DETALHADOS
FAVORITOS

**Comment by parrahenri** [comment]
@luizapeixe 

opção de compartilhar fica apenas na aba FAVORITES -> essa info se mantém?


Sim, o share só no FAVORITOS

**Comment by luizapeixe** [comment]
Ok! estou trabalhando nas alterações e aviso assim q subir as telas atualizadas, jajá.

Uma consideração sobre as nomenclaturas: é interessante que o botão CONHECER e a aba DETALHADOS tenham uma relação direta em suas nomenclaturas, já que a ação do clique no botão adiciona candidatos à essa aba. Que tal se fosse botão SELECIONAR e aba SELECIONADOS?

**Comment by parrahenri** [comment]
Gostei!

**Comment by luizapeixe** [comment]
telas alteradas!

aba Todos: https://invis.io/SPN6XE5NFGC
aba Selecionados: https://invis.io/PTN7U215BQW
aba Favoritos: https://invis.io/ZUN7U15JD4C

**Comment by luizapeixe** [comment]
Pessoal, as telas estão atualizadas e alinhadas de acordo com os feedbacks. Link para as 3 telas:

-> https://invis.io/J2N8S2ZQPGX

O que **NÃO** foi considerado nessas telas foi:

1. outra estrutura dentro do toggles na aba SELECIONADOS -> precisamos de um exemplo deles de quais infos estarão dispostas nos toggles
2. elemento sob a foto para o caso de candidatos a reeleição sendo processados / identificar se candidatos são de reeleição ou não?? um gadget? no campo de filtro? -> isso se mantém?
3. mais destaque do número da urna na aba FAVORITOS -> acho que está OK do jeito que está agora

De resto, fiz tudo da lista de feedbacks.

dúvidas: 1. Acham que precisamos trocar os ícones de SELECIONAR e PRESSIONAR? Eu tendo a crer que está OK do jeito que está, com joinhas pra cima e pra baixo. 2. o que acham do ícone de doar sendo aquela carteira aberta?

**Comment by ricardopoppi** [comment]
Pessoal, @luizapeixe @parrahenri fechando essa issue pois as issues especificas de implementação já foram criadas. Qq comentário e ajuste deve ser comentado nelas agora:
(i) implementação dos cards sem os detalhes: #103 
(ii) implementação dos detalhes: #104
