### ISSUE TITLE
Formular regras de negócio para os diferentes níveis de usuários do besouro

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#40]
Hoje tenho mapeado o seguinte sistema de permissões (peço ao @parrahenri opinar):
1) Usuário comum da campanha (não cria missões, só aceita ou conclui, não cria frases etc)
2) Usuário staff da campanha (cria missões, cria frases etc)
3) Usuário (pré-)candidato (não cria missões, não cria frases, mas tem alguns níveis de interação com o seu card)
4) Usuário superadmin (pode tudo, administra o sistema)

**Comment by parrahenri** [comment]
@ricardopoppi usuário 2 pode ser opcional pq o 4 resolve (TI distribui o email/senha superadmin) pra quem quiserem. Isso se gerar complexidade.

1. Usuário comum da campanha (não cria missões, só aceita ou conclui, não cria frases etc)
-> na verdade falamos que o usuário comum poderá criar frases, é um trofeu que ganha.

3. Usuário (pré-)candidato (não cria missões, não cria frases, mas tem alguns níveis de interação com o seu card)
- única coisa que faz na verdade é aderir a um dos 3 campos que podem torná-lo amarelo ou verde

**Comment by ricardopoppi** [comment]
@parrahenri é importante manter o 2, pq não podemos distribuir superadmins por aí, vulnerabiliza o app (qq uma dessas pessoas consegue apagar usuário, apagar todos os dados etc)

sobre o (1) ok, vamos formular isso na gamificação da fase 3, então essa estrutura considera apenas as permissões estáticas, ou seja as de inicio.

sobre o (3), essa edição dos três campos já justifica um role (papel) pra esse usuário, distinto dos demais.

Na minha avaliação, suas observações confirmam minha proposta inicial. O que acha?

**Comment by parrahenri** [comment]
De acordo!

**Comment by ricardopoppi** [comment]
Fechando essa pois criei a #64 para implementação
