### ISSUE TITLE
Criar faixa que convida ao APP para a home do unidoscontraacorrupcao

### ISSUE THREAD

**Issue by luizapeixe** [unidoscontraacorrupcao/ej-server#5]
Criar elementos convidativos para compor a faixa de "MOBILIZE" na landing page do http://www.unidoscontraacorrupcao.org.br/

**Comment by luizapeixe** [comment]
Criei uma proposta em versão desktop e subi no invison porém como o protótipo ali está setado para visualização em Mobile, criei essa issue pra gente considerar essa demanda e também para ter uma visualização decente da proposta. Não fiz ainda nenhuma sugestão editorial ou de conteúdo, apenas repliquei a solução que encontramos para o EJ. Eis:

![desktop faixa para a home](https://user-images.githubusercontent.com/6249788/41478320-a050beda-709d-11e8-8141-56aca0791c93.png)

O que acham?

**Comment by parrahenri** [comment]
Gostei da proposta e já vou sondar o cliente!

**Comment by ricardopoppi** [comment]
proposta já apresentada ao cliente, fechando essa issue então
