### ISSUE TITLE
Definir imagem default para o perfil de usuário

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#52]
Quando um novo usuário é criado ele deve herdar essa imagem default de perfil (@luizapeixe qdo puder carrega ela nos assets)

No menu com 80x80px, no thumbnail da missão com 40x40px e na página de perfil com 320x250px mais um filtro de cor #312783 com 50% de opacidade (para garantir a leitura do NOME e STATUS do user, que são infos sobrepostas a imagem no perfil):

![captura de tela 2018-07-12 as 12 58 49](https://user-images.githubusercontent.com/6249788/42645092-876e8d7a-85d3-11e8-8317-83bc2886aca7.png)

**Comment by luizapeixe** [comment]
tá lá! subi em .png para conservar o efeito de cores sobrepostas característico da identidade visual do Unidos Contra a Corrupção
