### ISSUE TITLE
Conteúdos estáticos devem abrir na mesma aba

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#53]
Atualmente o conteúdo "Voltar ao novas medidas" abre em uma aba nova, por exemplo. Vamos padronizar que todos os estáticos devem ser carregado na mesma aba do brower

**Comment by danielhmarinho** [comment]
@ricardopoppi epnsando aqui acho que seria melhor que todos abrissem em outra aba mesmo. No app o comportamento vai ser abrir no navegador independente da implementação. No navegador eu acho melhor pois faz parte de outro domínio além de não ter forma fácil de voltar desses domínios para o app.
Além disso fazendo testes dessa forma quando eu voltava pelo própiro navegador a aba do Chrome travava tudo e eu tinha que fechar pra conseguir acessar o app novamente.
Por esse pontos penso que todos os links devem abrir uma nova aba mesmo.

**Comment by ricardopoppi** [comment]
@danielhmarinho pelo potencial de bug na mesma aba, acho que pode ser mais prudente implementar em abas separadas. Mas talvez essa não seja a solução definitiva, pois a landing page da campanha será reformulada para fazer menção ao app, possibilitando um retorno mais fluido.

Por hora mantemos me outra aba para evitar bugs, inclusive em virtude do PWA. Quando concluir, pode fechar essa issue que a gente cria uma nova qdo a nova landing da campanha entrar no ar (ainda vai demorar uns dias) (cc @parrahenri )

**Comment by danielhmarinho** [comment]
@ricardopoppi vou implementar abrindo em outra aba e quando a nova landing entrar a gente alterar o comportamento.
