### ISSUE TITLE
Splash de usuário deslogado deve apresentar opção para login também

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#55]
Além da opção para cadastro, opção de login deve ser oferecida ao usuário também. Conforme wireframe atualizado: https://projects.invisionapp.com/d/main#/console/14558908/306943819/preview

![photo_2018-07-12_21-38-02](https://user-images.githubusercontent.com/1162183/42666522-0ad71cd4-861c-11e8-9306-2506af8ecf23.jpg)

**Comment by danielhmarinho** [comment]
@ricardopoppi O problema com essa issue é que o hoje a logica que é implementada pelo app joga o usuário sempre no login. quando você acessa o cadastro a rota continua sendo /login. Para separar os componentes em duas rotas daria um pouco mais de trabalho, mas e for isso tudo bem, eu refatoro a lógica, pq hoje voce clicando no botão de cadastrar na modal voce é jogado para o /login com o login renderizado. Em resumo os dois botões de dessa modal fariam a mesma coisa, o que não vejo como o comportamento correto.

**Comment by ricardopoppi** [comment]
Eu proponho uma solução (cc @luizapeixe ):
1) não refatorar as rotas
2) Manter apenas o botão, só que em vez de "CADASTRE-SE" trocar por LOGIN. 

Explico: Como 99% dos usuários vão usar os botões sociais, o login renderizado tb será uma espécie de "cadastro" pra eles. Para os 1% que não usarem, a tela de login dá a opção de CADASTRE-SE ao final, então tb resolve.
