### ISSUE TITLE
Propor estilo para os conteúdos estáticos do app

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#57]
@luizapeixe, peço propor estilo para os conteúdos estáticos (ex: AJUDA, PRIVACIDADE).

Atualmente, eles foram implementados sem estilo:

![captura de tela de 2018-07-13 12-54-25](https://user-images.githubusercontent.com/1162183/42701162-36652ca8-869c-11e8-86ee-b74bf3464abf.png)

**Comment by luizapeixe** [comment]
que tal e assim: https://invis.io/AMKSPGK26WN#/309116957_Mobile_Portrait_Pa-gina_Esta-tica

**Comment by ricardopoppi** [comment]
achei ótimo @luizapeixe ! vou colocar para implementação
