### ISSUE TITLE
Atualização da tela de profile para incluir troféus e pontos

### ISSUE THREAD

**Issue by parrahenri** [unidoscontraacorrupcao/ej-server#6]
@luizapeixe veja a primeira versão da gameficação que temos de implementar (abaixo). Do pontod e vista da tela de perfil, precisamos atualizar com uma barrinha de progresso pra pessoa obter o PERFIL CAMPEAO e desenhar os troféus descritos:

https://docs.google.com/document/d/10yVU-vNPAym39TCc67NoSyKTf4bF3L_zrM8ZimJG0VE/edit?usp=sharing

Se tiver alguma dúvida me avisa! :)

--------
--------
--------
Descrição da funcionalidade de Missões:
Missões têm título (1), imagem, áudio ou vídeo (2) e permitem que os usuários aceitem (3), comentem dentro da missão (4) e comprovem sua realização enviando link/ arquivo (5)

Mecânica MVP (viável para primeira entrega): cada missão corresponde a um troféu.
Táticas de gamificação v1:
(i) Missão completar o perfil.

Troféu tipo Perfil campeão (individual), definindo como níveis o preenchimento de diferentes conjuntos de informação do perfil, ou seja, terá todos os níveis quem completar todos esses conjuntos, o que cria uma progressão e estimula metas intermediárias. Medalha fácil de obter logo no início.

Detalhamento:

Perfil campeão: Nome, Email, CEP, Telefone, Foto e demais campos que a campanha avaliar como necessários correspondem a pontos para totalizar a pontuação do perfil campeão, o que atribui um troféu e um símbolo no perfil (criando uma distinção social, à exemplo dos perfis verificados). Esse primeiro troféu é de baixa dificuldade.

Nome 10 pontos
Email 10 pontos
CEP 20 pontos
Telefone 20 pontos
Foto 20 pontos
etc

obs: objetivo é totalizar 100 pontos. Essa barra de progresso nos pontos deve ser mostrada ao usuário com porcentagem (%), indicando o quanto falta para ele conquistar o perfil campeão.

(ii) Missão Apoiar Campanha Unidos Contra a Corrupção

Troféu tipo Apoiador de abaixo-assinado (individual e sem níveis) Cada novo abaixo-assinado criado "retira" a medalha dos participantes, fazendo com que eles tenham a motivação de assinar de novo. Medalha fácil de obter logo no início.

Detalhamento:

Missão simples na qual o usuário vai clicar para assinar o abaixo-assinado Unidos Contra a Corrupção. O sistema deve ser capaz de identificar no BD se o usuário já assinou (pela chave de email) e mostrar essa informação. Para os que ainda não tiverem assinado, deve apresentar os campos para que o usuário faça (botão para clique/assinatura). Realização dessa ação rende o troféu "APOIADOR". Troféu bem simples de ser obtido. Dificuldade baixa.

(iii) Missão Compartilhar pedido de assinatura no Grupo da Família ou Grupo de amigos

Troféu tipo Compartilhar nas redes sociais (individual), ação única, sem níveis para essa medalha. Realização da ação é comprovada com print screen. Tela da missão já terá o botão de compartilhamento para facilitar a ação. Troféu recebido após confirmação de que missão foi realizada é do tipo Ativista de Whatsapp.

(iv) Missão Compartilhar Pedido de assinatura no Facebook

Troféu tipo Compartilhar nas redes sociais (individual), ação única, sem níveis para essa medalha. Realização da ação é comprovada com print screen. Tela da missão já terá o botão de compartilhamento para facilitar a ação. Troféu recebido após confirmação de que missão foi realizada é do tipo Ativista de Facebook.
(v) Troféu atribuído a partir da obtenção de outros troféus anteriores

Troféu tipo Super Ativista: É concedido a partir da soma dos troféus de tipo Apoiador + Ativista de Whatsapp + Ativista de Facebook. Esses três troféus "liberam"/ ativam um quarto (reforçando a ideia de que o participante obteve um resultado importante).

(vi) Missão Criar grupo de Whatsapp para mobilizar pela campanha
Essa missão só é "liberada" para os que tiverem o troféu de super ativista.

Troféu tipo Mobilizador (individual), ação única, sem níveis para essa medalha. Realização da ação é comprovada com print screen. Essa Missão será uma base importante para as futuras missões que envolvam ações presenciais mais específicas, destaque na comunidade (ranking) e prêmio de funcionalidades específicas (EJ).

Essa funcionalidade futuramente será contabilizada dentro do PERFIL SUPER CAMPEÃO.

**Comment by ricardopoppi** [comment]
@luizapeixe @parrahenri sobre a pontuação: como ela se aplica apenas ao preenchimento de pefil e sua medalha/troféu, sugiro usarmos sempre em porcentagem na exibição dessa informação (estou orientando o back a desenvolver assim)

**Comment by parrahenri** [comment]
boa, @ricardopoppi! @luizapeixe acho massa implementarmos algumas das reflexões que rolaram há um tempo atrás quando pesquisou o duolingo. A missão principal é ajudar o usuário a entender quais são as maneiras de ganhar as medalhas (regras pra isso). :)

**Comment by ricardopoppi** [comment]
Pra ajudar, tirei do resumo uma lista organizada de medalhas, compartilho aqui:

**Resumo das medalhas/troféus:**

Troféu Perfil campeão (completamento do pefil)
Troféu Apoiador (cumprir a missão de apoiar abaixo assinado)
Troféu Ativista de Whatsapp (cumprir a missão de compartilhar a campanha no zap)
Troféu Ativista de Facebook (cumprir a missão de compartilhar a campanha no face)
Troféu Super Ativista (soma dos troféus de tipo Apoiador + Ativista de Whatsapp + Ativista de Facebook)
Troféu Mobilizador (após completar a missão "Criar grupo de Whatsapp para mobilizar pela campanha"). Para o usuário ter acesso a essa missão, requer possuir "Troféu Super Ativista".

**Comment by parrahenri** [comment]
1. Sobre as telas refeitas: gostei! :)

2. Sobre: 

Sobre a barra de progressão nas missão, fiquei com uma dúvida: Apenas algumas missões terão barra de progressão e outras não? Penso que seria interessante que todas tivessem, por exemplo, penso que as missões de assinatura de abaixo-assinados podem ter % de conclusão tb, tipo, ela é concluída qnd o user assina um abaixo mas qnd aparece um novo abaixo-assinado no app, a barra de progressão cai e o user perde o trofeu e só o ganha de novo qnd assinar o novo abaixo e subir novamente a barra de progressão ao 100%. O mesmo pode valer para os troféus de WhatsApp e Facebook, tipo de tempos em tempos essa barra pode cair (como faz o duolingo, por exemplo).

Concordo! Gostei da sua proposta!

3. Dúvida sobre relevância da autoria das missões: Nesse primeiro momento apenas os TI criação as missões, certo? Então podemos, por ora, retirar a info de autoria das missões dos thumbs e também páginas internas das missões? Ou melhor manter para já implementar prevendo a necessidade de criar esse campo no futuro, qnd users comuns também estiverem criando missões?

Que acha @ricardopoppi? 

4. Me baseei no estilo de iconização da identidade visual do projeto utilizada na landing page mas pessoalmente ainda acho as soluções pouco aprofundadas. Penso que nossos troféus podem ficar mais legais e com mais personalidade, porém quis compartilhar essas soluções até aqui pq precisaria de um pouco mais de tempo para criar soluções mais elaboradas :P

Quando elaborar mais um pouco, avisa! Realmente temos que seguir a idv da campanha!

**Comment by ricardopoppi** [comment]
Parabéns @luizapeixe ficou legal demais! Ó, sobre a autoria, acho que temos que manter sim. Mesmo que nesse momento as missões serão criadas pela TI e Coalizão, temos um indicativo que no futuro a gamificação destrava para os usuários. Então o app já "ensinar" que missões são criadas por atores acho produtivo.

**Comment by luizapeixe** [comment]
ok! Vou colocar de volta a autoria nos posts, porém acho que vou dar menos destaque pra essa info. ainda temos tempo de alterar um pouco os layouts? qnd vamos mandar pro cliente mesmo? De tarde? :P Sobre os troféus mais elaborados, acho que podemos combinar para as próximas entregas outras opções de troféus. O que vocês acham?
