### ISSUE TITLE
Foto de perfil aparenta carregar mas não é gravada pelo app

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#60]
Para reproduzir (mobile):

1) Crie um novo usuário
2) Edite o perfil
3) Carregue a foto
4) Recarregue a tela de perfil
5) Note que o local da foto segue na cor cinza, a foto carregada anteriormente desaparece

**Comment by danielhmarinho** [comment]
@ricardopoppi aparentemente o problema aqui era que a requisição para enviar a foto só era feita após a função de desenhar a foto na tela. Mudei a ordem das chamadas e espero que o problema não ocorra mais.
