### ISSUE TITLE
Troféu Superativista não deve exibir link para missão

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#69]
O troféu Superativista é do tipo "Complete on requirements satisfied?" = true

Por isso ele não possui link de missão ("Reference link:" em branco).

Nesse caso ele não deve exibir link para missão na galeria. Hoje está exibindo um link, conforme imagem abaixo:

![photo_2018-07-17_00-01-49](https://user-images.githubusercontent.com/1162183/42794348-9faad5b8-8954-11e8-9668-50c604b8ccc1.jpg)

**Comment by davidCarlos** [comment]
@ricardopoppi eu tinha visto esse comportamento, mas não propus uma correção pq queria discutir isso antes. O que eu devo exibir no logar do "ver missão" ? Se eu simplesmente não exibir nada vai ficar apenas o badge do troféu.

**Comment by ricardopoppi** [comment]
@davidCarlos nesse caso, mostrar somente o badge e o nome é o comportamento adequado mesmo. Ele já foi obtido. O modal de detalhes que aparece antes dele ser obtido já cumpre o papel de gerar engajamento pela galeria.
