### ISSUE TITLE
Criar lógica de usuário admin x comum no django

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#7]
A diferenciação é para que só os usuários admin tenham acesso ao botão de criação de missão

**Comment by arkye** [comment]
Uma solução parcial (sem afetar o ej-server) foi desenvolvida e está na develop do `besouro-app`.

**Comment by ricardopoppi** [comment]
@davidCarlos lógica pra usar na hora de decidir se o botão de criação de missão aparece ou não. criando issue específica pra isso e fechando essa.
