### ISSUE TITLE
Foto tirada pela câmera do celular não persiste no banco

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#70]
Para replicar:

1) Edite perfil
2) Clique no botão rosa de carregar foto
3) Escolha a camera do celular, tire a foto com o celular deitado
4) Veja que a foto apareceu no local do perfil
5) Salve
6) Recarregue
7) Note que a foto nova não foi gravada

**Comment by danielhmarinho** [comment]
@ricardopoppi refatorei muitas coisas na forma que esta funcionalidade estava implementada. Agora aparece um spinner de loading quando o usuário sobe a foto, além de que a nova foto sé é desenhada após a requisição na api ser feita, evitando que o usuário ache que a foto ja foi enviada antes da requisição acabar.

**Comment by ricardopoppi** [comment]
sensacional!
