### ISSUE TITLE
criar estilo com cores diferentes pros toasts

### ISSUE THREAD

**Issue by luizapeixe** [unidoscontraacorrupcao/ej-server#72]
"poderiamos pensar cores diferentes para os toasts que aparecem apos algumas açoes? (aqueles cards rosa quando acontece algum erro por exemplo ou quando atualiza o perfil) pq os cards sem diferença de estilo vai dar impressao que tudo e erro"

toast: 
![photo_2018-07-23_15-41-01](https://user-images.githubusercontent.com/6249788/43096299-010fc5c2-8e8f-11e8-8049-ac2f678b5bfc.jpg)

**Comment by luizapeixe** [comment]
@ricardopoppi @davidCarlos será que conseguimos fazer uma lista de todas as possibilidades de toasts? Assim fica mais claro e garantido como atribuir as diferentes cores a eles. Vou começar a lista e você podem complementa-la com aquilo que souberem, ok?

• Página lista de candidates:
- Candidate Selecionade com sucesso 
- Candidate Pressionade com sucesso
- Candidate Favoritade com sucesso

Obs.: Seria maravilhoso se a gente conseguisse alterar o pronome das frases de acordo com o gênero da pessoa do card, tipo sendo homem "Candidato selecinado com sucesso" e sendo mulher "Candidata selecinada com sucesso". Isso é possível?

**Comment by ricardopoppi** [comment]
@luizapeixe legal essa provocação. por hora vc poderia propor dois estilos de toasts, um para sucesso e um para erro. durante a fase 3, já usaríamos esses estilos pra tudo que for sucesso e erro também. Aí a gente conseguirá avaliar melhor se há um terceiro ou quarto tipo de toast que mereça estilo próprio (tendo a achar que para toasts não teremos essa necessidade).

Que tal?

**Comment by luizapeixe** [comment]
Ok! Faz todo sentido, @ricardopoppi 

Então que tal assim:

![captura de tela 2018-07-30 as 21 59 50](https://user-images.githubusercontent.com/6249788/43431374-e8d23048-9443-11e8-87a5-f7185f4abb00.png)

no de sucesso é background #E6007E e texto #FFF
no de erro é background #B7B8B7 e texto #333

**Comment by ricardopoppi** [comment]
@luizapeixe ficaram otimos, atualiza no invision pra eu poder fechar essa e abrir a de implementação

**Comment by luizapeixe** [comment]
ok!

toast de sucesso: https://invis.io/K5NBEN4F4PX
toast de erro: https://invis.io/SUNBEPJYQ3B

daí fiz também um toast coringa, que podemos usar em situações não são nem se sucesso nem de erro, algo como um aviso, um alerta, algo assim

toast coringa: https://invis.io/KENBEQNABUH

**Comment by ricardopoppi** [comment]
maravilha! fechando a issue pra abrir pra implementação
