### ISSUE TITLE
Trofeu superativista revelando a "cor" antes do segundo troféu pre-req ser obtido

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#73]
O troféu superativista é configurado no trophy como tendo prereq os trofeús ativista de whatsapp e ativista de facebook.

Ao completar a missão do trofeu ativista de whatsapp ele já fica colorido. Esse comportamento só seria esperado quando a missão do trofeu ativista de facebook estivesse concluída.

![captura de tela de 2018-07-23 21-52-25](https://user-images.githubusercontent.com/1162183/43110648-8ebcd520-8ec3-11e8-8a9b-3e7f6d2e9a4f.png)

**Comment by davidCarlos** [comment]
Não consegui reproduzir o bug. Conclui a missão "ativista do whatsapp", aceitei a missão "ativista facebook" (mas não conclui), e o badge do super ativista se manteve correto.

![image](https://user-images.githubusercontent.com/2847027/43208068-e17e0a3a-8fff-11e8-8f23-5f83dbe8cfc3.png)

**Comment by ricardopoppi** [comment]
bug não está acontecendo mais, fechando a issue
