### ISSUE TITLE
Criar tela de "splash" quando o usuário ganha um troféu

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#8]
Quando o usuário completa a missão e ganha um troféu deve ser exibido um "splash" para ele. Precisamos conceber visualmente esse splash

**Comment by luizapeixe** [comment]
aí vai uma proposta de splash: https://invis.io/YTLUVLMFUP7#/305375052_Mobile_Portrait_Splash_De_Trofeu

ainda não consegui tempo para me debruçar na criação de outras opções de troféus mas isso está entre minhas prioridades. pretendo mostrar novas opções entre essa e a próxima semana

**Comment by ricardopoppi** [comment]
Legal, com essa proposta já é possível implementar. Vou criar uma issue específica sobre as propostas visuais dos troféus em si @luizapeixe
