### ISSUE TITLE
A frase em negrito está chamando mais atenção que o conteúdo do comentário

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#80]
Acho que precisamos pensar em como fazer com que o conteúdo do comentário tenha mais destaque que o título: "vote e nos ajude...". 

Façam o teste votando, observem que o título é o que a gente le primeiro. O conteúdo do comentário fica quase apagado. (@parrahenri)

Atualmente na implementação está assim:

![photo_2018-07-25_01-36-03](https://user-images.githubusercontent.com/1162183/43179905-98c3bc6c-8fab-11e8-8d10-e4d6adbba2f9.jpg)

**Comment by parrahenri** [comment]
Que tal inverter o "vote e nos ajude..." com o comentário? @luizapeixe e @ricardopoppi

**Comment by parrahenri** [comment]
Só inverteria a posição. Botaria a frase "vote e nos ajude..." mais abaixo, perto dos botões

**Comment by ricardopoppi** [comment]
@luizapeixe resolveu a questão do destaque! A partir da proximidade com o processo de desenvolvimento, estamos criando a possibilidade de que mais de uma conversa seja associada a missão. 

Revendo esse modal, fiquei preocupado com o texto, agora mais claro, que já define para que vai servir a opinião dos usuários: "Vote e nos ajude a identificar ideias e ações importantes para melhorar a campanha". 

Talvez a gente devesse ser mais genérico, tipo: "Vote e nos ajude a melhorar a campanha". Dessa forma, as frases aí poderão ser mais amplas que ideias e ações. Como não experimentamos ainda, não sabemos que tipo de frases serão criadas, eu optaria por deixar um conteúdo fixo desse o mais genérico possível. Acha que isso tem impactos na ux @luizapeixe? O que acha @parrahenri?

**Comment by parrahenri** [comment]
De acordo, @ricardopoppi

**Comment by ricardopoppi** [comment]
@luizapeixe pode atualizar os wireframes? assim facilita pra passarmos à implementação dos ajustes

**Comment by luizapeixe** [comment]
Ok! Atualizado: https://invis.io/23N60KQVGA5

**Comment by parrahenri** [comment]
gostei!
