### ISSUE TITLE
Conceber uma variação do splash de agradecimento de voto nas frases

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#82]
Nas situações em que o usuário clicar no push de frases para votar e já tiver anteriormente votado em todas as frases, um splash deve ser exibido. Essa situação poderá acontecer, já que o push de frases será enviado pelo admin para todos os usuários que aceitaram/concluiram uma determinada missão.

O comentário https://github.com/unidoscontraacorrupcao/besouro-app/issues/22#issuecomment-408226899 também explica sobre isso

Sugestão inicial de texto, tirada do comentário https://github.com/unidoscontraacorrupcao/besouro-app/issues/22#issuecomment-408255737

UAU!
VOCÊ VOTOU EM TODAS AS OPINIÕES DESSA MISSAO!

Agradecemos demais seu engajamento!
Aceite e conclua missões para ajudar ainda mais a campanha!

**Comment by luizapeixe** [comment]
done: https://invis.io/2GN7UTNH8WS

tomei a liberdade de trocar "UAU!" por "UHUL!" porque o UAU em caixa alta e nesse tipografia me soou como um uivado de cachorro. Achei que o UHUL se comportou melhor nesse sentido. Tudo bem?

**Comment by ricardopoppi** [comment]
@luizapeixe ficou massa! fechando a issue e atualizando a issue da integração dos cards pra implementação desse splash
