### ISSUE TITLE
Propor como exibir msg sobre coleta de dados facebook

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#85]
Na oficina recebemos o feedback: "precisamos avisar os usuários que puxamos dados do face (quando faz login assim), mas não publicamos nenhuma info nem cedemos infos pro face"

@luizapeixe pode propor como vamos exibir essa mensagem? o ideal seria sem nenhum modal ou splash a mais. Talvez no próprio espaço ao lado da logo do facebook? como fazer isso sem poluir? (cc @parrahenri )

**Comment by luizapeixe** [comment]
Que tal assim: https://invis.io/KWN97AI3ZCV

**Comment by parrahenri** [comment]
gostei!

**Comment by ricardopoppi** [comment]
Fechando essa, issue #95 aberta para implementação
