### ISSUE TITLE
criar imagens e ícones de novas 4 missões

### ISSUE THREAD

**Issue by parrahenri** [unidoscontraacorrupcao/ej-server#86]
Criar imagens e ícones para as 4 missões:

https://docs.google.com/document/d/1_KjQEdB413xBa2h9fMRi0OE7UhziF3po3d8y1V5Cf0Q/edit?usp=sharing

**Comment by luizapeixe** [comment]
aí vai uma primeira leva de propostas:

(vii) Avatarface
![capa_missao7](https://user-images.githubusercontent.com/6249788/43430519-bc2cc11a-943f-11e8-8e47-ac9a7e2023b3.png)

(viii) Mudar seu perfil no facebook
![capa_missao8](https://user-images.githubusercontent.com/6249788/43430528-c6a431e6-943f-11e8-8998-f07187a1f255.png)

(ix) cabo eleitoral
![capa_missao9v2](https://user-images.githubusercontent.com/6249788/43430593-1f1bdd92-9440-11e8-8a5a-32a03716674f.png)

(x) multiplicador
![capa_missao10](https://user-images.githubusercontent.com/6249788/43430601-27a4f958-9440-11e8-9180-f38d34d21bc9.png)

(xi) status whatsapp
![capa_missao11](https://user-images.githubusercontent.com/6249788/43430608-2e8ed6f8-9440-11e8-8579-961b1aca7f92.png)

**Comment by parrahenri** [comment]
@luizapeixe essas são as imagens né? faltam os ícones?
Gostei dessaS: viii, ix e xii

São só 4 novas missões né? então falta só definir 1 imagem. Achei que a xi é boa, mas tá bem diferente das demais já feitas não? acho que vale algum numa identidade mais próxima.

**Comment by luizapeixe** [comment]
Verdade! Avatarface (vii) e Mudar Perfil do Facebook (viii) são a mesma! Concordo que a viii está mais bacana que a vii pra essa missão. Então, excluindo a vii, temos aqui opções pras 4 missões descritas no doc.

Faltam os ícones sim. Não tive tempo de produzi-los ainda. Apresentarei opções até o fim do dia de amanhã, no máximo, tudo bem?

As imagens realmente não estão seguindo uma unidade estética. Isso é proposital, como expliquei nas leva anterior de missões, penso que não seguir um padrão pode ser interessante pq assim cada missão tem a liberdade de ter sua própria personalidade e estilo (umas mais cômicas, outras mais sérias... de acordo com seus contextos específicos). Outro fator que me leva à esse posicionamento é que, pensando que futuramente outras frentes além da TI poderão criar missões, já não teremos uma unidade entre as capas de missões anyway, certo? O que você acha?

**Comment by parrahenri** [comment]
São 3 ícones de cada pros diferentes momentos da missão, mais o ícone que vai aparecer na galeria de trofeus, é isso?

**Comment by ricardopoppi** [comment]
@luizapeixe @parrahenri os ícones são para os TROFEUS

**Comment by luizapeixe** [comment]
e uma nova proposta pra capa da missão (x) multiplicador

![rectangle 3 copy 24](https://user-images.githubusercontent.com/6249788/43495922-00d458f6-9511-11e8-9709-eb15ce418eaf.png)

**Comment by parrahenri** [comment]
por mim aprovados!

**Comment by parrahenri** [comment]
@ricardopoppi @davidCarlos

**Comment by parrahenri** [comment]
@luizapeixe me manda esses ícones separadamente pra eu já subir?

**Comment by luizapeixe** [comment]
acabei de subir os Troféus lá no drive: https://drive.google.com/open?id=1a4bKhpU8S5YE6OX9qDO_pp2uOJIcXEb-

Você acha cada um deles pela nomenclatura: badget_<NomeDoTrofeu>X
esse X se traduz em números, assim:
X = 1 -> Troféu conquistado
X = 2 -> Troféu não-conquistado
X = 1v2 -> Primeiros Troféus conquistado com o novo design aplicado

**Comment by ricardopoppi** [comment]
msgs criadas, fechando essa issue
