### ISSUE TITLE
Troféu Ativista de whatsapp dispara trofeu superativista por engano

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#88]
Ao ganhar trofeu ativista de whatsapp, recebi trofeu e notificações do trofeu superativista por engano, já que o outro pre-req desse trofeu ainda não tinha sido obtido

![captura de tela de 2018-08-01 08-28-25](https://user-images.githubusercontent.com/1162183/43519264-29519cae-9565-11e8-9ecc-78d1dd4ee599.png)

**Comment by davidCarlos** [comment]
Tentei reproduzir no meu ambiente local mas não consegui. Farei mais alguns testes no ambiente de homologação.

**Comment by davidCarlos** [comment]
Realmente era um bug. Consegui replicar e está resolvido.
