### ISSUE TITLE
Notificação de admin não está clicavel no link inserido no body

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#90]
O link inserido no body da message object deveria ser clicável qdo a notificação chega na inbox

Para testar: Enviar pelo canal (2) de admin, o message object (16) criado no dev

**Comment by danielhmarinho** [comment]
@ricardopoppi Acho que esse comportamento não tinha ficado muito claro na pagina de notificações. O link então tem que aparecer de forma explicita na notificação? Ele ser clicável cria um problema tambem de precisar mudar o evento do card que ja redireciona para a pagina do link

**Comment by ricardopoppi** [comment]
Quando o admin inclui um link no body a ideia é a notificação direcionar pra ele. Creio que não precisa aparecer, apenas a msg ser clicável mesmo

**Comment by ricardopoppi** [comment]
testamos e esse bug não existe, o link está clicável novamente
