### ISSUE TITLE
Notificação de opiniões para votar não chegou ao usuário (missão 5)

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#91]
Objetos criados:

(i) channel object (6)
(ii) message object (17) (tive que replicar o conteudo do title no body pro django permitir salvar)
(iii) notification object (105)

**Comment by davidCarlos** [comment]
Não consegui reproduzir @ricardopoppi. Aceitei a missão, redisparei a mensagem, e ela chegou na minha pagina de notificações. Podemos realizar o teste com outro usuário.

**Comment by ricardopoppi** [comment]
@davidCarlos essa eu vou debugar melhor e atualizo aqui, pode ser que esse bug nem exista pois eu estava criando a entrada de notifications no admin e possivelmente gerando inconsistências

**Comment by ricardopoppi** [comment]
testei e funcionou, não consegui replicar. fechando
