### ISSUE TITLE
Ativar a API de push (cloud) nas notificações do app

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#94]
A partir da API ativada pra receber push "de verdade", [a tela de configurações](https://projects.invisionapp.com/d/main#/console/14558908/308496265/preview) passa a funcionar. Pois o disable só desabilita o recebimento de push e não a existencia da notificação na inbox.

A opção "Permito que a campanha me envie notificações aqui no app" deve vir MARCADA por default e quando o usuário DESMARCA é o mesmo que desabilitar as quatro categorias ao mesmo tempo (cc @danielhmarinho )

**Comment by parrahenri** [comment]
@luizapeixe viu essa? pelo que eu entendi é exatamente isso @ricardopoppi

**Comment by luizapeixe** [comment]
faz sentido pessoal, acho que é isso mesmo: se desmarcar a opção "Permito que a campanha me envie notificações aqui no app", automaticamente desmarca todas categorias de notificações.

**Comment by ricardopoppi** [comment]
@parrahenri @luizapeixe ok, já atualizei o corpo da issue com isso

**Comment by danielhmarinho** [comment]
@ricardopoppi existe alguma mensagem que aparece ao usuário se ele não aceitar ativar as notificações quando o diálogo é mostrado pelo navegador ou celular?

**Comment by ricardopoppi** [comment]
Sim, é essa: "Ok! Não enviaremos notificações por aqui. Você pode reativar elas no painel de configurações de notificações, direto no app"

**Comment by ricardopoppi** [comment]
Textos para o push:

Nova missão: 
Titulo: Nova missão
Conteúdo: Nova missão no ar! Vem conferir
Link: para a interna da missão

Novo trofeu:
Titulo: Novo troféu
Conteúdo: Parabéns! O troféu \<nome-do-trofeu\> é seu!
Link: para a galeria de trofeus

Novas opiniões
Título: Novos comentários
Conteúdo: Tem conteúdo novo! Vem dar sua opinião?
Link: para a interna da missão com o gatilho de opiniões

Seleção:
Título: Seleção feita!
Conteúdo: Você selecionou o candidato \<nome-do-candidato\>
Link: para a aba de selecionados

Pressão:
Título: Seleção feita!
Conteúdo: Você selecionou o candidato \<nome-do-candidato\>
Link: para a home do app

Porém não acho que devemos ativar seleção e pressão como push, não faz sentido. Ou não implementamos ou deixamos esses dois com push desabilitado por default no painel. Só habilita o flood quem quer (@danielhmarinho @parrahenri )

**Comment by danielhmarinho** [comment]
@ricardopoppi eu não acho que faça sentido nem deixar ativar mesmo. Principalmente pleo comportamento de redirecionar o usuário após o click. isso vai gerar muitas navegações desnecessárias. No navegador por exemplo sempre que uma notificação é clicada uma nova aba é aberta no navegador.

**Comment by ricardopoppi** [comment]
nossa, é mesmo! seleção e pressão não podem ser push mesmo. aí aqueles botões do admin das notificações perdem o sentido né?

**Comment by danielhmarinho** [comment]
@ricardopoppi ativar nesses casos tira a funcionalidade das notificações no painel.
"aí aqueles botões do admin das notificações perdem o sentido né" botões de admin? ou o redirecionamento das notificações? não consegui pegar essa poppi

**Comment by ricardopoppi** [comment]
@danielhmarinho me refiro aos botões de ativar/desativar as notificações do painel de configurações do admin. Para todas as outras, elas indicam ativação e desativação dos pushes, correto? Se eu desativo troféus, por exemplo, sigo recebendo na minha inbox, mas não recebo mais push.

Como para selecionar e pressionar não usaremos push, esses botões perdem o sentido para esses dois tipos confere?

Outra coisa importante: aqueles ítens que o usuário responde no painel (checkbox) já estão sendo gravados no banco?

**Comment by danielhmarinho** [comment]
@ricardopoppi sim faz sentido talvez retirar de lá mesmo. Sim os botões do painel ja estão funcionando e eu ja verifico eles antes de mandar o push notification.  Unica interação que flata é aquela de marcar para nao receber notificações e todos serem desmarcados.

**Comment by ricardopoppi** [comment]
maravilha, essa funcionalidade vai ficar show! e vai ser bem efetiva pra levar o pessoal de volta pro app. principalmente as notificações de novas missões, novas opiniões e no futuro a mudança de adesão dos candidatos. sucesso!

**Comment by ricardopoppi** [comment]
@danielhmarinho update só pra lembrar o que decidimos mais cedo: só haverá push as notificações de tipo:
(i) missão
(ii) conversations
(iii) alertas (admin)
(iv) pressionados (pro caso da mudança de opinião)

Obs: a gente não tinha reparado mas o nome da categoria com o thumbs down é "pressionados" e não reprovados. Reprovados vem de um wireframe antigo e nunca observamos pra mudar o nome. Vou abrir uma issue pra isso

**Comment by danielhmarinho** [comment]
@ricardopoppi não vou fechar essa issue pois ainda falta a notificação quando o candidato altera o seu compromisso

**Comment by ricardopoppi** [comment]
@danielhmarinho combinado
