### ISSUE TITLE
Implementar splash quando usuário não tem mais opiniões pra votar

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#96]
@davidCarlos hj mais cedo falamos desse comportamento, mas não me lembrei na hora que tinhamos concebido um splash para o caso do usuário clicar numa notificação de opinião pra votar e já tiver votado em todos os comentários de todas as conversas associadas à missão. É esse aqui: https://projects.invisionapp.com/d/main#/console/14558908/311283130/preview (voltar = fechar)

Esta descrito no corpo da issue principal https://github.com/unidoscontraacorrupcao/besouro-app/issues/22 mas de qq forma especifico aqui também. Chegou a ser implementado?

**Comment by davidCarlos** [comment]
Está implementado em prod. A única coisa que eu não fiz foi colocar o link "voltar", uma vez que já tem o ícone de fechar na modal. Você acha realmente necessário ter esse link "voltar"?

**Comment by ricardopoppi** [comment]
O fechar resolve sim, fechando essa
