### ISSUE TITLE
Formular duas versões das planilhas de dados dos candidatos

### ISSUE THREAD

**Issue by ricardopoppi** [unidoscontraacorrupcao/ej-server#98]
Precisamos preparar duas versões:

1) Planilha com os dados básicos que aparecem no card resumido
2) Planilha com os dados avançados que aparecem nos conteúdos colapsáveis do card expandido e do ver mais

**Comment by parrahenri** [comment]
Fiz essa e submeti ao cliente, vamos ver de validam:


[planilha de dados para besouro.xlsx](https://github.com/unidoscontraacorrupcao/ej-server/files/2257630/planilha.de.dados.para.besouro.xlsx)

**Comment by ricardopoppi** [comment]
Sugestão:
dia 10: infos resumidas
dia 15: update com infos detalhadas

**Comment by parrahenri** [comment]
atualizei assim, vamos ver se aprovam: 
[planilha de dados para besouro_v2.xlsx](https://github.com/unidoscontraacorrupcao/ej-server/files/2258701/planilha.de.dados.para.besouro_v2.xlsx)

**Comment by ricardopoppi** [comment]
Update de status:
1) Estrutura da planilha (formato google drive): https://docs.google.com/spreadsheets/d/1F-y23v3YL0DF8kln0Ea-dPZ2MosP3Jk0tLJjjprwq9w/edit?usp=sharing
2) Planilha com dados dos senadores: 
[exemplo_dados_candidatos.xlsx](https://github.com/unidoscontraacorrupcao/ej-server/files/2273600/exemplo_dados_candidatos.xlsx)

**Comment by ricardopoppi** [comment]
@davidCarlos versão da planilha pronta para carga: 
Planilha feita para primeira importação no app: [exemplo_dados_candidatos_versaocomlinksenomedafoto.xlsx](https://github.com/unidoscontraacorrupcao/ej-server/files/2279737/exemplo_dados_candidatos_versaocomlinksenomedafoto.xlsx)

A explicação dela está na issue da funcionalidade csv: https://github.com/unidoscontraacorrupcao/ej-server/issues/99#issuecomment-412234883

**Comment by ricardopoppi** [comment]
Formato já foi definido e importação segue no ritmo. Fechando essa aqui então
